

[[_idTextAnchor457]]
[appendix]
== Strategic business plans

[[_idTextAnchor458]]
=== Objectives of a strategic business plan (SBP)

. To demonstrate in an objective manner the specific benefits which result from, or are expected from, the work of this technical committee.
+
--
NOTE: These benefits can vary significantly between different fields in which committees are involved: they can be economic (cost savings, reduced time to market, easier access to certain regional markets, lower sales prices), they can be social (improvement of safety for workers, measured in the reduction of accidents) or they can be the improvement of the environmental impact, for example.
--

. To support prioritization and to improve the management of the technical work in a committee.
+
--
NOTE: This includes the definition of target dates and the planning of resources for the work of the technical committee (and its SCs) in relation to the development of new and the maintenance of existing documents.
--

. To increase the transparency in relation to the market forces and the percentage of market share represented within a committee.

All current SBP may be viewed online at https://www.iso.org/bp[https://www.iso.org/bp].


[[_idTextAnchor459]]
=== Development tools and additional guidance

To facilitate the preparation of SBP, ISO Central Secretariat has developed a document template. This template and additional guidance may be downloaded from the ISOTC server at https://www.iso.org/forms[www.iso.org/forms].

[[_idTextAnchor460]]
=== SC.3Procedure for the development of a strategic business plan

[[_idTextAnchor461]]
==== {blank}

The committee secretary, in cooperation with committee members and/or the committee chair, shall prepare a draft SBP. The draft SBP shall be submitted to an internal consultation within the technical committee. It shall be formally agreed upon by the technical committee by way of a resolution, before being submitted to the technical management board for review.

The technical committee shall submit the draft SBP (tmb@iso.org) in revisable (i.e. Word) and PDF-format to the ISO technical management board who will review the draft SBP against the set of minimum requirements for SBPs (see <<_idTextAnchor462>>).


[[_idTextAnchor462]] 
.Requirements for strategic business plans of ISO technical committees
[cols="3*"]
|===
| Item | Description of Requirements | Score

| 1 | Descriptions of relevant dynamics in the business environment related to the work of the ISO committee, and quantitative indictors of trends in this business environment and the acceptance and implementation of the ISO committee's standards. | 1 to 5

| 2 | Descriptions of tangible benefits that the standardization programme is expected to achieve for the business environment. | 1 to 5
| 3 | Descriptions of identified objectives of the ISO committee and strategies to achieve those objectives. This should include descriptions of specific actions that will be taken or that will be proposed to the ISO committee to better respond to the needs and trends of the business environment. | 1 to 5
| 4 | Descriptions of factors that may negatively impact the ISO committee's ability to achieve its objectives and implement its strategies, including information on the representation of the major market forces in the committee (geographically as well as by type, e.g. manufacturer, government, etc.). | 1 to 5
| 5 | Objective information regarding the ISO committee and its work programme that is required:— link added in section 7 to the TC's page on ISO's website About (Secretariat, Secretary, Chair, Date of creation, Scope, etc.), Contact details, Structure (Subcommittees and working groups), Liaisons, Meetings, Tools, Work programme (published standards and standards under development;— priorities assigned to projects in the work programme (if the committee assigns priorities) with an explanation of the reasons/process for prioritization;— relationships of projects to European regional standardization (CEN);— time allocated to each project by working group convenors, project leaders/editors and for translation; and— the range of stakeholders that should be engaged based on the subject area being standardized. a| No score +
 (Yes/No)Mandatory information

|===


[[_idTextAnchor463]]
==== {blank}

An average score of at least 10 is necessary for approval. If the SBP is not approved by the TMB, the technical management board scores and comments will be sent to the committee who will be asked to resubmit the SBP. If approved, the comments from the technical management board shall be taken into consideration during the SBP review at the next plenary meeting.


[[_idTextAnchor464]]
==== {blank}

Once approved by the technical management board, the SBP is made available to the general public for review and comment on a publicly accessible server (https://www.iso.org/bp[https://www.iso.org/bp]) by the ISO Central Secretariat. Member bodies are encouraged to inform the interested public in their countries of the availability of the SBP for public review and, if appropriate, to set links to the SBPs.


[[_idTextAnchor465]]
==== {blank}

The committee shall conduct a review of the SBP, considering all comments received, preferably once per year, but at least once every 3 years. Updated SBP do not need to be submitted for TMB approval -- they shall be approved by consensus within the committee (or, if consensus is not possible, by a simple majority of P-members casting a vote).
