
[[_idTextAnchor470]]
[appendix]
== Numbering of documents


[[_idTextAnchor471]]
=== Working documents (including committee drafts)

Each document (including committee drafts -- see also <<_idTextAnchor472>>) relating to the work of an ISO technical committee or subcommittee circulated to all or some of the member bodies shall have a "N-number" generated by the system that appears at the top right-hand corner of recto pages and at the top left-hand corner of verso pages. The first page of the document shall also bear, immediately under the reference number, the date, written in accordance with ISO 8601 (_Data elements and interchange formats -- Information interchange -- Representation of dates and times_), on which the document was compiled.

Once a reference number is used for a working document, it cannot be used again for a document with differing wording and/or different contents. The same number may be used for a proposal and a voting form (optional). If a document replaces an earlier one, the system generates a new N-number on the first page of the new document.

The N-number is made up of the following two parts separated by the letter N:

. the number of the technical committee (TC) and, when applicable, the number of the subcommittee (SC) to which the working document belongs;

. an overall serial number.

As an example, the reference number will look as follows: *ISO/TCa/SCb Nn*


[[_idTextAnchor472]]
=== Working drafts (WD), committee drafts (CD), draft International Standards (DIS), final draft International Standards (FDIS) and International Standards

When a new project is registered by ISO Central Secretariat (see <<_idTextAnchor147>>), the latter will allocate an ISO reference number to the project. The number allocated will remain the same for the ensuing WD, CD, DIS and FDIS and for the published International Standard. The number allocated is purely a registration and reference number and has no meaning whatsoever in the sense of classification or chronological order. The number allocated to a withdrawn project or International Standard will not be used again.

If the project represents a revision or amendment of an existing International Standard, the registered project will be allocated the same number as the existing International Standard (with, in the case of an amendment, a suffix indicating the nature of the document).

If, however, the scope is substantially changed, the project shall be given a different number.

Successive WDs or CDs on the same subject shall be marked "first working draft", "second working draft", etc., or "first committee draft", "second committee draft", etc., as well as with the working document number in accordance with <<_idTextAnchor471>>.

Successive DIS on the same subject will carry the same number but will be distinguished by a numerical suffix (.2, .3, etc.).
