
[[_idTextAnchor473]]
[appendix]
== Hosting meetings

[[_idTextAnchor474]]
=== Who may host an ISO meeting?

Meetings may be hosted by:

* any ISO member (member body, correspondent member, subscriber member);

* for working group meetings only, any liaison member of the committee concerned.

For technical committee or subcommittee meetings, the ISO member body in the country shall be the host and its pre-approval of the meeting is required.

For working group meetings, the ISO member body in the country shall be informed of the meeting before the meeting is confirmed.

It is not necessary for a host to be a direct participant in the work of the committee concerned, although that will typically be the case.

A potential host shall first ascertain that there are no restrictions imposed by its country or the hosting venue to the entry of representatives of any P-member of the technical committee or subcommittee for the purpose of attending the meeting. In some cases it may be necessary for special permission to be obtained for attendance -- wherever possible the host should assist in determining if this is the case, but it is the joint responsibility of the secretariat or group leader, and the participant to determine any restrictions.

Given that some hosts may not have sufficient meeting facilities and/or other resources of their own, the main host -- say an ISO member -- may accept an invitation from another organization to assist by, for instance, providing a meeting location or organizing a welcoming event.

Irrespective of the actual host of a meeting, responsibility for the meeting concerned rests with the secretary (in the case of a technical committee or subcommittee, or similar groups) or group leader (in the case of working groups, ad-hoc groups, etc.). Thus, potential hosts should liaise directly with these individuals.


[[_idTextAnchor475]]
=== Sponsorship of meetings

Large ISO meetings can be expensive and/or complicated to stage and support, and the resource requirements may exceed those that an ISO member can itself provide. It is therefore acceptable for a meeting to have one or more sponsors contributing to its organization and cost. Nevertheless, whilst it is acceptable for sponsors to be identified, and for their support to be recognized in the meeting, an ISO meeting shall not be used as an opportunity for the promotion for commercial or other reasons of the products or services of any sponsor (see also "Fees for delegates at ISO meetings").

[[_idTextAnchor476]]
=== Proposing or withdrawing support as a meeting host

The _ISO/IEC Directives, Part 1_, request that the following advance notice be given:


[cols="3*",options="header,unnumbered"]
|===
| Meeting of … a| Advance notice of +
meeting date
a| Advance notice of +
meeting location

| Technical committee or subcommittee | 2 years | 4 months

| Working group | -- | 6 weeks

|===

In general, the more notice the better in order that participants may make appropriate travel and business arrangements, and also obtain briefing, where appropriate.

If a host finds that they need to withdraw an offer, these notice periods should also be respected.


[[_idTextAnchor477]]
=== Meeting locations

In planning meetings, account should be taken of the possible advantage of grouping meetings of technical committees and subcommittees dealing with related subjects, in order to improve communication and to limit the burden of attendance at meetings by delegates who participate in several technical committees or subcommittees.


[[_idTextAnchor478]]
=== Facilities to provide at meetings

Any member body offering to host an ISO technical committee or subcommittee meeting undertakes to provide appropriate meeting facilities, including any provisions for interpretation (see <<_idTextAnchor479>>), for the TC/SC, taking into account the normal attendance at such meetings and any requirements foreseen by the committee secretariat for facilities for parallel meetings (for example, of working groups, ad hoc groups or the drafting committee). The working facilities required during a meeting (i.e. additional to rooms) will vary from group to group. This may include printing, and internet access (teleconference facilities). Administrative support may also be needed. The host may be requested, but shall not be obliged, to provide separate facilities serving as the "chair's" or "secretariat" room.

The exact requirements should be determined by the committee secretariat or group leader. Some committee secretariats develop and maintain a standing document to advise member bodies of the facilities that will be required of any potential host of a meeting of the committee, which ensures clear understanding of what will be required. The host of a working group is also expected to provide all basic working facilities.


[[_idTextAnchor479]]
=== Interpretation facilities at meetings

The chair and secretariat are responsible for dealing with the question of language at a meeting in a manner acceptable to the participants, following the general rules of ISO, as appropriate. The official languages at meetings are English, French and Russian, and meetings are conducted in any one or more of these. The typical language combinations are English and French, or English only. In the latter case, French may only be omitted with the explicit agreement of the francophone member(s). Thus, there may be an obligation on the host to provide interpretation between English and French. This needs to be determined in advance. Potential hosts may need to seek assistance from ISO Central Secretariat or from other P-members. The National Body for the Russian Federation provides all interpretation and translation into or from the Russian language.

So far as the capabilities of translators (when required) are concerned, the guidance is:

* for meetings where final decisions on draft standards are expected to be taken, the services of an adequately qualified interpreter are generally required;
* meetings where "intermediary" or procedural decisions are expected to be taken, brief interpretation may be provided by a member of the secretariat or a volunteer delegate;
* at working group meetings, the members should, whenever possible, arrange between themselves for any necessary interpretation on the initiative and under the authority of the convenor of the working group.


[[_idTextAnchor480]]
=== Welcoming activities and social events

ISO is widely recognized and respected. It is therefore not unusual for formal ceremonies to be associated with, for example, the opening of a technical committee meeting. Such events are acceptable, but their incorporation within the meeting period is entirely at the option of the host, and typically subject to the approval of the secretary and chair of the group/s concerned.

A host may also offer social events of one kind or another, perhaps with the aid of co-sponsors. As for welcoming events, social events are entirely optional (see also <<_idTextAnchor481>>).

It is recognized that the inclusion of welcoming and social events significantly increases the time and cost, etc. of organizing a meeting. It may also increase the cost of participation. Given the pressures on the resources of all participants there is merit in the simplification of meetings. Above all, meetings shall not become "competitive" events so far as hosts are concerned, in the sense that no host shall feel obliged, in any respect, to equal or exceed the welcoming and/or social facilities offered at any previous meeting.


[[_idTextAnchor481]]
=== Fees for delegates at ISO meetings

Accredited delegates shall not be obliged to pay a fee as a condition of their participation in ISO meetings. However, in very exceptional cases (e.g. large and complex meetings), some charging mechanism may be necessary, but such mechanisms shall be approved on a case-by-case basis by the Technical Management Board.

There is no obligation on a host to provide social functions during ISO meetings but if a committee requests a host to organize social functions, the host shall have the right to require that the costs of holding such functions be borne by the delegates participating therein.


[[_idTextAnchor482]]
=== Media participation policy

[[_idTextAnchor483]]
==== General

This clause describes a policy for engaging with the media to raise the effectiveness of communication activities of ISO. It is vital to ensure transparency and openness by proactively and consistently delivering accurate information to the public, and to support the use of proper channels to deliver information to the public as effectively and efficiently as possible.

This policy describes how to raise awareness about ISO activities and ensure transparency. It is important that all involved in ISO activities provide accurate and appropriate information in a spirit of good will and responsibility. The media contributes to the shaping of attitudes and behaviours of the general public. Building good media relations is important for building awareness through accurate information and preventing isolated and unrepresentative views and opinions from misleading the public.

Engagement with the media should be sought through multiple vehicles at multiple organizational levels.

All engagement with the media relating to ISO activities will be consistent with the following:

* Interest by the press or other media in ISO work is to be welcomed and the ISO Central Secretariat and many ISO member bodies have public relations and promotion services able to provide information to the press concerning ISO, ISO standards, and work in progress.

* In recent years, there has been a growing interest on the part of some of the press to be present during meetings of particular ISO committees. Whilst this interest is welcome, the presence of the press during an ISO meeting may inhibit the free and open discussion of issues. For this reason, members of the press shall not be permitted to be present during working sessions of ISO meetings. However participation by members of the press may be permitted during opening and closing ceremonies of ISO plenary meetings.


[[_idTextAnchor484]]
==== ISO Central Secretariat roles

Within ISO, the ISO Central Secretariat prepares and releases any and all official press releases. The ISO Central Secretariat reserves the right of final decision on any ISO press release.


[[_idTextAnchor485]]
==== ISO committee and working group leadership roles

Leaders shall only express the consensus reached by the delegates/experts at press conferences held in conjunction with the ISO committee meetings. Between meetings, the secretariat will endeavour to provide prompt written responses to media requests.


[[_idTextAnchor486]]
==== Member body and mirror committee roles

At a local or national level, mirror committees are the proper channel for media inquiries. Mirror committees are encouraged to arrange meetings with local media. This will improve local participation and awareness. At the national level, the relevant member body's media policy should apply.


[[_idTextAnchor487]]
==== Delegate, expert and observer roles

These parties shall not comment to the media on the consensus achieved in the ISO committee, nor shall they comment on the contributions and comments made by other delegates and experts in the working sessions of the ISO committee. This could have a detrimental effect on the productive dialogue and trust necessary among delegates and experts for effective ISO standards development.


[[_idTextAnchor488]]
==== Meetings and media participation

Media representatives present at the site of a meeting shall register with the ISO committee secretariat and the meeting host (name, organization, and contact number).

Media representatives will be given a media badge to wear or keep handy when present at the meeting site.

Registered media representatives with badges are allowed to attend the following events:

* Opening and closing ceremonies;
* Press conferences;
* Social events if invited by the host organization.

People from the media are not allowed to attend:

* Technical committee or subcommittee plenary meetings;
* Working group meetings;
* Chair's Advisory Group (CAG) meetings.

Press conferences may be scheduled for appropriate times (pre- and/or post-plenary) in a designated location by the ISO committee leadership in consultation with the public relations service of the host ISO member body. At the press conferences, the ISO committee leaders and ISO Central Secretariat representatives will make statements to the press. Delegates or experts may be invited to speak by the ISO committee leaders. Otherwise, delegates, experts and observers may attend, but are not permitted to speak at the press conferences.


[[_idTextAnchor489]]
=== Recordings at ISO meetings

The recording of ISO meetings by the committee secretary is acceptable provided that at the outset of the meeting all participants are made aware that the meeting will be recorded and there are no objections. Individual participants shall have the right to require that the means of recording are switched off during a particular intervention if s/he so desires.

Such recordings are intended to aid the meeting secretary in preparing the minutes/report of the meeting. They may also be used to resolve disputes concerning what occurred at a meeting, which, in some instances, may require the preparation of transcripts of the recording.

The recordings and any transcripts are the property of the meeting secretary, who is expected to respect the confidentiality of ISO meetings. The recordings and transcripts shall accordingly not be divulged to third parties and should preferably be destroyed once the minutes have been approved.
