
[[_idTextAnchor490]]
[appendix]
== Second (and subsequent) language texts for ISO standards

[[_idTextAnchor491]]
=== Introduction

<<_idTextAnchor381>> of the _ISO/IEC Directives, Part 1_, specifies the general policy on the use of languages as applied in ISO. This annex describes additional requirements concerning obtaining second and subsequent language texts. (English, French and Russian are the official ISO languages.)


[[_idTextAnchor492]]
=== English, French, Russian and other languages

[[_idTextAnchor493]]
==== Responsibilities

It is the responsibility of the ISO committee secretariat to obtain (but not necessarily themselves prepare) texts in English in general. Translation of documents into French is typically (but not exclusively) carried out by the translation department of the member body of France (AFNOR), or by agents nominated to act on their behalf.

It is the responsibility of the Russian member body to determine those cases for which a Russian version is required, and to provide all translation into Russian.

When a non-official language has been approved by the committee for inclusion in the final deliverable (this is permitted only in the case of a vocabulary), the National Body supporting the related non-official language is responsible for the text, and its timely delivery (i.e. at the latest before the FDIS ballot).


[[_idTextAnchor494]]
==== Equivalence of texts

The National Body supporting a language is responsible for ensuring the equivalence of the related language version to the official language text during the development of an ISO deliverable, if necessary with the assistance of other experts. A recommended way of ensuring equivalence of texts is to establish a multilingual editing committee.


[[_idTextAnchor495]]
==== Timing of preparation of texts

The ISO/IEC Directives note that it is beneficial to start preparation of language versions as early as possible in the development cycle. It is preferable, but not required, that Committee Drafts are available in all envisaged language versions. Apart from aiding comprehension during development, this also serves to help avoid preparation-related delays at later stages.

Where a second or subsequent official language version is required, the ISO Central Secretariat will provide the member body responsible for the second or subsequent language with a copy of the first language version, English in general, when the text is submitted to ISO Central Secretariat for processing as a DIS.


[[_idTextAnchor496]]
==== Timely delivery of language versions

In the case where a second or subsequent official language version is required, the National Body supporting the related language shall provide the ISO Central Secretariat with the related language version within 8 weeks of the submission of the first language version, English in general.


[[_idTextAnchor497]]
==== Updating language versions after ballot

In the case of preparation of a second or subsequent DIS, or the FDIS text, in order to facilitate the preparation of the second or subsequent official language text (where required), TC and SC secretariats should preferably provide the ISO Central Secretariat with a marked-up copy of the revised first-language DIS showing the changes to be made, for use by the member body responsible for the second or subsequent language version.


[[_idTextAnchor498]]
=== Other non-official languages

Languages other than the official languages of ISO may only be included in the body of vocabularies. This is dependent on the committee approving the business case presented by a National Body, which is then responsible for the related language version.

In those cases where an ISO project is a joint project with CEN under the Agreement on technical cooperation between ISO and CEN (Vienna Agreement), the preparation of a German version is a requirement. For more guidance reference should be made to the separate https://isotc.iso.org/livelink/livelink/fetch/2000/2122/4230450/4230458/02__Guidelines_for_the_implementation_of_the_Agreement_on_Technical_Cooperation_between_ISO_and_CEN_%28the_Vienna_Agreement%29_6th_ed._Jan_2014.pdf?nodeid=4230689&vernum=-2[Guidelines for Chairmen and Secretariats on the implementation of the Vienna Agreement]. In all cases of multilingual documents, the cover page, copyright and foreword pages of the document will only mention the official ISO languages and, only in case of a joint project with CEN under the Vienna Agreement, German might be added.


[[_idTextAnchor499]]
=== Single-language versions

It may be proposed that an international document need only be developed in a single official language. Further official language versions can always be prepared as a translation of the published text.


[[_idTextAnchor500]]
=== Translations

Under the terms of the ISO Statutes, as supplemented by the agreement ISO policies and procedures for copyright, copyright exploitation rights and sales of ISO publications (ISO POCOSA), the member bodies of ISO may, under their sole responsibility, prepare translations into other languages of certain ISO publications and documents.
