
[[_idTextAnchor510]]
[appendix]
== Procedure for the development of International Workshop Agreements (IWA)

[[_idTextAnchor511]]
=== Proposals to develop IWAs

A proposal to hold an ISO workshop for the purpose of developing one or more IWAs on a particular subject may come from any source, including ISO member bodies, liaison organizations, corporate bodies etc. An organization that is not an ISO member body or liaison organization, or is not international in scope, shall inform the ISO member body in its country of its intent to submit such a proposal.

Whenever practicable, proposers shall provide details concerning:

* Purpose and justification of the proposal;
* Relevant documents; and
* Cooperation and liaison,

in accordance with the ISO/IEC Directives, Part 1, <<_idTextAnchor326>>.

Additionally, wherever possible, proposals shall include indication of an ISO Member Body willing to provide secretariat support to the IWA Workshop. If it is considered likely that participation in the workshop will need to be limited (see SJ.5.2), this shall also be indicated.

In some circumstances, it may be considered that several meetings may be needed in order to reach a consensus. In such cases, the proposer is encouraged, or may be required by the ISO Technical Management Board, to develop a business plan which would give details concerning meeting schedules, expected dates of availability of draft documents, the possibility that a workshop may establish project teams to progress work between meetings of the workshop, the expected date of availability of any IWA, etc.


[[_idTextAnchor512]]
=== Review of proposals

Proposals will be referred to the ISO Technical Management Board for approval. Proposals should contain an analysis of the global interest in the subject being proposed for the IWA in different countries and by stakeholders.

If the proposal is accepted, the ISO/TMB will initiate consultations with member bodies to identify a candidate willing to act as the organizer and to provide administrative and logistics support to the proposer. Preference will normally be given to:

* The member body from the country of the proposer, if the proposer is not a member body; or
* Member bodies holding secretariats in fields related to that covered by the proposal.

If there is more than one offer, the ISO/TMB will formally designate the member body assigned to act as the workshop secretariat. The assigned ISO member body may establish financial arrangements with the proposer to cover administrative and logistics support costs for the workshop. If a member body is not willing to act as workshop secretariat, the ISO/TMB may authorize the ISO Central Secretariat to fulfil this role, provided all associated costs are recovered by workshop registration fees.

An informative checklist for estimating IWA workshop costs is provided in <<_idTextAnchor523>>.

The workshop secretariat and the proposer shall designate the chair of the workshop.


[[_idTextAnchor513]]
=== Announcement

Once the workshop secretariat and the proposer have agreed on a date and venue for the first meeting of the workshop, these shall be communicated to the ISO member bodies. These details shall be further announced by the workshop secretariat, the ISO Central Secretariat and by any other interested member bodies in the most appropriate way(s) to achieve the widest possible circulation (e.g. a publicly accessible website). This may include a number of different announcement options and media, but the intent is to ensure that the broadest range of relevant interested parties worldwide are informed of the workshop and have the opportunity to attend.

The proposer and workshop secretariat will ensure that any ISO committees with projects relevant to the subject will be invited to be represented at the workshop.

A registration fee may be applied to help support preparation and hosting of the workshop. Any registration fees shall be stated in the workshop announcement.

NOTE: When the subject matter of a workshop is likely to be of interest to developing countries, it is recommended either that a funding mechanism other than a registration fee be applied to facilitate participation from such countries, or that a number of "free" registrations be permitted.

The announcement shall be made at least 90 days in advance of the agreed date to allow potential attendees adequate time to plan on attending the workshop. The announcement shall be accompanied by a registration form to allow potential participants to register for the workshop. Registration forms shall be returned to the workshop Secretariat.


[[_idTextAnchor514]]
=== Workshop information

A workshop programme detailing workshop objectives, deliverables, agenda, draft documents and any other relevant details for the workshop shall be available, and circulated to registered participants, no later than six weeks prior to the workshop date. Registered participants may submit their own contributions to the workshop secretariat for further distribution to other participants.


[[_idTextAnchor515]]
=== Participation

[[_idTextAnchor516]]
==== Workshop chairs

The proposer and workshop secretary shall designate the chair of any particular workshop. The chair shall act in a purely international and neutral capacity and in particular shall

* Ensure that all points of view expressed during a workshop are adequately summed up so that they are understood by all present,
* Conduct the workshop with a view to reaching consensus,
* Ensure that all decisions are clearly formulated and, if needed, made available to the participants before closure of the meeting of the workshop.


[[_idTextAnchor517]]
==== Registered participants

Any organization may register as a participant in a workshop and participation will be open to the registered participants only. Participants are not required to be appointed by the ISO member body in their country. The workshop secretariat, chair and proposer shall endeavour to ensure that the broadest range of interests is represented in any workshop and that there is an appropriate balance of representation. If needed, this may require that some limitation be placed on participation (for example no more than two registered participants from the same corporate body or organization). If the need to limit participation is expected at the outset, this shall be indicated in the proposal submitted to the ISO Technical Management Board. If a need for limitation becomes apparent after announcement of the workshop, this shall be authorized by the TMB secretariat following consultation with the ISO/TMB chair and, if needed, other ISO/TMB members.

Workshop secretariats are responsible for ensuring that the outcome of the workshop is truly international, i.e. it is attended by more than one country.


[[_idTextAnchor518]]
==== Project teams

In cases in which more than one meeting will be required to reach consensus, a workshop may establish one or more project teams to progress work between meetings of the workshop. The workshop shall designate the membership of such project teams, ensuring that their working methods will allow all interests to participate fully.


[[_idTextAnchor519]]
=== Workshop procedures and management oversight

Workshops will be permitted to work in a practically autonomous manner using very flexible procedures.

However, there are a number of general ISO policies which need to be respected, in particular those concerning intellectual property rights and the use of SI units. It shall be the responsibility of the workshop secretariat to ensure that the appropriate policies are known to registered participants and are respected.

Management oversight will be kept to the minimum required to ensure coordination with existing standardization activities if relevant and to ensure that appropriate resource is provided by the ISO system. It will be the responsibility of the workshop chair to determine when consensus of the workshop participants has been reached on a particular item or deliverable. For the purposes of determining consensus, the workshop chair shall apply the definition of consensus in <<_idTextAnchor167>>.

It should be noted that an IWA workshop may arrive at the consensus that an IWA deliverable is not necessary.

The workshop deliverables shall contain a description of the workshop consensus achieved including any recommendations for possible future actions or revisions to the workshop deliverables. The deliverable resulting from the workshop will proceed to publication based on the consensus of the workshop without additional reviews or approvals by any other body, except in the case of an appeal on such a deliverable (see immediately below).


[[_idTextAnchor520]]
=== Appeals

Any parties affected by the deliverable resulting from the workshop shall have the right of appeal for the following reasons:

* The workshop and the process to arrive at its deliverable have not complied with these procedures;
* The deliverable resulting from the workshop is not in the best interests of international trade and commerce, or such public factors as safety, health or the environment; or
* The contents of the deliverable resulting from the workshop conflict with existing or draft ISO standard(s) or may be detrimental to the reputation of ISO.

Such appeals shall be submitted within two months of the date of the workshop and shall be considered by the ISO Technical Management Board which in such circumstances will take the final decision concerning publication of an IWA.


[[_idTextAnchor521]]
=== Workshop deliverables and publication

Workshops will decide on the content of their own deliverables. Deliverables shall be sent to the ISO Central Secretariat for publication as International Workshop Agreements. They will be numbered in a special IWA series. Each IWA shall include the list of participants in the workshop that developed it.

IWAs may be published in one of the official ISO languages only and competing IWAs on the same subject are permitted. The technical content of an IWA may compete with the technical content of an existing ISO or IEC standard, or the proposed content of an ISO or IEC standard under development, but conflict is not normally permitted unless expressly authorized by the ISO/TMB.


[[_idTextAnchor522]]
=== Review of IWAs

If there is an existing ISO committee whose scope covers the topic, the published IWA shall automatically be allocated to this committee for maintenance.

An IWA shall be reviewed three years after its publication. This review shall be organized by the member body which provided the workshop secretariat, or the committee which has been allocated the responsibility for the maintenance of the IWA. The review shall include the consultation of interested market players. The result of the review may be to confirm the IWA for a further three year period, to withdraw the IWA or to submit it for further processing as another ISO deliverable in accordance with Part 1 of the ISO/IEC Directives.

An IWA may be further processed to become a Publicly Available Specification, a Technical Specification or an International Standard, according to the market requirement.

An IWA may exist for a maximum of six years following which it shall either be withdrawn or be converted into another ISO deliverable.


[[_idTextAnchor523]]
=== Checklist to estimate costs associated with hosting an ISO IWA Workshop (WS)

Completion of this checklist is NOT mandatory for the proposed hosting of an IWA. It is intended simply as a tool to assist proposers and assigned ISO member bodies in determining major costs associated with hosting an ISO IWA Workshop. Some of the sample costs provided may not be applicable to particular IWA Workshops, or may be covered in a different manner than is described below.


[[_idTextAnchor524]]
==== Overall measures to consider

[cols="2*",options="unnumbered"]
|===
| Expected number of deliverables |
| Expected number of Project Groups |
| Expected number of participants |
| Expected number of WS plenary meetings |
| Expected number of Project Group meetings |
|===


[[_idTextAnchor525]]
==== Planned Resources -- Human Resource Requirements & Functions

[cols="5*",options="header,unnumbered"]
|===
| Function | Who | Estimated Cost a| Covered by … (Who) | Commitment (Y/N)

a| *WS Secretariat*

* organizing WS plenary meetings
* producing WS and project meeting reports and action lists
* administrative contact point for WS projects
* managing WS (and project group) membership lists
* managing WS (and project group) document registers
* follow-up of action lists
* if the Workshop works mainly by electronic means, assist Chair in monitoring and follow-up of electronic discussion
| | | |

a| *WS Chair*

* chairing WS plenary meetings
* responsible for overall WS/project management
* producing project management progress reports
* acting as formal liaison with related WS/projects and liaison body
* if the Workshop works mainly by electronic means, follow and steer electronic discussions that take place between meetings, take necessary decisions
| | | |

a| *WS Vice-Chair* +
If your WS will have "Vice-Chair(s)", you should list them here, along with their particular functions and fill-in the right side of this table
| | | |

a| *Project Leader(s)* +
(where applicable)

* chairing project group meetings
* producing project group meeting
* reports and action lists
* preparing project group progress reports
* if the Workshop works mainly by
* electronic means, follow and steer
* electronic discussions that take place
* regarding his/her particular project
| | | |

a| *IWA Editor*

* editing of the IWA texts
* attend meetings
* follow discussions relating to the IWA (s) that s/he is editing
| | | |
|===


[[_idTextAnchor526]]
==== Planned Resources -- Material Resource Requirements

[cols="5*",options="header,unnumbered"]
|===
| Material Resource costs | Numbers a| Estimated Cost per meeting a| Covered by … (Who) a| Commitment (Y/N)

| WS Meetings | | | |
| Meeting rooms | | | |
| Logistics (IT support, photocopies, etc.) | | | |
| Food and beverage | | | |
| Interpretation during meetings | | | |
|===
