

[[_idTextAnchor598]]
[appendix]
== Global relevance of ISO technical work and publications

[[_idTextAnchor599]]
=== Introduction

The formation of the WTO and the subsequent adoption of the WTO Technical Barriers to Trade Agreement (WTO/TBT), placed an obligation on ISO to ensure that the International Standards it develops, adopts and publishes are globally relevant. In Annex 4, paragraph 10 of the Second Triennial Review of the Agreement, the following criteria state that a globally relevant standard should:

* Effectively respond to regulatory and market needs (in the global marketplace)
* Respond to scientific and technical developments in various countries
* Not distort the market
* Have no adverse effects on fair competition
* Not stifle innovation and technological development
* Not give preference to characteristics or requirements of specific countries or regions when different needs or interests exist in other countries or regions
* Be performance based as opposed to design prescriptive

Hence the development and adoption of an International Standard that fails to meet these requirements is open to being challenged as creating a barrier to free trade.

Noting the need to provide fuller advice to committees on global relevance, and following a request from the ISO Council, the ISO/TMB established a Global Relevance Task Force. This task force and, subsequently, the ISO/TMB have agreed on the set of principles that follows.


[[_idTextAnchor600]]
=== Terms and definitions

Standard:: Document, established by consensus and approved by a recognized body, that provides, for common and repeated use, rules, guidelines or characteristics for activities or their results, aimed at the achievement of the optimum degree of order in a given context.
+
--
NOTE: Standards should be based on the consolidated results of science, technology and experience, and aimed at the promotion of optimum community benefits.

(ISO/IEC Guide 2, ISO/IEC Directives, Part 2)
--

international standard:: Standard that is adopted by an international standardizing/standards organization and made available to the public.
+
--
(ISO/IEC Guide 2, ISO/IEC Directives, Part 2)
--

International Standard:: International standard where the international standards organization is ISO or IEC.
+
--
(ISO/IEC Directives, Part 2)
--

Global relevance:: Required characteristic of an International Standard that it can be used/implemented as broadly as possible by affected industries and other stakeholders in markets around the world.


[[_idTextAnchor601]]
=== Principles

==== The status and meaning of an International Standard shall be respected.

Any International Standard shall respect the above definitions and shall to the extent possible represent a unique international solution. In cases where unique international solutions are not possible for specific provisions of an International Standard at the current time due to legitimate market and essential differences, International Standards may present options to accommodate these differences where justified.


==== The commitment to participate in the development of and the feasibility of preparing International Standards shall be demonstrated at the outset of a standards development project.

It is recognized that in some instances various solutions exist to meet unique aspects of the local markets in different regions and countries. With globalization and the unification of markets, these market differences should be minimized over time and evolve into one global market. Simply projecting one solution that accommodates one market (but not others) as the International Standard will not force markets to evolve and coalesce. In such cases, the markets and their related industries will look elsewhere for standards that better accommodate their needs, and ISO will lose its relevance for those markets and industries. Rather than force such a situation, ISO committees should ascertain at the outset of a project whether:

* a globally relevant International Standard presenting one unique international solution in all of its provisions is feasible;
* an International Standard is feasible that presents options in specific provisions to accommodate existing and legitimate market differences where justified; or
* the preparation of a globally relevant International Standard is not feasible and work should not be undertaken in such circumstances.

Additional practical guidance for committee leaders and delegates/experts may be found in the ISO/TMB's Global Relevance Implementation Guidance document.


==== Preference shall be given to preparing performance rather than prescriptive standards.

Please note the following: Annex 3 of the WTO/TBT Agreement.

"Wherever appropriate, the standardizing body shall specify standards based on product requirements in terms of performance rather than design or descriptive characteristics."

ISO/IEC Directives, Part 2, clause 5.4 Performance principle (Excerpt) "Whenever possible, requirements shall be expressed in terms of performance rather than design or descriptive characteristics. This principle allows maximum freedom for technical development and reduces the risk of undesirable market impacts (e.g. restriction of innovative solutions)."

Given these quotations, the use of the performance-based approach is widely recognized as supporting the development of globally relevant ISO standards. In the case of design-based standards, the freedom for further technical innovation is most limited, while performance-based standards provide for maximum freedom for further innovation. However, in practice, there may be cases where inclusion of design requirements for some provisions within a performance-based standard is appropriate. There may also be other cases where development of a completely design-based standard may be appropriate and will result in a globally relevant ISO standard.

Thus, which approach is most appropriate depends on the technical matter in question.

Additional practical guidance for committee leaders and delegates/experts may be found in the ISO/TMB's Global Relevance Implementation Guidance document.


==== Given existing and legitimate market differences, an International Standard may pass through an evolutionary process, with the ultimate objective being to publish, at a later point, an International Standard that presents one unique international solution in all of its provisions.

Under this principle, a committee may wish to consider how it addresses current and potentially changeable differences in markets (based on factors such as legislation, economies, social conditions, trade patterns, market needs, scientific theories, design philosophies, etc.) in the ISO deliverables it produces.

Additional practical guidance for committee leaders and delegates/experts may be found in the ISO/TMB's Global Relevance Implementation Guidance document.


==== Essential differences consistent with Annex 3 to the WTO Agreement on Technical Barriers to Trade can be included in International Standards, but specific rules shall be applied if a committee wishes to introduce such differences and special authorization needs to be given by the ISO/TMB in instances not covered by these rules.

Under this principle, a committee may wish to consider how it addresses essential differences in markets around the world, that is, factors that are not expected to change over time, such as imbedded technological infrastructures, climatic, geographical or anthropological differences.

Additional practical guidance for committee leaders and delegates/experts may be found in the ISO/TMB's Global Relevance Implementation Guidance document.


==== Committees can only ensure the global relevance of the International Standards they produce if they are aware of all the factors that may affect a particular standard's global relevance.

Additional practical guidance for committee leaders and delegates/experts may be found in the ISO/TMB's Global Relevance Implementation Guidance document.
