

[[_idTextAnchor602]]
[appendix]
== Registration Authority ("RA") Policy

[[_idTextAnchor603]]
=== Scope

A number of International Standards developed by ISO technical committees require the assignment of unique Registration Elements and describe the methodology for the assignment of these Elements. The Registration Elements themselves are not part of the standard but are assigned by an appointed RA, who also maintains an accurate register of the Registration Elements that have been assigned. The RA is a competent body with the requisite infrastructure that ensures the effective allocation of these Registration Elements and any other RA responsibilities that are described in the RA Standard. These bodies are designated by ISO to serve as the sole RA for particular standards, which creates a de facto monopoly situation.

This Policy is mandatory and must be read in conjunction with <<_idTextAnchor415>> of Part 1 of the ISO/IEC Directives.


[[_idTextAnchor604]]
=== Compliance

Where ISO/CS becomes aware of an RA Standard under development or under revision that has not followed this Policy, it shall stop the publication process to allow time to implement this Policy before the RA Standard is published. For this reason, committees are encouraged to make the ISO Technical Program Manager (TPM) aware of a project requiring an RA as early in the development process as possible to avoid delays in publication.


[[_idTextAnchor605]]
=== Definitions

==== {blank}

RA Standard:: A standard for which an RA is providing the Registration Services.


==== {blank}

Registration Services or RA Services:: Services provided by the RA in the implementation of the RA Standard and which shall be described in the RA Standard.


==== {blank}

Registration Authority ("RA"):: Entity appointed by ISO to fulfill the Registration Services in an RA Standard.


==== {blank}

Registration Agencies:: Third parties (e.g. national or regional sub-entities) to which the RA may delegate some aspects of the Registration Services. Even when delegated to Registration Agencies, the Registration Services remain under the overall responsibility of the RA.


==== {blank}

Registration Authority Agreement ("RAA"):: Agreement based on the RAA template signed by the RA and the ISO Secretary-General on behalf of ISO, which details the functions, roles and legal obligations of the parties involved.


==== {blank}

Registration Elements:: Unique identifiers or identifier code components, the methodology for which is described in the RA Standard but which themselves are not part of the RA Standard.

==== {blank}

Technical Programme Managers (TPM):: Individual within ISO/CS assigned to work with a given committee.


[[_idTextAnchor606]]
=== Procedure

[[_idTextAnchor607]]
==== Chronology

This Policy addresses the various aspects of an RA in the order of the life cycle of a typical RA noting that some stages may be done in parallel. Each stage is addressed as follows:

* Declaring the need for an RA (<<_idTextAnchor608>>)
* Drafting an RA Standard (<<_idTextAnchor609>>)
* Selecting an RA (<<_idTextAnchor610>>)
* Appointing an RA (<<_idTextAnchor611>>)
* Signing an RAA (<<_idTextAnchor612>>)
* Implementing an RA Standard (<<_idTextAnchor613>>)
* Role of the RA (<<_idTextAnchor614>>)
* Role of the Committee (<<_idTextAnchor615>>)
* Role of the ISO Central Secretariat (<<_idTextAnchor616>>)
* Terminating an RA (<<_idTextAnchor617>>)


[[_idTextAnchor608]]
==== Declaring the need for an RA

A committee shall determine that an RA is required for a standard as soon as the draft is sufficiently mature to make this decision, whether this is during the creation of a new standard or the revision of an existing standard involving material changes to its implementation. The committee confirms its decision that a standard needs an RA for its implementation by way of a resolution.

The committee secretariat completes the RA Confirmation ("RAC") Form (See Annex SJ) and submits it to the TPM as soon as the resolution is approved.


[[_idTextAnchor609]]
==== Drafting an RA Standard

The following shall be included in all RA Standards:

* A description of the identification scheme or the mechanism for generating unique Registration Elements.
* A description of the Registration Services, and the responsibilities of the RA.
* The link to the page on iso.org where ISO publishes the name and contact information of the RA for a given RA Standard. The page on iso.org shall provide a link to the RA's website which will contain more information on the Registration Services available.

The following *shall not be* included in RA Standards:

* In accordance with clause 4 of the ISO/IEC Directives, Part 2, contractual or other legal aspects.
* Procedures concerning the provision of the Registration Services (e.g. a Handbook made available by the RA).
* The name of the RA. Instead, a link to the ISO website shall be provided (see above).
* References to the selection or reappointment process for the RA.
* Details about any Registration Agencies. In case of delegation of Registration Services by the RA to third parties (e.g. Registration Agencies) as agreed under the RAA, the RA Standard may mention the fact that some aspects of the Registration Services have been delegated.

The TPM is responsible for coordinating with the committee to ensure that the appropriate text is included in the RA Standard. Any questions about what should be included in the RA Standard are to be addressed to the TPM.


[[_idTextAnchor610]]
==== Selecting an RA

The selection process of the RA applies to new RA Standards and existing RA Standards.

In the case of revisions, the committee shall review and decide whether the existing RA should continue or if a selection process should be launched to select additional RA candidates. In their review, the committee shall consider the changes being made to the RA Standard, particularly with regard to the responsibilities of the RA, and the goal of optimizing the implementation of the RA Standards. The decision to launch a selection process should be supported by a rationale. The committee shall confirm its decision by resolution.

The committee shall establish a process so that an RA can be appointed or re-appointed before publication of the RA Standard. It is important that each draft of the RA Standard contains details about the nature of the Registration Services needed and that these are shared with any current or prospective RA candidates.

The committee establishes the criteria for the application process and selection of the RA and confirms these by resolution. The minimum criteria for the selection process shall be:

* *Selection criteria* -- these must be clearly explained and with sufficient details for possible RA candidates to assess their ability to meet the criteria and apply on this basis. Included in the selection criteria shall be the requirement that the prospective RA candidates provide the following information in writing:
** Proof (e.g. Statutes) that it is a legal entity which means that is an organization formed under the laws of a jurisdiction and that it is therefore subject to governance related rules.
** Expression of willingness to take responsibility for the Registration Services.
** Confirmation that the RA is technically and financially able to carry out the RA Services described in the RA Standard and the RAA on an international level, including for example, a financial plan for funding the expected volume of registrations, a list of employees or third parties and their applicable background and skills, and description of the physical facilities available to the RA to accomplish the work, demonstrated financial capacity to meet liability exposure for performing the services.
** Documentation and examples, where relevant, of the candidate RA's experience in the respective community of practice.
** Confirmation of whether it intends to delegate part of the Registration Services to Registration Agencies.
** Confirmation of whether it will charge fees for the RA Services and, if it charges fees, confirmation that any such fees will be on a cost recovery basis.
** Expression of willingness to sign and execute an RAA, the ISO/CS RAA template for which shall be shared with RA candidates.
* *Public call for RA candidates* -- committees shall take the appropriate steps needed to post the call for competent RA applicants to as broad a market as possible, also targeting possible organizations by inviting them to apply. The relative weighting of each evaluation criterion shall be published in the public call. Details of the Registration Services shall be made available to any current RA and any prospective RA candidates.
* *Evaluation* -- Prospective RA candidates shall provide their responses in writing. The committee (or a subset thereof) shall determine the relative weight to be given to each selection criterion and shall evaluate the prospective RA candidates accordingly.
* *Record-keeping* -- the committee secretariat shall keep records of all documents in the selection process, including the call for candidates, applications, evaluation, decision, etc.
* *Professionalism* -- the selection process should be conducted in a professional manner, adhering to the principle of discretion amongst those involved.

The committee shall then confirm to the TMB its recommendation for appointment of the organization selected to be the RA via a resolution.


[[_idTextAnchor611]]
==== Appointing an RA

The information that is provided by the committee in the RAC (see <<_idTextAnchor608>> above) is needed to launch the TMB ballot appointing the RA, as well as the ISO Council ballot if the RA intends to charge fees. The ISO/IEC Directives state that RA may charge fees for the Registration Services subject to authorization by the ISO Council, and as long as the basis of charging fees is strictly on a cost recovery basis. In the case of revisions, approval from the TMB or ISO Council is not needed if the committee decides that the same RA should continue (see <<_idTextAnchor610>>) and the required authorization to charge fees has already been given.

In the case of JTC 1 RA Standards, a copy of the RAC Form shall also be provided to the IEC since RA appointments must all be confirmed by the IEC/SMB (and Council Board) where fees are charged.


[[_idTextAnchor612]]
==== Signing an RAA

A signed RAA must have been executed using the latest RAA template before an RA Standard is published (including revisions). In the case of revisions, the process to sign the RAA should begin at the time of the launch of the systematic review or the committee decision to launch a revision to ensure the timely signature of the RAA and to avoid delays in publication.

Only after the TMB (and Council if fees are charged) has appointed the RA (and in the case of JTC 1 RA Standards, involving the IEC) can the RAA be signed. Signing an RAA based on the ISO/CS template is mandatory for all RAs. The RAA shall be signed before publication of a new or revised RA Standard. If an RAA is not signed, the new or revised RA Standard shall not be published.

To ensure consistency and equality of treatment between the different RAs, any requested deviations from the RAA template which ISO/CS considers to be significant in nature shall be submitted to the TMB for approval.


[[_idTextAnchor613]]
==== Implementing an RA Standard

[[_idTextAnchor614]]
===== Role of the RA

The RA provides the Registration Services by:

* providing the Registration Services described in the RA Standard, and
* respecting the provisions of the RAA.


[[_idTextAnchor615]]
===== Role of the committee

Although RAAs are signed by the RA and by the ISO Central Secretariat, the signature of a RAA by the Central Secretariat binds all components in the ISO system, including ISO members and ISO committees. The central role is played by committees. In addition to declaring the need for an RA Standard (4.2), drafting the RA Standard (4.3) and selecting an RA (4.4) for both new and revised RA Standards, the committee has the main responsibility for oversight of the RA as follows:

* Answering questions: The committee must be available to the RA to answer questions about the RA Standard and clarify any expectations regarding its role in implementing the RA Standard.
* Assessing RA's annual reports: The RAA requires the RA to provide the committee with annual reports by the date specified by the committee. The committee shall ensure that these annual reports are provided on time and read them.

The RA's annual report is to be divided in two parts:

The first part addresses the operational aspects of the RA as directly related to the RA Services. The committee or ISO (or the IEC for JTC 1 standards) may request information about the activities of the RA that are not related to the RA Services if there is reason to believe that these are interfering with the RA Services. At a minimum this first part of the RA report shall confirm:

* That the RA is fulfilling the RA Services described in the RA Standard.
* Compliance with the signed RAA by the Registration Agencies designated by the RA.
* That the RA is meeting user needs and providing users with guidance, as needed.

The second part of the RA report provides information about any complaints received from users of the RA Standard regarding, for example: fees, access to and use of data and/or information produced during the implementation of the RA Standard, as well as accuracy of the data and/or information. This part shall indicate whether of the complaints remain outstanding at the time of the RA report and the efforts underway to resolve them.

* *Monitoring*: In addition to the annual RA report, the committee shall also analyse any feedback it receives from industry and users of the RA Standard. Based on all of these elements (RA report and other feedback), the committee shall report to ISO/CS (see below).

* *Reporting to ISO/CS*: At least once per year and based on the information collected under Monitoring above, the committee shall provide a report to the responsible TPM using the Annual Committee Report to TPM ("ACR") Form (See Annex SJ). The purpose of such reports is to confirm that the RA operates in accordance with the RAA or to raise any concerns (concerns can include: RA not meeting industry or user needs, complaints about the quality of the Registration Services, etc.). Such reports shall be provided at least annually to the responsible TPM or more frequently if the committee deems it necessary. The TPM may also ask for ad hoc reports. If the report identifies concerns, it shall include the planned Corrective measures (see below) needed to address these concerns.

* *Dispute resolution*: The obligations of RAs to address complaints are contained in the RAA template. The role of the committee (and ISO/CS) is limited to advising the RA of any complaints it receives about the RA Services and supporting the RA in its addressing of the dispute. The committee shall not assume responsibility for the dispute or become the appellate body for disputes between the RA and users of the RA Standard as this may inadvertently give the impression that ISO is responsible for the Registration Services.

* *Corrective measures*:
** By the RA: the RA is responsible for implementing any corrective measure that are within its area of responsibility, which would include the Registration Services and the provisions described in the RAA.
** By the committee: the committee is responsible for recommending possible corrective measures such as: revising the RA Standard, providing advice and guidance to the RA, carrying out audits or recommending the termination of the RAA to ISO/CS in severe cases.
** By ISO/CS: the corrective measures that fall within the responsibility of ISO/CS (e.g. updating or overseeing the RAA) will be coordinated by the TPM. The TPM may also recommend corrective measures.

* *Maintenance of records*: The committee shall maintain and archive all key communications and documentation (e.g. correspondence between the RA and the committee regarding complaints) until at least five years after either termination of the RAA or withdrawal of the RA Standard. The committee secretariat is responsible for ensuring that these are maintained in a separate folder on e-committees.

The committee may create an advisory subgroup, with the appropriate terms of reference, [often referred to as a Registration Management Group ("RMG")] in order to help them with the above. Committees (either directly or through the RMG) shall not participate or get involved in providing the Registration Services except in the supervisory roles specified in this subclause.


[[_idTextAnchor616]]
===== SN.4.7.3Role of the ISO/CS

The committee's interface with ISO/CS is through the responsible TPM. The role of the TPM includes:

* Identification of RA Standards during the development process if not done by the committee.
* Providing guidance and advice for the drafting of RA Standards.
* Training committees on this RA Policy.
* Coordination with committees to ensure compliance with the RA Policies, quality of RA Services, appropriate handling of complaints, addressing industry and users' needs, including addressing the concerns raised in the annual reports provided by committees (using the ACR Form) and recommending and assisting in the implementation of any corrective measures (see <<_idTextAnchor615>>).
* Maintenance of records in relation to his or her involvement.


[[_idTextAnchor617]]
==== Termination of an RA

Termination of RAs could occur when

. an RAA has expired and the RA or ISO (or the IEC in the case of JTC 1 RA Standards) has given the required notice of its intent not to renew it, or
. the RAA is terminated for cause, or
. the RAA was terminated by mutual consent, or
. the RA Standard is withdrawn, or
. the RAA goes into bankruptcy, liquidation or dissolution.

When an RA has been given notice of non-renewal or termination, the committee should exercise particular oversight to ensure that RA Services are maintained during the notice period and change-over phase.

Unless the RA Standard is withdrawn, the process detailed in <<_idTextAnchor610>> above should be followed in the selection of a replacement RA unless the committee has identified an alternative RA candidate that meets the selection criteria in 4.4 and going through the selection process for additional RA candidates would cause unacceptable disruption in the RA Services.
