
[[_idTextAnchor618]]
[appendix,obligation="informative"]
== Principles for developing ISO and IEC Standards related to or supporting public policy initiatives

[[_idTextAnchor619]]
=== Background Context

The 2007 ISO General Assembly Open Session on International Standards and Public Policy addressed important dynamics confronting the ISO community -- the relationship between ISO standards and public policy as well as the unique needs and concerns of one major class of ISO standards users, namely, governments. ISO's sister organization IEC, responsible for electrotechnical standardization, applauds the initiative and wishes to co-operate with ISO to develop common ISO/IEC principles and guidance to technical committees of both organizations. It is a reasonable goal that ISO and IEC wish to make their portfolio of standards more visible to public authorities and, equally important, ensure that its standards address the relevant needs and concerns of the public authorities. This will support their global relevance and applicability worldwide, as it has been shown that ISO and IEC standards are capable of providing valuable support to the implementation of public policy. ISO and IEC have been and will continue to be effective providers of voluntary standards that support the programs of government authorities, who need standards that meet the WTO TBT criteria and that support technical regulations and/or procurement actions.

It should be noted that, as private, voluntary organizations, ISO and IEC themselves are not directly representative of government interests. ISO and IEC consensus on ISO and IEC standards reflects agreement across a range of stakeholders at the standard drafting level, AND it reflects a consensus across national standards bodies at the approval level. National positions on ISO or IEC standards are not necessarily government positions, although government experts may participate in developing these positions with their counterparts from the private sector.

The following set of principles has been established to guide ISO and IEC committees developing standards related to or supporting public policy initiatives. These principles will ensure that ISO and IEC standards can properly support and be used by public authorities.


[[_idTextAnchor620]]
=== Principles

. ISO and IEC are committed to creating market-driven International Standards, based on objective information and knowledge on which there is global consensus, and not on subjective judgments, in order to provide credible technical tools that can support the implementation of regulation and public policy initiatives.

. ISO and IEC are committed to developing International Standards that are market relevant, meeting the needs and concerns of all relevant stakeholders including public authorities where appropriate, without seeking to establish, drive or motivate public policy, regulations, or social and political agendas.
+
--
When ISO or IEC standards are anticipated to support a public policy initiative, the relationship between the standard(s) and the public policy initiative(s) should be clearly understood among all concerned parties. The interaction of standardization and public policy or regulation should be anticipated and the intervention of the public authorities in the standards development process should occur as early as possible. It should be noted that in many cases experts representing regulatory authorities are actively participating in the development of ISO and IEC International Standards both as members of the relevant international committees and/or at the pertinent national mirror committees to ISO and IEC technical bodies.
--

. ISO and IEC recognize that the development of regulation, public policy and/or the development and interpretation of international treaties are the role of governments or treaty organizations.

. ISO and IEC standards supporting regulation, regulatory cooperation and public policy are best developed within ISO and IEC structures and under operational approaches and participation models that have been proven successful and that are detailed in the ISO/IEC Directives.

The use of special committee structures, procedures or participation models may compromise the credibility and suitability of the resulting ISO/IEC standards supporting regulation and public policy.


[[_idTextAnchor621]]
=== Implementation

* In addition to promoting these principles to ISO and IEC committees, their leaders and participants, ISO and IEC shall actively support and promote the principles for international standardization established in the WTO TBT Agreement and subsequent decisions of the TBT Committee regarding the development of International Standards.

* ISO member bodies and IEC National Committees should ensure that national governments, including their trade representatives, are aware of ISO's and IEC's portfolios, are informed about ISO and IEC as venues for standards development, and are engaged in ISO and IEC standards development whenever appropriate to reduce misunderstanding and inadvertent contradictions.

* The ISO Technical Management Board and the IEC Standardization Management Board should develop additional implementation guidance and case studies of successful ISO and IEC standards efforts that support public policy initiatives (for example, ISO standards related to medical devices and greenhouse gas emissions, and IEC standards related to radio interference, safety of household appliances, ships and marine technology).
