
[[_idTextAnchor622]]
[appendix]
== Policy for the development of sector-specific management standards and sector-specific management system standards (MSS)

[[_idTextAnchor623]]
=== General

Any technical committee or subcommittee, project committee or International Workshop that proposes development of a sector-specific management standard (SP.2.2) or a sector-specific management system standard (MSS) (SP.2.4) shall follow the directions specified in this annex. It includes, as applicable, committee specific policies (<<_idTextAnchor627>>) which may not be limited to sector-specific management standards or sector-specific management system standards.


[[_idTextAnchor624]]
=== Terms and definitions

==== generic management standard
management standard designed to be widely applicable across economic sectors, various types and sizes of organizations and diverse geographical, cultural and social conditions
  
==== sector-specific management standard

management standard that provides additional requirements or guidance for the application of a generic management standard (SP.2.1) to a specific economic or business sector
  

====  generic management system standard
alt:[generic MSS]

MSS designed to be widely applicable across economic sectors, various types and sizes of organizations and diverse geographical, cultural and social conditions


==== sector-specific management system standard (MSS)
atl:[sector-specific MSS]

MSS that provides additional requirements or guidance for the application of a generic MSS (SP.2.3) to a specific economic or business sector


[[_idTextAnchor625]]
=== Sector-specific management standards and sector-specific management system standards

Any new proposal for a sector-specific management standard (SP.2.2) or sector-specific MSS (SP.2.4) shall:

* clearly demonstrate its market relevance and alignment through the completion of appropriate ISO project approval procedures by means of ISO Form 4, New Work Item Proposal,

* [in the case of the development of a sector-specific MSS (SP.2.4)] clearly demonstrate that all the rules and principles in Annex SL have been followed, including the approval of the justification study (see Annex SL), and

* clearly demonstrate that the liaison with the committee responsible for the generic management standard or generic MSS concerned is effective,

* if applicable, conform with the committee specific policies set out below.


[[_idTextAnchor626]]
=== Drafting rules

Sector-specific management standards (SP.2.2) and sector-specific MSS (SP.2.4) shall respect the following rules:

. Normative reference shall be made to the generic management standard (SP.2.1) or generic MSS (SP.2.3). Alternatively, the clauses and subclauses may be reproduced verbatim.

. If text from the generic management standard (SP.2.1) or generic MSS (SP.2.3) is reproduced in the sector-specific standard, it shall be distinguished from the other elements of the sector-specific standard.

. Terms and definitions specified in the generic management standard (SP.2.1) or generic MSS (SP.2.3) shall be referred to in a normative manner or reproduced verbatim.


[[_idTextAnchor627]]
=== Committee specific policies

[[_idTextAnchor628]]
==== General

Sector-specific management standards (SP.2.2) and sector-specific MSS (SP.2.4) shall not interpret, change, or subtract from the requirements of the generic management standard or generic MSS.


[[_idTextAnchor629]]
==== Environment

===== Terms and definitions

The following terms and definitions are applicable to environmental policy:


====== sector-specific environmental management standard

standard that provides additional requirements or guidance for the application of a generic environmental management standard to a specific economic or business sector

[example]
The application of an environmental management system (ISO 14001) or life-cycle assessment (ISO 14044) to agri-food or energy sectors.


====== aspect-specific environmental management standard

standard that provides additional requirements or guidance for the application of a generic environmental management standard for a specific environmental aspect or aspects within its scope

[example]
The application of an environmental management system (ISO 14001) for greenhouse gas (aspect) management or life-cycle assessment (ISO 14044) for the water (aspect) footprint of products.


====== element-specific environmental management standard

standard that provides additional requirements or guidance for the application of a generic environmental management standard for a specific element or elements within its scope

[example]
Communications or emergency management (elements) within an environmental management system (ISO 14001) or data collection or critical review (elements) within a life-cycle assessment (ISO 14044).


===== General

Any technical committee, subcommittee, project committee or International Workshop that proposes development of a sector-, aspect- or element-specific environmental management standard shall clearly demonstrate its market relevance and alignment through the completion of appropriate project approval procedures, including:

* ISO Form 4, _New Work Item Proposal_ for sector-, aspect- or element-specific specific application of generic environmental management system standards, environmental labeling, life-cycle assessment and greenhouse gas management standards, and

* Annex SL _Proposals for management system standards (MSS)_ for sector-, aspect- or element-specific specific application of generic environmental MSS.

Approval documentation should include specific justification as to why the relevant generic ISO 14000 series standard(s) insufficiently address sector-, aspect- or element-specific needs and how the proposed new standard would effectively resolve identified issues. Proposers should critically assess whether additional sector-, aspect- or element-specific requirements are needed as opposed to the provision of additional guidance to the generic environmental management standard(s).


===== {blank}

Any technical committee, subcommittee, project committee or International Workshop that proposes development of a sector-, aspect- or element-specific environmental management standard should consider and reflect the needs of developing countries, economies in transition, small- and medium- enterprises and organizations operating across a variety of sectors.


===== {blank}

ISO/TC 207 will cooperate in or, where appropriate and as decided by the Technical Management Board, lead joint projects with technical committee, subcommittee, project committee or International Workshop developing sector-, aspect- or element-specific environmental management standards to avoid duplication of effort and promote consistency and alignment. There is no intention to restrict the development of market relevant standards in committees outside of ISO/TC 207.


===== {blank}

Technical committee, subcommittee, project committee or International Workshop developing sector-, aspect- or element-specific environmental management standards shall:

* include the normative reference of the appropriate generic ISO 14000 series environmental management systems, environmental auditing, environmental labeling, life-cycle assessment and greenhouse gas management standards;
* include the normative reference of the appropriate generic ISO 14050 terms and definitions;
* distinguish ISO 14000 series text if it is reproduced; and
* not interpret, change, or subtract from the requirements of the generic ISO 14000 series environmental management systems, environmental auditing, environmental labeling, life-cycle assessment and greenhouse gas management standards.


===== {blank}

Any requests for guidance on this sector-, aspect- or element-specific policy or for interpretation of generic ISO 14000 series standards or ISO 14050 terms and definitions or for guidance on a sector-, aspect- or element-specific document shall be submitted to the ISO Central Secretariat as well as the relevant TC 207 subcommittee.


[[_idTextAnchor630]]
==== Quality

When an technical committee, subcommittee, project committee or International Workshop wishes to develop quality management system requirements or guidance for a particular product or industry/economic sector it shall respect the following rules.

. Normative reference shall be made to ISO 9001 in its entirety. Alternatively, the clauses and subclauses may be reproduced verbatim.

. If text from ISO 9001 is reproduced in the sector document, it shall be distinguished from the other elements of the sector document [see <<item_sp-4>>].

. Terms and definitions specified in ISO 9000 shall be referred to in a normative manner or reproduced verbatim.

. [[item_sp-4]]The guidance and criteria provided in Quality management systems -- Guidance and criteria for the development of documents to meet needs of specific product and industry/economic sectors, approved by ISO/TC 176, shall be considered not only when determining the need for a sector-specific requirements or guidance document but also in the document development process.

Any requests for guidance on this sector policy or for interpretation of ISO 9000 terms and definitions, ISO 9001 or ISO 9004 shall be submitted to the secretariat of ISO/TC 176.


[[_idTextAnchor631]]
==== Asset management

When an technical committee, subcommittee, project committee or International Workshop wishes to develop asset management system requirements or guidance for a particular product or industry/economic sector it shall respect the following rules:

. Normative reference shall be made to ISO 55001 in its entirety. Alternatively, the clauses and subclauses may be reproduced verbatim.
. If text from ISO 55001 is reproduced in the sector document, it shall be distinguished from the other elements of the sector document.
. Terms and definitions specified in ISO 55000 shall be referred to in a normative manner or reproduced verbatim.

Any requests for guidance on a sector-specific document or for interpretation of ISO 55000 terms and definitions or ISO 55001 shall be submitted to the secretariat of ISO/TC 251.


[[_idTextAnchor632]]
==== Risk

When a technical committee, subcommittee, project committee or International Workshop wishes to develop risk management requirements or guidance for a particular product or industry/economic sector it shall respect the following rules:

. Reference shall be made to ISO 31000 in its entirety. Alternatively, the clauses and subclauses may be reproduced verbatim.
. If text from ISO 31000 is reproduced in the sector document, it shall be distinguished from the other elements of the sector document.
. Terms and definitions specified in ISO 31000 shall be referred to in a normative manner or reproduced verbatim.

Any requests for guidance on a sector-specific document or for interpretation of ISO 31000 terms and definitions shall be submitted to the secretariat of ISO/TC 262.


[[_idTextAnchor633]]
==== Social responsibility

When a technical committee, subcommittee, project committee or International Workshop wishes to develop social responsibility requirements or guidance for a particular product or industry/economic sector it shall respect the following rules:

. Reference shall be made to ISO 26000 in its entirety. Alternatively, the clauses and subclauses may be reproduced verbatim.
. If text from ISO 26000 is reproduced in the sector document, it shall be distinguished from the other elements of the sector document.
. Terms and definitions specified in ISO 26000 shall be referred to in a normative manner or reproduced verbatim.
