
[[_idTextAnchor634]]
[appendix]
== Selection criteria for people leading the technical work

[[_idTextAnchor635]]
=== Obligations of member bodies

Member bodies are responsible for ensuring that candidates for leadership positions (i.e. chairs, convenors, and secretaries) meet the requirements contained in <<_idTextAnchor637>>. Member bodies are also responsible for ensuring that any gaps in skills or knowledge of the selected leaders, as well as experts, are identified and filled through ongoing training.


[[_idTextAnchor636]]
=== Resources available to fill gaps in skills or knowledge

A number of resources are available to help member bodies fill any identified gaps in skills or knowledge:

* Training and other materials are available from the ISO Central Secretariat to ensure the effectiveness of the various roles in conducting/attending meetings, including understanding key concepts.

* To help train experts, it may be useful to schedule committee pre-sessions and information on existing resources before or in conjunction with committee plenaries.

* The support of the Technical Programme Manager, particularly in the case of new committees, is available to train leaders and experts. In the case of new committees, the Technical Programme Manager should attend the first meeting to provide an overall introduction of ISO and its processes.

* Exchange programmes could also be organized between member bodies or with the ISO Central Secretariat. Member bodies may also wish to consider twinnings.

* The services of an external facilitator for coaching and training could be considered as one of the options to assist the committee leadership to develop non-ISO specific skills, such as the skills needed to run effective meetings, general leadership skills, etc.


[[_idTextAnchor637]]
=== Selection Criteria for people leading the technical work

The success of any committee or working group is dependent on its leadership. This selection criteria applies to committee footnote:[Technical Committees, Subcommittees, Project Committees.] chairs, working group convenors and committee secretaries. Members bodies are therefore required to apply this criteria when nominating people to these roles in order to ensure that the new https://www.iso.org/iso/standards_development/governance_of_technical_work.htm[ISO Code of Conduct for the technical work] is upheld and that the ISO/IEC Directives are correctly applied.


[[_idTextAnchor638]]
==== Chairs and convenors

[[_idTextAnchor639]]
===== Competencies and attributes of good chairs and convenors:

* existing role and good reputation in the sector
* relevant professional experience with previous experience of chairmanship
* lead and inspire delegates and experts from the sector towards consensus
* understand the international nature of ISO's work and its resulting benefits
* commit time and resources to their role
* develop solutions through innovative and creative thinking in a consensus environment
* act proactively and communicate diplomatically
* foster and value cooperation with other ISO and IEC Committees and partners including those from regulatory bodies
* act in a purely international capacity


[[_idTextAnchor640]]
===== Job specification for chairs and convenors:

* lead meetings effectively with a view to reaching agreement and to ensure that positions and decisions are clearly understood
* ensure that all positions and views (at meetings and by correspondence) are given equal treatment
* manage projects according to agreed target dates in accordance with the project plan from preparation to completion
* work to ensure that a full range of technical competence is available to the group
* be fully knowledgeable of the subject and market needs
* propose decisions to progress or to stop work on the basis of its market or global relevance
* have basic knowledge of ISO and its procedures


[[_idTextAnchor641]]
===== Additionally -- chairs of committees are required to:

* take responsibility for the overall management of the committee, including any subcommittees and working groups
* advise the ISO Technical Management Board on important matters relating to the Committee
* ensure that the policy and strategic decisions of the ISO Technical Management Board are implemented by the Committee
* think strategically to promote ISO's work in the sector


[[_idTextAnchor642]]
===== Additionally -- convenors of working groups are required to:

* have appropriate knowledge and capabilities in using MS Word based drafting tools and the ISO web-based applications, including the required use of ISO applications for communications and document sharing, in order to support the working group's work


[[_idTextAnchor643]]
===== Supporting information

The following information should be considered by the member bodies in the nominations for chairs and convenors:

* current role in the sector
* education
* professional career
* leadership experience
* similar activities
* language skills


[[_idTextAnchor644]]
==== Secretaries and secretariats

[[_idTextAnchor645]]
===== Selection of secretaries and secretariats

The success of an ISO committee or working group is dependent on its secretariat and secretary (or convenor of a WG in case there is no secretary). The following list is based on the ISO/IEC Directives and shows the tasks expected to be performed in these roles. ISO Members should use this list when appointing organizations and professionals as secretariats and secretaries.


[[_idTextAnchor646]]
===== Good documents

Preparing drafts for the committee or working group, arranging for their distribution and the treatment of the comments received. In the case of committee secretaries, preparing of drafts, text and figures for circulation by ISO Central Secretariat (ISO/CS) for enquiry and final draft International Standards or for publication. Fulfilling the ISO/CS submission requirements of such documents when sending them.


[[_idTextAnchor647]]
===== Excellent project management

Assisting in the establishment of priorities and target dates for each project. Notifying the names of all working group convenors and project leaders to the ISO Central Secretariat. Initiating ballots. Proposing proactive solutions for projects that are running significantly overtime, and/or which appear to lack sufficient support.


[[_idTextAnchor648]]
===== Well prepared meetings

Establishing the agenda and arranging for its distribution as well as the distribution of all documents on the agenda, including reports of working groups, and indicating all other documents which are necessary for discussion during the meeting. Recording the decisions taken in a meeting and making these decisions available in writing for confirmation in the meeting. Preparing the minutes of meetings to be circulated within 4 weeks after the meeting.


[[_idTextAnchor649]]
===== Good advice on ISO processes

Providing advice to the chair, project leaders, and convenors on the ISO/IEC Directives and in particular the procedures associated with the progression of projects. Contacting any subcommittees and working group regarding their activities.


[[_idTextAnchor650]]
===== Connecting and networking

Working in close liaison with the chair of the committee or convenor of the working group. Maintaining close contact with the ISO Central Secretariat and with the members of the committee or working group regarding its activities. Maintaining close contact with the secretary of any parent committee.


[[_idTextAnchor651]]
===== Proactive follow up of actions

Ensuring that all actions agreed at meetings or by correspondence are completed on time and in a transparent manner.


[[_idTextAnchor652]]
===== Good with IT

Have appropriate knowledge and capabilities in using MS Word based drafting tools and the ISO web-based applications, including the required use of ISO applications for communications and document sharing, in order to support the committtee's work.


[[_idTextAnchor653]]
===== Supporting Information

The following information should be considered by the member body when appointing secretaries:

* education
* professional career
* experience in standardization work
* participation in training programmes on standardization
* experience with ISO's IT tools and IT infrastructure
* language skills
