

[[_idTextAnchor654]]
[appendix]
== Statements intended to limit the purpose or use of deliverables

[[_idTextAnchor655]]
=== Principles

The ISO Technical Management Board adopted the following ISO/TMB Resolution 8/2012 regarding statements intended to limit the purpose or use of deliverables:

* Noting that ISO Council Resolution 9/2001 confirms ISO's compliance with the basic principles of the operation and implementation of the WTO Agreement on Technical Barriers to Trade (TBT),
* Agrees that statements intended to limit the purpose or use of deliverables in relation to barriers or obstacles to trade are not permitted,
* Further agrees that statements relating to contractual obligations or government regulation are also not permitted,
* Requests that any such statements be removed during the development of a deliverable (i.e. before the close of the DIS) and that any such statements in existing deliverables be removed when the deliverable is revised,
* Requires that any exceptions to the above in exceptional cases be approved by the ISO/TMB (…)

The ISO Technical Management Board also adopted the following ISO/TMB Resolution 69/2012 regarding statements intended to limit the purpose or use of deliverables in relation to conformity assessment ("conformity assessment disclaimers"):

* *Recalling* https://isotc.iso.org/livelink/livelink/fetch/-15620806/15620808/15623592/15768654/TMB_resolutions_-_2012_%28Resolution_1-148%29.pdf?nodeid=15768229&vernum=-2[TMB Resolution 8/2012] _Statements intended to limit the purpose or use of deliverables_,
+
(…)

* *Decides* that statements related to conformity assessment (for example certification) are not permitted in ISO deliverables,
+
(…)

* *Agrees* that any conformity assessment statements must be removed during the development of a deliverable (i.e. before the close of the DIS) and that any such statements in existing deliverables must be removed when the deliverable is revised, to be replaced by the link in the Foreword, and

* *Requires* that any exceptions to the above be approved by the TMB.


[[_idTextAnchor656]]
=== Further information regarding statements in relation to barriers or obstacles to trade

Various statements intended to limited purpose or use of deliverables (sometimes referred to as "disclaimers") in relation to barriers or obstacles to trade are included in a number of ISO deliverables. Though the wording differs slightly from case to case, they make the point that the deliverable in question is not intended to create barriers or obstacles to trade.

As explained on the http://www.standardsinfo.net/info/inttrade.html#2[ISO/IEC Information Centre], the https://www.wto.org/english/docs_e/legal_e/17-tbt.pdf[Agreement on Technical Barriers to Trade] (TBT) is one of the legal texts of the http://www.wto.org/english/docs_e/legal_e/final_e.htm[WTO Agreement]. It obliges http://www.wto.org/english/thewto_e/whatis_e/tif_e/org6_e.htm[WTO Members] to ensure that, inter alia, voluntary standards do not create unnecessary obstacles to trade. Specifically, link:https://www.wto.org/english/docs_e/legal_e/17-tbt_e.htm#annexIII[Annex III] of the TBT entitled Code of Good Practice for the Preparation, Adoption and Application of Standards (para. E) states: "The standardizing body shall ensure that standards are not prepared, adopted or applied with a view to or with the effect of, creating unnecessary obstacles to international trade."

Standardizing bodies within the territory of a WTO Member can notify their acceptance of the Code of Good Practice for the Preparation, Adoption and Application of Standards (Annex 3 to the TBT). A https://tbtcode.iso.org/sites/wto-tbt/home.html[list] is available of the standardizing bodies from the countries that have notified their acceptance. In accordance with the TBT, the onus is then on WTO Members to ensure that the TBT is respected within their respective territories.

The obligation to avoid obstacles to trade is therefore amply covered in the TBT. To add a TBT declaimer in some standards but not in others creates two classes of standards with no clear difference between the two. In fact, if the practice were allowed to continue, this could inadvertently create the impression that there are two different levels of compliance with the TBT.

In addition, the issue of ISO's general compliance with the basic principles of the operation and implementation of the TBT was considered by the ISO Council. By way of ISO Council Resolution 9/2001, the ISO Council confirmed that ISO was indeed compliant in this regard.


[[_idTextAnchor657]]
=== Further information regarding statements in relation to contractual obligations or government regulation

ISO/TMB Resolution 8/2012 reinforces the application of clause 4 of the ISO/IEC Directives, Part 2 which states that "A document shall not include contractual requirements (e.g. concerning claims, guarantees, covering of expenses) and legal or statutory requirements."

The ISO Technical Management Board also adopted the following ISO/TMB Resolution 70/2018 regarding the interpretation of "statements relating to contractual obligations or government regulation":

*Noting* the issues of interpretation related to Technical Management Board Resolution 8/2012 concerning the phrase "Further agrees that statements relating to contractual obligations or government regulation are also not permitted";

*Further noting* that

* text relating to compliance with contractual obligations, legal requirements and government regulations exists in many ISO standards; and
* ISO deliverables can be used to complement such requirements and serve as useful tools for all related stakeholders (which can include government authorities and industry players);

*Further noting* the responses received from the DMT consultation on this question;

*Clarifies* that, for all ISO deliverables:

. [[item_sr-a]]Statements that include an explicit requirement or recommendation to comply with any specific law, regulation or contract (such as a normative reference to such requirements), or portion thereof, are not permitted;
. Statements related to legal and regulatory requirements that do not violate point <<item_sr-a>> are permitted;
. Factual examples of the content of specific laws or regulations for informative purposes are permitted; and
. No exceptions shall be granted to point <<item_sr-a>>.

In addition, a document shall not include statements containing an explicit requirement or recommendation to comply with national law or statements that an ISO standard is not intended to conflict with national law. The application of ISO standards is voluntary and national law takes precedence in case of conflict. Furthermore, to add such statements in some standards but not in others creates two classes of standards. This could inadvertently create the impression that an ISO standard takes precedence over national law unless primacy of national law is expressly stated.


[[_idTextAnchor658]]
=== Further information on do's and don'ts related to conformity assessment

Further information regarding conformity assessment for standard writers is available in the publication entitled "Conformity assessment for standards writers -- Do's and Don'ts": https://www.iso.org/iso/PUB100303.pdf[https://www.iso.org/iso/PUB100303.pdf] and in clause 33 of ISO/IEC Directives, Part 2. Additional guidance is also contained in the generic text, a link to which is included in the Foreword of ISO deliverables (https://www.iso.org/foreword-info[www.iso.org/foreword-info]).


[[_idTextAnchor659]]
=== Requests for exceptions

Requests for exceptions to include a statement intended to limit the purpose or use of deliverables shall be approved by the ISO Technical Management Board who will carefully consider such requests on a case by case basis.
