
[[_idTextAnchor660]]
[appendix]
== Optional use of the Committee Draft (CD) stage -- Guidance for committees

The following is guidance for committees regarding the optional use of the Committee Draft (CD) stage.


[[_idTextAnchor661]]
=== Implementation guidance

* Decisions on whether to skip the CD should be made on a case by case basis.

* Decisions should be made on the basis of what is expected to be gained by a CD circulation (e.g. further understanding of an issue) compared to possible increases in costs and time (additional drafting and meetings).

* The proposal to skip the CD stage should be made by the Working Group Convenor/Project Leader following a consultation with the WG experts to prove consensus.

* The final decision should then be taken by the parent committee by consensus through a 4 week Committee Internal Ballot or at a meeting (for a definition of consensus, see <<_idTextAnchor167>>).

* In cases where there are concerns that skipping of the CD stage may seriously compromise consensus, then skipping the CD stage should be avoided.


[[_idTextAnchor662]]
=== Tips for Convenors and Project Leaders when proposing to skip the CD stage

. *Use* stage 0 to build a draft document which reflects already known stakeholder views.

. *Ensure* a high quality draft is circulated with the New Work Item Proposal.

. *Inform* the parent committee secretary as soon as it is known that the Working Group (WG) would like the project to skip the CD stage.

. *Ensure* P-members with a major interest in the subject have nominated experts to the WG and that consensus has been achieved on the document among the WG.

. *Ensure* appropriate number of re-iterations of Working Drafts circulations to the experts.

. Give regular updates about the status of the work to the secretary of the committee who in turn should provide updates to the P-members and circulate working drafts for information if necessary.

. *Ask* WG Experts to regularly inform their nominating P-members of the status of the work and encourage the WG experts to conduct informal consultations at the national level.

. *Ensure* the document submitted to the committee secretary is of high technical quality which is good enough for a DIS vote.

. *Always* ensure a full review of the DIS comments after the DIS vote.


[[_idTextAnchor663]]
=== Tips for committee Chairs and Secretaries

* Inform the members of the committee as soon as it is known that the Working Group would like to skip the CD stage.
* When submitting the DIS draft to ISO CS for preparation of the vote send the draft to the committee for information.


[[_idTextAnchor664]]
=== Other information

* This does not alter the current standards development timeframes which remain at 2, 3 or 4 years. The optional use of the CD will help you meet or beat your target dates that are set under these timeframes.
* For Vienna Agreement projects the CD can also be used on an optional basis.
