

[[_idTextAnchor665]]
[appendix]
== Twinning Policy

[[_idTextAnchor666]]
=== Scope

The objective of twinning is to build capacity and improve participation and performance in the twinned partner. The twinning objectives should support those priorities identified by the twinned partner and be integrated into their national development plans/strategies.

This policy is mandatory.


[[_idTextAnchor667]]
=== Definitions

==== {blank}

*Twinning:* A partnership agreement between two ISO members for the purposes of capacity building, where capacity building is defined as the "development of competencies (at National Body- NSB level) to be successful in ISO standardization work.


==== {blank}

*Lead partner:* The ISO member body providing the guidance, expertise and training.


==== {blank}

*Twinned partner:* The ISO member body seeking to build capacity.


==== {blank}

*Leadership twinning:* Twinning arrangements that involve learning the competencies relevant to leadership roles in the development of International Standards. There are three types of leadership twinning arrangements; chair, convenor and secretary. Through leadership twinning, the twinned partner has the opportunity to learn the skills and responsibilities needed to assume the chairmanship/convenorship/the role of a committee secretary.


==== {blank}

*Chair twinning:* An arrangement between a Chair and a Twinned-Chair.


==== {blank}

*Convenor twinning:* An arrangement between a Convenor and a Twinned Convenor.


==== {blank}

*Secretariat twinning:* An arrangement between a Secretariat and a Twinned Secretariat.


==== {blank}

*P-member twinning:* The lead partner and the twinned partner both need to be P-members of the committee in question. P-member Twinning allows the twinned partner, that may not yet have the level of competency required to cooperate on a leadership position, to participate actively in the technical work of standards development. P-member twinning allows members to gain specific targeted experience related to the work of a committee at the international and national levels (including the role of national mirror committees) and insight into the obligations of a P-member.


[[_idTextAnchor668]]
=== Requirements

To be eligible to participate in a twinning arrangement, the following requirements need to be met:

* Full membership of ISO (or participation in the ISO Council's New member rights pilot, in the case of P-member Twinning).
* Requirement to be a lead partner: demonstration of sufficient knowledge and experience (at NSB level) of the role in question.
* Requirement to be a twinned partner: demonstration of a need for capacity building, as evidenced by a lack of experience holding secretariats /appointing chairs or convenors/ participating actively in technical committees.

Selection criteria

The suggested experience for a lead partner is:

* Secretariat twinning: holding 5 or more committee secretariats.
* Chair or convenor twinning: having 5 or more appointed chairs or convenors.
* P-member twinning: being a P-member in 100 or more committees.

The suggested experience for a twinned partner is:

* Secretariat twinning: holding fewer than 5 committee secretariats.
* Chair or convenor twinning: having fewer than 5 appointed chairs or convenors.
* P-member twinning: being a P-member in fewer than 100 committees.


[[_idTextAnchor669]]
=== General principles

. *Voluntary in nature* -- Twinning arrangements are to be entered into voluntarily.

. *Objectives* -- Both partners to the arrangement shall be committed to the primary objective of twinning: to build capacity and improve participation and performance in the twinned partner. Twinning objectives should support those priorities identified by the twinned partner and integrated into their national development plans/strategies.

. *No expectation of financial support* -- There is no expectation that the lead partner will provide financial support to the twinned partner.

. *One country, one vote* -- Twinning arrangements shall have no influence in terms of national position. There should be no expectation that one partner will support the positions and views of the other partner. Twinning arrangements shall not jeopardize the principle of "one country, one vote" in ISO (and proxy voting is not allowed).

. *Cooperation* -- The cooperation should be viewed as broadly as possible, with a flexible approach, and include technical, strategic and policy-level activities between the partners.

. *Commitment* -- The commitment of both partners to the twinning arrangement should be sustained for the duration of the arrangement. By mutual agreement of the two partners, the lead partner may also assume other specific administrative tasks beyond providing training and guidance.

. *Continual improvement* -- Twinning arrangements should embrace the continual improvement concept. There should be mechanisms in place to ensure that, for each action, there is a possibility for follow-up and, if necessary, corrective action. Projects should include indicators to measure/monitor the progress of a twinned partner's participation and leadership in ISO, with progress reviewed on an annual basis.

. *Sustainability* -- The knowledge and experience gained through the twinning arrangement should be used to train other staff in the twinned partner to build capabilities in a sustainable manner. Participation in twinning should reduce, or remove altogether, the need for twinning of the twinned partner so that, once the twinning arrangement is finished, the twinned country can participate independently.


[[_idTextAnchor670]]
=== Procedure

[[_idTextAnchor671]]
==== Chronology

This Policy addresses the various aspects of a Twinning arrangement in the order of the life cycle of a typical Twinning arrangement noting that some stages may be done in parallel. Each stage is addressed as follows:

* Identifying the need for a Twinning arrangement (<<_idTextAnchor672>>)
* Selecting a Twinning partner (<<_idTextAnchor673>>)
* Drafting/Submitting a Twinning Request (<<_idTextAnchor674>>)
* Approving the Twinning Request (<<_idTextAnchor675>>)
* Implementing the Twinning arrangement (<<_idTextAnchor676>>)
* Terminating a twinning arrangement (<<_idTextAnchor677>>)
* Role of the ISO CS (<<_idTextAnchor678>>)


[[_idTextAnchor672]]
==== Identifying the need for a Twinning arrangement

Twinning arrangements are to be entered voluntarily. The partners shall fill in the Request Form (See Annex SJ) once they have agreed on the type of twinning (P-member, Secretariat, Chair or Convenor). In the case of a Secretariat or Chair twinning, the request form should be submitted to the TMB Secretariat. In the case of a WG Convenor twinning arrangement, it should be submitted directly to the parent committee and the ISO Technical Program Manager (TPM) for processing. For P-member twinning arrangements, the request form should be submitted to the TPM for review and the committee secretariat for information.


[[_idTextAnchor673]]
==== Selecting a Twinning partner

If a member body has identified the need for a twinning arrangement, but not a twinning partner, it can contact ISO/CS or the TPM of the committee in question, if a committee has been identified, and ask for help in identifying a partner to twin with.


[[_idTextAnchor674]]
==== Drafting/Submitting a Twinning Request

The following shall be included in the request form:

* Contact details of the ISO member bodies making the request
* Committee in which a twinning relationship is requested
* Type of twinning requested
* Statement from the ISO member body (twinned partner) demonstrating the need for capacity building and explaining what kind of capacity-building this arrangement will target
* Statement from the ISO member body (lead partner) demonstrating competencies and resources to support capacity building
* Goals and expected outcome of the twinning arrangement
* Proposed time frame of the twinning arrangement
* In the case of a leadership twinning arrangement, the contact details and CV of the Secretary/Twinned Secretary, Chair/Twinned-Chair, Convenor/Twinned Convenor

Secretariat or Chair twinning arrangements at TC, PC or SC level shall be approved by the TMB.

For WG Convenor Twinning arrangements, the requesting partners submit the Twinning request form directly to the secretariat of the parent committee for approval.

For P-member Twinning arrangements, the requesting partners submit the Twinning request form directly to the ISO/CS TPM (copied to the committee secretariat for information).


[[_idTextAnchor675]]
==== Approving the Twinning request:

* Secretariat and Chair twinning arrangements shall be submitted to the TMB Secretariat who will send the Twinning request form and supporting material to the TMB members for approval by correspondence (4-week CIB ballot). Supporting material for the ballot shall include an assessment from the TPM/ISO CS, plus any relevant statistics on NSB participation in ISO and performance in other committee leadership roles. The request is evaluated by the TMB according to the quality of the information, and against the above guidelines (suggested experience) for being a "lead" and "twinned" partner.
+
If approved by the TMB, the Secretariat or Chair twinning arrangement will be registered in the Global Directory (GD).

* For WG Convenor Twinning arrangements, the requesting NSBs submit the Twinning request form directly to the secretariat of the parent committee for approval. The committee then submits its decision to the TPM for processing.

* For P-member Twinning arrangements, the requesting NSBs submit the Twinning request form directly to the ISO/CS TPM (copied to the committee secretariat for information). The TPM reviews the form and registers the Twinning arrangement in the GD.

Once approved, the twinned partners shall submit a completed Twinning Agreement (with end date, maximum time limit of 5 years) and Collaboration Plan to their ISO/CS TPM within 3 months of the registration of the Twinning arrangement. See Annex SJ for the Forms. The TPM reviews the Agreement and Collaboration Plan and works with the twinned partners to improve it, if necessary. If the partners do not submit a satisfactory Twinning Agreement and Collaboration plan within 3 months, the twinning arrangement shall not be started.


[[_idTextAnchor676]]
==== Implementing the Twinning arrangement

Twinning arrangements shall be subject to an annual review and performance assessment, consisting of a self-assessment by the twinned partners, an assessment by the P-members of the committee, and an assessment by the TPM.

*Annual performance assessment form:* The twinned partners shall submit a completed form once per year. This form includes a section that will be completed by the TPM.

P-member assessments will be done as part of the regular post-meeting feedback survey process. The TPM reviews the results of these surveys and notes the P-member feedback on the Annual performance assessment form.

The TMB secretariat reviews the performance assessment forms and sends the completed forms back to the twinned partners for information. If there are no problems raised, the form is filed and the arrangement continues.


[[_idTextAnchor677]]
==== Terminating a Twinning arrangement

Failure to submit annual performance assessments or negative assessments/problems raised shall be brought to the attention of the TMB. The TMB evaluates the information and decides on any action to be taken. This may include the cancellation of the twinning arrangement.

Once a twinning arrangement reaches the 5-year maximum time limit, it is automatically terminated. Extensions/renewals of Twinning arrangements are not possible.

There shall be no automatic transfer of leadership roles (secretariat, chair, convenor) from the lead to the twinned partner at the end of the twinning arrangement. The twinned partner leadership roles shall be removed from the GD.

In the case of secretariat twinning, if the lead partner wishes to relinquish the secretariat, the committee may take a resolution to support the assignment of the secretariat to the twinned partner. In the case of an SC secretariat, the TC will approve this assignment based on the SC resolution. In the case of a TC secretariat, the ISO/TMB will approve this assignment based on the TC's resolution.

Any other changes to leadership roles shall follow the approval process outlined in the ISO/IEC Directives Part 1.


[[_idTextAnchor678]]
==== Role of ISO/CS

The Twinned partners' interface with ISO/CS is through the responsible TPM. The role of the TPM includes:

* Helping to identify a potential twinning partner in cases where a twinning partner/lead partner has not been identified
* Providing guidance and advice on how to implement the twinning policy
* Raising potential problems to the attention of the TMB

