source "https://rubygems.org"

gem "metanorma-cli", git: "https://github.com/metanorma/metanorma-cli", branch: "main"
gem "debug"
gem "sassc-embedded"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc", branch: "main"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "main"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "main"
gem "metanorma", git: "https://github.com/metanorma/metanorma", branch: "main"
gem "metanorma-taste", git: "https://github.com/metanorma/metanorma-taste", branch: "main"
gem "metanorma-utils", git: "https://github.com/metanorma/metanorma-utils", branch: "main"

gem "relaton", "= 3.0.0.pre.alpha.4"
gem "relaton-render", "= 3.0.0.pre.alpha.19"
gem "relaton-bib", "2.1.9"
gem "pubid", github: "pubid/pubid", branch: "main"
gem "moxml", github: "lutaml/moxml", branch: "main"
gem "leptris", "1.9.314"
