= ISO Rice document in Metanorma (Metanorma-ISO)

image:https://github.com/metanorma/mn-samples-iso/workflows/generate/badge.svg["Build Status", link="https://github.com/metanorma/mn-samples-iso/actions?query=workflow%3Agenerate"]
image:https://github.com/metanorma/mn-samples-iso/workflows/docker/badge.svg["Docker Build Status", link="https://github.com/metanorma/mn-samples-iso/actions?query=workflow%3Adocker"]

This document is available in its rendered forms here:

* https://metanorma.github.io/mn-samples-iso/[ISO Rice document (repository)]

== Introduction

This repository provides a readily usable  https://github.com/metanorma/metanorma-iso[Metanorma-ISO]
source document based on the
https://www.iso.org/publication/PUB100407.html["`Rice document`"],
the ISO's model document of an international standard.

Refer to the https://www.metanorma.com/overview/getting-started/[Metanorma quickstart] for a primer on creating Metanorma-ISO documents.


== Fetching the document

[source,sh]
----
git clone https://github.com/metanorma/mn-samples-iso/
----

== Installing Build Tools

See https://www.metanorma.com/overview/getting-started/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate
----


== Building The Document

[source,sh]
----
metanorma site generate
----


== Source files provided in this repo

* `iso-rice-en.adoc`: Metanorma-ISO markup source document for the Rice document, in English

* `sections/*`: The Metanorma-ISO markup source document for the Rice document, broken up into separate files for each section

* `iso-rice-en-sections.adoc`: Metanorma-ISO markup source document for the Rice document, referencing the individual files in `sections/*`

* `iso-rice-zh.adoc`: Metanorma-ISO markup source document for the Rice document, in Chinese


== Description of generated artifacts

* `{filename}-{lang}.xml`: Metanorma-ISO XML output corresponding to the `{filename}-{lang}.adoc` source

* `{filename}-{lang}.html`: Metanorma-ISO HTML output corresponding to the `{filename}-{lang}.adoc` source

* `{filename}-{lang}-alt.html`: Metanorma-ISO "`readability-optimized`" HTML output corresponding to the `{filename}-{lang}.adoc` source


== Managing an IsoDoc

=== General

The Rice document is given here both as a single source document and broken up into separate files, to illustrate both ways of managing Metanorma content.

=== Single file

There are two document examples provided here:

* `iso-rice-en.adoc`: the Rice document in English
* `iso-rice-zh.adoc`: the Rice document as translated to Chinese

For each language:

* the file `iso-rice-{lang}.adoc` provides the document header
* the file `body/body-{lang}.adoc` provides the content body.


=== Multiple files

The document `iso-rice-en-sections.adoc` includes the document header and the following files.

The section files are listed in order of appearance in the document, and each corresponds to a first-level clause of the Rice document:

* `00-foreword.adoc`: Foreword
* `00-introduction.adoc`: Introduction
* `01-scope.adoc`: Scope
* `02-normref.adoc`: Normative references
* `03-termdef.adoc`: Terms and definitions
* `04-specifications.adoc`: Clause 4: Specifications
* `05-sampling.adoc`: Clause 5: Sampling
* `06-testmethods.adoc`: Clause 6: Test Methods
* `07-testreport.adoc`: Clause 7: Test Report
* `08-packaging.adoc`: Clause 8: Packaging
* `09-marking.adoc`: Clause 9: Marking
* `aa-annex-a.adoc`: Annex A
* `ab-annex-b.adoc`: Annex B
* `ac-annex-c.adoc`: Annex C
* `ad-annex-d.adoc`: Annex D
* `ae-annex-e.adoc`: Annex E (not in original Rice document, included to illustrate further formatting options)
* `b0-bibliography.adoc`: Bibliography

