
[[terms]]
== Terms and definitions

=== attribute

inherent characteristic of a person

[example]
Visual acuity; sensitivity to others; openness.

[.source]
<<iso17027,clause 2.10>>


=== competence

ability to apply term:[knowledge], term:[skills,skill] and term:[attributes,attribute] to achieve intended results

NOTE: "`Competence`" can also be referred to as "`competency`".

[.source]
<<iso9000>>, "`attributes`" and Note 1 to entry have been added.


=== knowledge

facts, information, truths, principles or understanding acquired through experience or education

[.source]
<<iso17027,clause 2.56>>


=== skill

ability acquired through education, training, experience or other means to perform a term:[task] or an activity with a specific intended outcome

[.source]
<<iso17027,clause 2.74>>, The wording in the definition has been reordered.


=== task

set of activities undertaken in order to achieve a specific goal

NOTE: These activities can be physical, perceptual and/or cognitive.

NOTE: While goals are independent of the means used to achieve them, tasks describe particular means of achieving goals.

[.source]
<<iso9241_11,clause 3.1.11>>
