[.preface]
== Foreword

The ISO/IEC Directives, Part 2 has been prepared by the ISO/IEC Joint Directives Maintenance Team (JDMT) and approved by the ISO Technical Management Board (ISO/TMB) and IEC Standardization Management Board (IEC/SMB).

This eighth edition of the ISO/IEC Directives, Part 2 cancels and replaces the seventh edition published in 2016.

This edition includes the following significant changes compared to the previous edition:

* updating of reference documents, cross-references and examples;
* addition of terminological entries for "`Technical Specification`" (<<scls_3-1-5>>), "`Publicly Available Specification`" (<<scls_3-1-6>>), "`Guide`" (<<scls_3-1-7>>), "`Technical Report`" (<<scls_3-1-8>>);
* review of grammar and linguistic consistency of definitions in <<cls_3>>;
* replacement of "`Verbal form`" with "`Preferred verbal form`" in <<table_3>> to <<table_7>>;
* deletion of "`needs to`" and "`need not`" as equivalent expressions in <<table_3>>;
* replacement of "`need not`" with "`may not`" as expression of permission in the negative form in <<table_5>>;
* clarification in <<scls_8-1>> that the general policy on the use of languages is explained in the ISO/IEC Directives, Part 1;
* redrafting of text describing how normative references are cited in the text (in <<scls_10-2>>, <<scls_15-1>>, <<scls_15-5-3>> and <<table_a-1>>) to improve clarity of meaning;
* addition of <<item_10-2-e>>, regarding the rules relating to referencing of patented items;
* inclusion of a statement in <<cls_14>> that the Scope shall be numbered as <<cls_1>>;
* inclusion of statements in <<cls_15>> that the Normative references clause shall be numbered as <<cls_2>> and that it shall only appear once in a document;
* inclusion of statements in <<cls_16>> that the Terms and definitions clause shall be numbered as <<cls_3>> and that it shall only appear once in a document;
* inclusion of statements in <<cls_16>> that terms shall be presented in their basic grammatical form and that a definition shall not take the form of, or contain, a requirement (in accordance with ISO 10241-1);
* clarification in <<scls_20-2>> that informative annexes may contain optional requirements;
* inclusion of a statement in <<scls_21-4>> that the Bibliography shall not have a clause number;
* splitting of former <<cls_34>> into <<cls_34>> and <<cls_35>>, with clarification of where to find additional rules on management standards and management system standards;
* addition of a new <<figure_6>> (Example of a graph) and renumbering of subsequent figures;
* revision of <<figure_1>>, <<figure_7>> (former Figure 6) and <<figure_10>> (former Figure 9);
* inclusion of a new <<table_8>> to summarize how to use notes and footnotes within documents, and renumbering of subsequent tables;
* inclusion of cross-references in the checklist in <<annex_a>>.

It is not the intention that the ISO/IEC Directives, Part 2 follow the same structure and drafting rules as International Standards and associated publications (referred to collectively as documents, see <<scls_3-1-1>>).

This eighth edition of the ISO/IEC Directives, Part 2 is applicable to all enquiry drafts and to all final drafts registered after 2018-10-01.

Both ISO and IEC have published guides on the use of templates and other tools for the preparation of documents prepared in accordance with the ISO/IEC Directives. These guides are available on the ISO website (http://www.iso.org) and IEC website (http://www.iec.ch).


