
[.preface]
== Introduction

The ISO/IEC Directives, Part 2 states the general principles by which ISO and IEC documents are drafted and stipulates certain rules to be applied in order to ensure that they are clear, precise and unambiguous. These rules are also important for ensuring that each document contributes effectively to the consistent and interdependent body of knowledge that ISO and IEC produce.

It is recognized that the ever-increasing range of subject matter covered by ISO and IEC reflects an increasingly diverse range of users of their documents, both geographical and in terms of the level and type of technical expertise that it can be expected to have. Those drafting ISO and IEC documents should try to be aware of the particular needs of their intended users and to write in a style that is likely to be readily understood. It is particularly important to be conscious of the likelihood that a document will be translated.

Advice on applying the ISO/IEC Directives, Part 2 is readily available from ISO Central Secretariat and IEC Central Office, as appropriate, and it should be sought whenever any difficulties are encountered.
