
[[cls_4]]
== Objective of standardization

The objective of documents is to specify clear and unambiguous provisions in order to help international trade and communication. To achieve this objective, documents shall:

* be complete within the limits specified by their scope;
+
NOTE: When a document provides requirements or recommendations, these are either written explicitly, or made by reference to other documents (see <<cls_10>>).

* be consistent, clear and accurate;
* be written using all available knowledge about the state of the art;
* take into account the current market conditions;
+
NOTE: There is sometimes a tension between what is technically feasible and what the market actually requires and is prepared to pay for.

* provide a framework for future technological development;
* be comprehensible to qualified people who have not participated in their preparation; and
* conform to the ISO/IEC Directives, Part 2.

A document does not in itself impose any obligation upon anyone to follow it. However, an obligation can be imposed, for example, by legislation or by a contract which makes reference to the document.

A document shall not include contractual requirements (e.g. concerning claims, guarantees, covering of expenses) and legal or statutory requirements.
