
[[cls_8]]
== Language, spelling, abbreviated terms, style and basic reference works

[[scls_8-1]]
=== Language versions

The general policy on languages is explained in the ISO/IEC Directives, Part 1.

The different language versions of documents shall be technically equivalent and structurally identical.

The use of bilingualism from the initial stage of drafting is of great assistance in the preparation of clear and unambiguous texts.

Documents containing text in languages additional to the official languages shall contain the following text (completed as appropriate) in the Foreword.

____
In addition to text written in the official … [ISO or IEC] … languages (English, French, Russian), this document gives text in … [language] …. This text is published under the responsibility of the Member Body/National Committee for … (…) and is given for information only. Only the text given in the official languages can be considered as … [ISO or IEC] … text.
____


=== Spelling reference works

The following reference works for spelling are suggested:

* for English, The Shorter Oxford English Dictionary, The Concise Oxford Dictionary, The Collins Concise English Dictionary, Webster’s New World College Dictionary or Chambers Concise Dictionary;
* for French, Dictionnaire Le Robert, Dictionnaire Larousse and Dictionnaire des difficultés de la langue française (V. Thomas, Larousse).


=== Spelling and abbreviated forms of names of organizations

The names of organizations, and their abbreviated forms, shall be written as used by those organizations, in English, French or Russian.


=== Abbreviated terms

The use of abbreviated terms shall be consistent throughout the document.

If a list of abbreviated terms is not given in the document (see <<cls_17>>), then the first time that an abbreviated term is used, the full term shall be given with the abbreviated term following in brackets.

[example]
… the weighted root mean square (RMS) width of the active output interface optical spectrum …

Any abbreviated term should be in upper case letters, without a full stop after each letter.

[example]
"`RH`" for "`relative humidity`".


Occasionally, abbreviated terms in common use are written differently, either for historical or for technical reasons.

Technical specifications regarding marking may impose other requirements.


=== Linguistic style

To help users understand and use the document correctly, the linguistic style shall be as simple and concise as possible. This is particularly important for those users whose first language is not one of the official languages of ISO and IEC.
