
[[cls_13]]
[heading=clause]
== Introduction

[[scls_13-1]]
=== Purpose or rationale

The Introduction provides specific information or commentary about the technical content of the document, and about the reasons prompting its preparation.

[[scls_13-2]]
=== Normative or informative?

The Introduction is an informative element. It shall not contain requirements.

[[scls_13-3]]
=== Mandatory, conditional or optional?

The Introduction is an optional element. It is only mandatory if a specific patent right has been identified during the development of the document.

[[scls_13-4]]
=== Numbering and subdivision

The Introduction shall not have a clause number. If there is a need to create numbered subdivisions, the subclauses are numbered 0.1, 0.2, etc. Any figure, table, displayed formula or footnote shall be numbered starting with 1.

[[scls_13-5]]
=== Specific principles and rules

Whenever alternative solutions are offered in a document and preferences for the different alternatives provided, the reasons for the preferences shall be explained in the Introduction.

Where patent rights have been identified in a document, the Introduction shall include an appropriate notice. See <<cls_30>>.

