
[[cls_17]]
== Symbols and abbreviated terms (concept)

[[scls_17-1]]
=== Purpose or rationale

The symbols and abbreviated terms clause or subclause provides a list of the symbols and abbreviated terms used in the document, along with their definitions.

[[scls_17-2]]
=== Normative or informative?

The symbols and abbreviated terms clause is a normative element.


[[scls_17-3]]
=== Mandatory, conditional or optional?

The symbols and abbreviated terms clause is a conditional element.


[[scls_17-4]]
=== Numbering and subdivision

The symbols do not need to be numbered. For convenience, the symbols and abbreviated terms may be combined with the terms and definitions in order to bring together terms and their definitions, symbols and abbreviated terms under an appropriate composite title, for example "`Terms, definitions, symbols and abbreviated terms`".


[[scls_17-5]]
=== Specific principles and rules

Only symbols used in the text shall be listed.

Unless there is a need to list symbols in a specific order to reflect technical criteria, all symbols should be listed in alphabetical order in the following sequence:

* upper case Latin letter followed by lower case Latin letter (_A_, _a_, _B_, _b_, etc.);
* letters without indices preceding letters with indices, and with letter indices preceding numerical ones (_B_, _b_, _C_, _C~m~_, _C~2~_, _c_, _d_, _d~ext~_, _d~int~_, _d~1~_, etc.);
* Greek letters following Latin letters (_Z_, _z_, _Α_, _α_, _Β_, β, …, Λ, λ, etc.);
* any other special symbols.