
[[cls_19]]
== Marking, labelling and packaging

[[scls_19-1]]
=== Purpose or rationale

Marking, labelling and packaging are important aspects related to product manufacturing and procurement that frequently need a standardized approach, particularly in safety critical applications.


[[scls_19-2]]
=== Normative or informative?

Marking, labelling and packaging clauses are usually normative elements although exceptions can exist (e.g. when only recommendations are made concerning marking, labelling and packaging).


[[scls_19-3]]
=== Mandatory, conditional or optional?

Marking, labelling and packaging clauses are conditional elements.


[[scls_19-4]]
=== Specific principles and rules

[[scls_19-4-1]]
==== General

Marking, labelling and packaging are complementary aspects that shall be included wherever relevant, particularly for product standards concerning consumer goods.

If necessary, the means of marking shall also be specified or recommended.

This element shall not specify or recommend marks of conformity. Such marks are normally applied under the rules of a certification system – see ISO/IEC Guide 23. Information on the marking of products with reference to a standards body or its documents is given in ISO/IEC 17050-1 and ISO/IEC 17050-2.

Information on safety standards and aspects related to safety is given in ISO/IEC Guide 51.

This element may be supplemented by an informative annex giving an example of information necessary for the purposes of procurement.


[[scls_19-4-2]]
==== Requirements concerning marking, labelling and packaging of products

Documents containing a reference to the marking of the product shall specify the following, where applicable:

. the content of any marking that is used to identify the product, for example:
.. the manufacturer (name and address);
.. responsible supplier (trade name, trademark or identification mark);
.. the marking of a product itself [for example manufacturer's or supplier's trademark, model or type number, designation (see <<annex_c>>)];
.. the identification of different sizes, categories, types and grades;
. the means of presentation of such marking, for example by the use of plates (sometimes called "`name-plates`"), labels, stamps, colours, threads (in cables), as appropriate;
. the location on the product, or in some cases on the packaging, where the marking is to appear;
. requirements for the labelling and packaging of the product (e.g. handling instructions, hazard warnings, date of manufacture);
. other information as required.

If the document requires the application of a label, the document shall also specify the nature of the labelling and how it is to be attached, affixed or applied to the product or its packaging.

Symbols specified for marking shall conform to relevant documents published by ISO and IEC.

NOTE: Documents relating to packaging can be found under the ICS classification 55 in the ISO and IEC Catalogues.


[[scls_19-4-3]]
==== Requirements concerning documentation accompanying the product

Documents may require that the product be accompanied by some kind of documentation (e.g. test report, handling instructions, other information appearing in the product packaging). When relevant, the content of such documentation shall be specified.

NOTE: A classification and designation system of such documentation for plants, systems and equipment is provided in IEC 61355-1. Rules for such documentation in administration, commerce and industry can be found under the ICS classification 01.140.30.


[[scls_19-4-4]]
==== Warning notices and instructions

In product standards, it is sometimes necessary to specify that the product shall be accompanied by warning notices or by instructions to the installer or user, and to specify their nature. Such requirements concerning installation or use may be included in a separate part of the series or a separate document, because they are not requirements applicable to the product.
