
[[cls_26]]
== Footnotes

[[scls_26-1]]
=== Purpose or rationale

Footnotes to the text of a document are used to give additional contextual information to a specific item in the text. The document shall be usable without the footnotes.

For rules on footnotes to figures, see <<scls_28-5-5>>.

For rules on footnotes to tables, see <<scls_29-5-2>>.


[[scls_26-2]]
=== Title

Footnotes do not have a title.


[[scls_26-3]]
=== Numbering and subdivision

Footnotes shall be numbered sequentially throughout the document. Normally, footnote references are indicated using Arabic numerals. Exceptionally, other systems (a, b, c, etc.; *, **, ***, etc.; †, ‡, etc.) can be used, for example when there is the possibility of confusing them with superscript numbers.


[[scls_26-4]]
=== Referencing

Footnotes shall be referenced in the text.

Use, for example, the following form for references to footnotes:


* ISO 1234:–^1^ lists the test methods for…

&#x200c;-------------

^1^ Under preparation. Stage at the time of publication: ISO/DIS 1234:2014.


[[scls_26-5]]
=== Specific principles and rules

A footnote can appear anywhere within the text of a document apart from terminological entries.

Footnotes shall not contain requirements (e.g. use of "`shall`", see <<table_3>>) or any information considered indispensable for the use of the document, for example instructions (imperative mood), recommendations (e.g. use of "`should`", see <<table_4>>) or permission (e.g. use of "`may`", see <<table_5>>). Footnotes should be written as a statement of fact.

[[scls_26-6]]
=== Examples

====
C.1.1   Introduction +
...multiplex real-time PCR method based on TaqMan(R)^7^. +
&#x200c;--------- +
^7^ TaqMan(R) is a trademark of Roche Molecular Systems. This information is given for the convenience of users of this document and does not constitute an endorsement by ISO of the product named.
====

====
…such effects of salt mist on connectors has been demonstrated^[2]5^. +
&#x200c;--------- +
^5^ Numbers in square brackets refer to the Bibliography.
====

