
[[cls_31]]
== Use of trade names and trademarks

A correct designation or description of a product shall be given rather than a trade name or trademark.

Proprietary trade names or trademarks for a particular product should as far as possible be avoided, even if they are in common use.

If, exceptionally, trade names or trademarks cannot be avoided, their nature shall be indicated, for example by the symbol (R) for a registered trademark (see <<ex_30-1>>) and by the symbol (TM) for a trademark.


[[ex_30-1]]
====
Instead of "`Teflon(R)`", write "`polytetrafluoroethylene (PTFE)`".
====

If it is known that only one product is currently available that is suitable for the successful application of the document, the trade name or trademark of the product may be given in the text of the document but shall be associated with a footnote as shown in <<ex_30-2>>.

[[ex_30-2]]
====
… [trade name or trademark of product] … is the [trade name or trademark] of a product supplied by … [supplier] …. This information is given for the convenience of users of this document and does not constitute an endorsement by … [ISO or IEC] … of the product named. Equivalent products may be used if they can be shown to lead to the same results.
====

If it is considered essential to give an example (or examples) of commercially available products suitable for successful application of the document because the product characteristics are difficult to describe in detail, trade names or trademarks may be given in a footnote as shown in <<ex_30-3>>.

[[ex_30-3]]
====
… [trade name(s) or trademark(s) of product(s)] … is (are) an example(s) of a suitable product(s) available commercially. This information is given for the convenience of users of this document and does not constitute an endorsement by … [ISO or IEC] … of this (these) product(s).
====

