
[[cls_33]]
== Aspects of conformity assessment

[[scls_33-1]]
=== Documents containing requirements for products, processes, services, persons, systems and bodies

All documents containing requirements for products, processes, services, persons, systems and bodies shall be written in accordance with the "`neutrality principle`", such that conformity can be assessed by a manufacturer or supplier (first party), a user or purchaser (second party), or an independent body (third party).

NOTE: First-party, second-party and third-party conformity assessment activities are defined in ISO/IEC 17000.

NOTE: The term "`document`" is defined in <<scls_3-1-1>>.

Such documents shall not include requirements related to conformity assessment other than requirements which are necessary to provide repeatable and reproducible conformity assessment results.

Committees wishing to specify additional conformity assessment requirements for the product, process, service, persons, systems or bodies may only do so in a separate document or in a separate part of the document provided that the separate parts can be applied independently. Prior to commencing work on a separate document or separate part, a committee shall seek the approval of the ISO Committee on conformity assessment (ISO/CASCO) or IEC Standardization Management Board (IEC/SMB) or both as applicable.

For particular requirements in IEC, see the ISO/IEC Directives, Supplement – Procedures specific to IEC.

No document containing requirements for products, processes, services, persons, systems and bodies shall make conformity dependent on a quality management systems standard (i.e. it shall not, for example, make normative reference to ISO 9001).


[[scls_33-2]]
=== Conformity assessment schemes and systems

Committees shall not develop documents providing general requirements for conformity assessment schemes and systems. Development of such documents is the responsibility of the ISO policy committee ISO/CASCO in liaison with the IEC Conformity Assessment Board (IEC/CAB).

Committees wishing

. to propose the establishment of a conformity assessment scheme or system, or
. to prepare documents specifying conformity assessment systems or schemes or sector-specific operating procedures for use by conformity assessment bodies and others for conformity assessment purposes,

shall consult with the secretariat of ISO/CASCO or IEC/CAB or both as appropriate, prior to commencement of the work to ensure that any documents developed are in line with the conformity assessment policies and rules approved by ISO/CASCO and IEC/CAB as relevant.


[[scls_33-3]]
=== References to ISO/IEC conformity assessment documents

When a committee develops a document relating to conformity assessment systems or schemes, or any other document addressing conformity assessment aspects, the document shall make normative reference to the relevant published ISO/IEC documents for conformity assessment procedures, including ISO/IEC 17000 and ISO/IEC 17025. The committee may include verbatim text from the
ISO/IEC documents for conformity assessment procedures but the committee shall not delete, change or interpret them. Committees shall consult with the ISO/CASCO or the IEC/CAB secretary or both, as appropriate, for advice on correctly referencing the ISO/IEC conformity assessment documents. Any request for addition, deletion, change or interpretation shall be submitted to the secretariats of
ISO/CASCO and IEC/CAB for decision.
