
[[cls_35]]
== Management standards (MS) and management systems standards (MSS)

Rules for the drafting of management standards and management systems standards (including sector-specific standards) are given in Annex SL and Annex SP of the ISO Supplement to the ISO/IEC Directives, Part 1.

When an ISO or IEC committee wishes to develop quality management system requirements or guidance for a particular product or industry/economic sector, it shall respect the following rules.

. Normative reference shall be made to ISO 9001 in its entirety. Alternatively, the clauses or subclauses may be reproduced verbatim.

. If text from ISO 9001 is reproduced in the sector document, it shall be distinguished from the other elements of the sector document [see <<item_35-d>>].

. Terms and definitions specified in ISO 9000 shall be referred to in a normative manner or reproduced verbatim.

. [[item_35-d]]The guidance and criteria provided in _Quality management systems – Guidance and criteria for the development of documents to meet needs of specific product and industry/economic sectors_, approved by ISO/TC 176, shall be considered not only when determining the need for a sector-specific requirements or guidance document but also in the document development process.

Any requests for guidance on this sector policy or for interpretation of ISO 9000 terms and definitions, ISO 9001 or ISO 9004 shall be submitted to the secretariat of ISO/TC 176.

