[[intro]]
== Introduction

This document was developed in response to worldwide demand for minimum
specifications for rice traded internationally, since most commercial bulks of
grain, which have not been screened or aspirated, contain a proportion of other
grains, weed seeds, chaff, straw, stones, sand, etc. The vegetable materials can
have physical and biological properties which differ from those of the main
constituent and can therefore affect the storage behaviour.

Rice is a permanent host to a considerable microflora; most of these
microorganisms are cosmopolitan, the majority are innocuous, but some produce
harmful by-products. Microflora communities present on freshly harvested rice
include many types of bacteria, moulds and yeasts. While the rice is ripening
and its moisture content is falling, the number of field microorganisms, mainly
bacteria, diminishes. When the rice is harvested, it is invaded by storage
microorganisms and the field microflora gradually die out. If the mass fraction
of moisture (formerly expressed as moisture content) is less than 18 %, the
microflora does not multiply, whereas above 18 % it does so rapidly. Thus, at
harvest, the qualitative and the quantitative composition of the microflora
depends more upon ecological factors than upon the variety of the rice. During
transport and storage, additions to the microfloral population occur.
Microorganisms on the rice at harvest tend to die out during storage and are
replaced by microorganisms adapted to storage conditions.

Storage losses have been estimated as being an average of 5 %, and as much as 30
%, especially in regions with climates favourable to the rapid development of
agents of deterioration, such as tropical climates. The magnitude of these
figures highlights the need to promote a rapid improvement in techniques of
conservation worldwide.

[reviewer=ISO,from=intro,to=intro]
****
* Optional element
* Provides background information about the technical content
** ISO/IEC Directives, Part 2, 2021, Clause 13
****
