
== Terms, definitions and abbreviated terms

=== Terms and definitions

==== greenhouse gas
alt:[GHG]

gaseous constituent of the atmosphere, both natural and term:[anthropogenic], that absorbs and emits radiation at specific wavelengths within the spectrum of infrared radiation emitted by the Earth’s surface, the atmosphere, and clouds

[.source]
<<iso14064_1,clause 3.1.1>>, The Notes to entry have been removed.


==== greenhouse gas emission
alt:[GHG emission]

release of a term:[GHG,greenhouse gas] into the atmosphere

[.source]
<<iso14064_1,clause 3.1.5>>


==== greenhouse gas removal
alt:[GHG removal]

withdrawal of a term:[GHG,greenhouse gas] from the atmosphere

[.source]
<<iso14064_1,clause 3.1.6>>, The words "`by GHG sinks`" have been removed from the definition.


==== anthropogenic

resulting from or caused by human activity


=== Abbreviated terms

CC:: Climate Change
CCM:: Climate Change Mitigation
CCS:: Carbon Dioxide Capture and Storage
CCU:: Carbon Dioxide Capture and Utilization
CFP:: Carbon Footprint of a Product
GHG:: Greenhouse Gas

