
[.preface]
== INTRODUCTION TO THE CONSOLIDATED ISO SUPPLEMENT

=== What is the Consolidated ISO Supplement?

The ISO/IEC Directives define the basic procedures to be followed in the development of International Standards and other publications. This Consolidated ISO Supplement (also referred to as the "ISO Supplement") contains both the ISO/IEC Directives, Part 1 and the procedures specific to ISO which were formerly referred to as the "ISO Supplement".

Part 1 of the ISO/IEC Directives, together with this Consolidated ISO Supplement, provide the complete set of procedural rules to be followed by ISO committees. There are, however, other documents to which reference may need to be made. In particular, for committees cooperating with CEN under the Agreement on technical cooperation between ISO and CEN (Vienna Agreement), reference should be made to the https://isotc.iso.org/livelink/livelink/fetch/2000/2122/4230450/4230458/02__Guidelines_for_the_implementation_of_the_Agreement_on_Technical_Cooperation_between_ISO_and_CEN_%28the_Vienna_Agreement%29_6th_ed._Jan_2014.pdf?nodeid=4230689&vernum=-2[Guidelines for Chairmen and Secretariats on the implementation of the Vienna Agreement].

Attention is also drawn to the fact that ISO/IEC JTC 1 Information technology has adopted ISO/IEC Directives, Part 1 together with the https://isotc.iso.org/livelink/livelink/open/jtc1supplement[JTC 1 Supplement].

=== The structure of this Consolidated ISO Supplement

The clause structure of the Consolidated ISO Supplement follows that of Part 1 of the ISO/IEC Directives. In order to assist in cross-referencing the texts, the ISO specific clauses are highlighted in blue under the clauses of the ISO/IEC Directives. If there is no highlighted blue text under a particular clause, it means that there are no ISO-specific clauses.

Tables and annexes beginning with "S" in this Consolidated ISO Supplement are all unique to ISO and do not follow the order in the ISO/IEC Directives. Where a reference in an ISO annex (i.e. beginning with "S") is made to an annex in the ISO/IEC Directives, Part 1, this is explicitly indicated.

The following clauses that have been modified with respect to the previous edition of the ISO Supplement: Foreword, <<_idTextAnchor128>>, <<_idTextAnchor129>>, <<_idTextAnchor143>>, <<_idTextAnchor194>>, <<_idTextAnchor198>>, <<_idTextAnchor203>>, <<_idTextAnchor204>>, <<_idTextAnchor233>>, Annex SA, Annex SH, Annex SK, Annex SL, Annex SN, Annex SP, Annex SQ and Reference documents. The track change version of this eleventh edition should be consulted for the details of the changes made (http://www.iso.org/directives[www.iso.org/directives]).