
== Organizational structure and responsibilities for the technical work

[[_idTextAnchor005]]
=== Role of the technical management board

The technical management board of the respective organization is responsible for the overall management of the technical work and in particular for:

. establishment of technical committees;

. appointment of chairs of technical committees;

. allocation or re-allocation of secretariats of technical committees and, in some cases, subcommittees;

. approval of titles, scopes and programmes of work of technical committees;

. ratification of the establishment and dissolution of subcommittees by technical committees;

. allocation of priorities, if necessary, to particular items of technical work;

. coordination of the technical work, including assignment of responsibility for the development of standards regarding subjects of interest to several technical committees, or needing coordinated development; to assist it in this task, the technical management board may establish advisory groups of experts in the relevant fields to advise it on matters of basic, sectoral and cross-sectoral coordination, coherent planning and the need for new work;

. monitoring the progress of the technical work with the assistance of the office of the CEO, and taking appropriate action;

. reviewing the need for, and planning of, work in new fields of technology;

. maintenance of the ISO/IEC Directives and other rules for the technical work;

. consideration of matters of principle raised by National Bodies, and of appeals concerning decisions on new work item proposals, on committee drafts, on enquiry drafts or on final draft International Standards.

NOTE: Explanations of the terms "new work item proposal", "committee draft", "enquiry draft" and "final draft International Standard" are given in <<_idTextAnchor109>>.

NOTE: For detailed information about the role and responsibilities of the ISO technical management board, see the Terms of reference of the TMB -- https://www.iso.org/committee/4882545.html[https://www.iso.org/committee/4882545.html] and for the IEC see https://www.iec.ch/dyn/www/f?p=103:47:0::::FSP_ORG_ID,FSP_LANG_ID:3228,25[https://www.iec.ch/dyn/www/f?p=103:47:0::::FSP_ORG_ID,FSP_LANG_ID:3228,25].


=== Advisory groups to the technical management board

==== {blank}

A group having advisory functions in the sense of <<_idTextAnchor005>> g) may be established

. by one of the technical management boards;
. jointly by the two technical management boards.

NOTE: In IEC certain such groups are designated as Advisory Committees.


[[_idTextAnchor009]]
==== {blank}

A proposal to establish such a group shall include recommendations regarding its terms of reference and constitution, bearing in mind the requirement for sufficient representation of affected interests while at the same time limiting its size as far as possible in order to ensure its efficient operation. For example, it may be decided that its members be only the chairs and secretaries of the technical committees concerned. In every case, the TMB(s) shall decide the criteria to be applied and shall appoint the members.

Any changes proposed by the group to its terms of reference, composition or, where appropriate, working methods shall be submitted to the technical management boards for approval.


[[_idTextAnchor010]]
==== {blank}

The tasks allocated to such a group may include the making of proposals relating to the drafting or harmonization of publications (in particular International Standards, Technical Specifications, Publicly Available Specifications and Technical Reports), but shall not include the preparation of such documents unless specifically authorized by the TMB(s).


[[_idTextAnchor011]] 
==== {blank}

Any document being prepared with a view to publication shall be developed in accordance with the procedural principles given in <<_idTextAnchor293>>.


[[_idTextAnchor012]]
==== {blank}

The results of such a group shall be presented in the form of recommendations to the TMB(s). The recommendations may include proposals for the establishment of a working group (see <<_idTextAnchor068>>) or a joint working group (see <<_idTextAnchor074>>) for the preparation of publications. Such working groups shall operate within the relevant technical committee, if any.


[[_idTextAnchor013]]
==== {blank}

The internal documents of a group having advisory functions shall be distributed to its members only, with a copy to the office(s) of the CEO(s).


[[_idTextAnchor014]]
==== {blank}

Such a group shall be disbanded once its specified tasks have been completed, or if it is subsequently decided that its work can be accomplished by normal liaison mechanisms (see <<_idTextAnchor092>>).


[[_idTextAnchor016]]
=== Joint technical work

[[_idTextAnchor017]]
==== Joint Technical Advisory Board (JTAB)

The JTAB has the task of avoiding or eliminating possible or actual overlapping in the technical work of ISO and IEC and acts when one of the two organizations feels a need for joint planning. The JTAB deals only with those cases that it has not been possible to resolve at lower levels by existing procedures. (See <<_idTextAnchor306>>.) Such cases may cover questions of planning and procedures as well as technical work.

Decisions of the JTAB are communicated to both organizations for immediate implementation. They shall not be subject to appeal for at least 3 years.


[[_idTextAnchor018]]
==== Joint Technical Committees (JTC) and Joint Project Committees (JPC)

[[_idTextAnchor019]]
===== {blank}

JTC and JPC may be established by a common decision of the ISO/TMB and IEC/SMB, or by a decision of the JTAB.


[[_idTextAnchor020]]
===== {blank}

For JPC, one organization has the administrative responsibility. This shall be decided by mutual agreement between the two organizations.

Participation is based on the one member/country, one vote principle.

Where two National Bodies in the same country elect to participate in a JPC then one shall be identified as having the administrative responsibility. The National Body with the administrative responsibility has the responsibility of coordinating activities in their country, including the circulation of documents, commenting and voting.

Otherwise the normal procedures for project committees are followed (see <<_idTextAnchor064>>).


[[_idTextAnchor022]]
=== Role of the Chief Executive Officer

The Chief Executive Officer of the respective organization is responsible, inter alia, for implementing the ISO/IEC Directives and other rules for the technical work. For this purpose, the office of the CEO arranges all contacts between the technical committees, the council board and the technical management board.

Deviations from the procedures set out in the present document shall not be made without the authorization of the Chief Executive Officers of ISO or IEC, or the ISO/IEC Joint Technical Advisory Board (JTAB), or the technical management boards for deviations in the respective organizations.


[[_idTextAnchor024]]
=== Establishment of technical committees

[[_idTextAnchor025]]
==== {blank}

Technical committees are established and dissolved by the technical management board.


[[_idTextAnchor026]]
==== {blank}

The technical management board may transform an existing subcommittee into a new technical committee, following consultation with the technical committee concerned.


[[_idTextAnchor027]]
==== {blank}

A proposal for work in a new field of technical activity which appears to require the establishment of a new technical committee may be made in the respective organization by

* a National Body;
* a technical committee or subcommittee;
* a project committee;
* a policy level committee;
* the technical management board;
* the Chief Executive Officer;
* a body responsible for managing a certification system operating under the auspices of the organization;
* another international organization with National Body membership.


[[_idTextAnchor028]]
==== {blank}

The proposal shall be made using the appropriate form (see Annex SJ in the Consolidated ISO Supplement to the ISO/IEC Directives and https://www.iec.ch/standardsdev/resources/docpreparation/forms_templates/[https://www.iec.ch/standardsdev/resources/docpreparation/forms_templates/]), which covers

. the proposer;
. the subject proposed;
. the scope of the work envisaged and the proposed initial programme of work;
. a justification for the proposal;
. if applicable, a survey of similar work undertaken in other bodies;
. any liaisons deemed necessary with other bodies.

For additional informational details to be included in the proposals for new work, see <<_idTextAnchor326>>. The form shall be submitted to the office of the CEO.


[[_idTextAnchor029]]
==== {blank}

The office of the CEO shall ensure that the proposal is properly developed in accordance with ISO and IEC requirements (see <<_idTextAnchor326>>) and provides sufficient information to support informed decision making by National Bodies. The office of the CEO shall also assess the relationship of the proposal to existing work, and may consult interested parties, including the technical management board or committees conducting related existing work. If necessary, an ad hoc group may be established to examine the proposal.

Following its review, the office of the CEO may decide to return the proposal to the proposer for further development before circulation for voting. In this case, the proposer shall make the changes suggested or provide justification for not making the changes. If the proposer does not make the changes and requests that its proposal be circulated for voting as originally presented, the technical management board will decide on appropriate action. This could include blocking the proposal until the changes are made or accepting that it be balloted as received.

In all cases, the office of the CEO may also include comments and recommendations to the proposal form.

For details relating to justification of the proposal, see <<_idTextAnchor326>>.

Proposers are strongly encouraged to conduct informal consultations with other National Bodies in the preparation of proposals.

In some instances, the ISO Technical Management Board may consider it appropriate to carry out an informal exploratory enquiry.

Technical committees are established by the ISO/TMB on a provisional basis. Following the initial meeting of the technical committee, but no later than 18 months, provisionally established technical committees are required to prepare a strategic business plan for review by the ISO/TMB (see Annex SC). The committees are formally established by the ISO/TMB at the time of acceptance of the business plan. This does not preclude the initiation of standardization projects during this 18 month period.


[[_idTextAnchor030]]
==== {blank}

The proposal shall be circulated by the office of the CEO to all National Bodies of the respective organization (ISO or IEC), asking whether or not they

. support the establishment of a new technical committee providing a statement justifying their decision ("justification statement"), and

. intend to participate actively (see <<_idTextAnchor047>>) in the work of the new technical committee.

The proposal shall also be submitted to the other organization (IEC or ISO) for comment and for agreement (see <<_idTextAnchor306>>).

The replies to the proposal shall be made using the appropriate form within 12 weeks after circulation. Regarding <<_idTextAnchor030>> a) above, if no such statement is provided, the positive or negative vote of a National Body will not be registered and considered.

The form for replies to the proposals has been replaced by an electronic balloting system. Replies not using the electronic balloting system will not be counted.


[[_idTextAnchor031]]
==== {blank}

The technical management board evaluates the replies and either

* decides the establishment of a new technical committee, provided that
+
--
. a 2/3 majority of the National Bodies voting are in favour of the proposal, and

. at least 5 National Bodies who voted in favour expressed their intention to participate actively,
--

and allocates the secretariat (see <<_idTextAnchor059>>), or

* assigns the work to an existing technical committee, subject to the same criteria of acceptance.


[[_idTextAnchor032]]
==== {blank}

Technical committees shall be numbered in sequence in the order in which they are established. If a technical committee is dissolved, its number shall not be allocated to another technical committee.


[[_idTextAnchor033]]
==== {blank}

As soon as possible after the decision to establish a new technical committee, the necessary liaisons shall be arranged (see <<_idTextAnchor086>> to <<_idTextAnchor096>>).


[[_idTextAnchor034]]
==== {blank}

A new technical committee shall agree on its title and scope as soon as possible after its establishment, preferably by correspondence.

Agreement of the title and scope of the technical committee requires approval by a 2/3 majority of the P-members voting.

The scope is a statement precisely defining the limits of the work of a technical committee.

The definition of the scope of a technical committee shall begin with the words "Standardization of …" or "Standardization in the field of …" and shall be drafted as concisely as possible.

For recommendations on scopes, see <<_idTextAnchor435>>.

The agreed title and scope shall be submitted by the Chief Executive Officer to the technical management board for approval.


[[_idTextAnchor035]]
==== {blank}

The technical management board or a technical committee may propose a modification of the latter's title and/or scope. The modified wording shall be established by the technical committee for approval by the technical management board.


[[_idTextAnchor036]]
==== {blank}

"Stand-by" -- a technical committee or subcommittee is said to be in a "stand-by" status when it has no tasks on its work programme but retains its title, scope and secretariat so that it can be reactivated should a new task be assigned to it.

The decision to put a committee on stand-by or to reactivate it is taken by the technical management board on a proposal from the committee in question.


[[_idTextAnchor038]]
=== Establishment of subcommittees

[[_idTextAnchor039]]
==== {blank}

Subcommittees are established and dissolved by a 2/3 majority decision of the P-members of the parent committee voting, subject to ratification by the technical management board. A subcommittee may be established only on condition that a National Body has expressed its readiness to undertake the secretariat.


[[_idTextAnchor040]]
==== {blank}

At the time of its establishment, a subcommittee shall comprise at least 5 members of the parent technical committee having expressed their intention to participate actively (see <<_idTextAnchor047>>) in the work of the subcommittee.


[[_idTextAnchor041]]
==== {blank}

Subcommittees of a technical committee shall be designated in sequence in the order in which they are established. If a subcommittee is dissolved, its designation shall not be allocated to another subcommittee, unless the dissolution is part of a complete restructuring of the technical committee.


[[_idTextAnchor042]]
==== {blank}

The title and scope of a subcommittee shall be defined by the parent technical committee and shall be within the defined scope of the parent technical committee.


[[_idTextAnchor043]]
==== {blank}

The secretariat of the parent technical committee shall inform the office of the CEO of the decision to establish a subcommittee, using the appropriate form. The office of the CEO shall submit the form to the technical management board for ratification of the decision.


[[_idTextAnchor044]]
==== {blank}

As soon as possible after ratification of the decision to establish a new subcommittee, any liaisons deemed necessary with other bodies shall be arranged (see <<_idTextAnchor086>> to <<_idTextAnchor096>>).


[[_idTextAnchor046]]
=== Participation in the work of technical committees and subcommittees

It is recognized that member bodies in developing countries often lack the resources to participate in all committees which may be carrying out work which is important for their national economy. Developing country member bodies are therefore invited to establish P-member twinning arrangements with more experienced P-members. Under such arrangements, the lead P-member will ensure that the views of the twinned P-member are communicated to and taken into consideration by the responsible ISO committee. The twinned P-member shall consequently also have the status of P-member (see note) and be registered as a twinned P-member by the Central Secretariat.

NOTE: It is left to the member bodies concerned to determine the most effective way of implementing twinning. This may include for example the P-member sponsoring an expert from the twinned member body to participate in committee meetings or to act as an expert in a working group, or it may involve the P-member seeking the views of the twinned member body on particular agenda items/documents and ensuring that the twinned member body provides its positions in writing to the committee secretariat.

The details of all twinning arrangements shall be notified to the secretariat and chair of the committee concerned, with the committee members and the office of the CEO being informed accordingly to ensure the greatest possible transparency.

A lead P-member shall twin with only one other P-member in any particular committee.

The twinned P-member shall cast its own vote on all issues referred to the committee for vote by correspondence.

For more information on twinnings, see <<_idTextAnchor665>> for the Twinning Policy.

Consistent with the ISO Statutes and Rules of Procedure, correspondent and subscriber members are not eligible for P-memberships. Correspondent members of ISO may register as observers of committees but do not have the right to submit comments.


[[_idTextAnchor047]]
==== {blank}

All National Bodies have the right to participate in the work of technical committees and subcommittees.

In order to achieve maximum efficiency and the necessary discipline in the work, each National Body shall clearly indicate to the office of the CEO, with regard to each technical committee or subcommittee, if it intends

* to participate actively in the work, with an obligation to vote on all questions formally submitted for voting within the technical committee or subcommittee, on new work item proposals, enquiry drafts and final draft International Standards, and to contribute to meetings (*P-members*), or

* to follow the work as an observer, and therefore to receive committee documents and to have the right to submit comments and to attend meetings (*O-members*).

In ISO, National Bodies that choose to be P-members of a committee have the additional obligation to vote on all systematic review ballots under the responsibility of that committee.

A National Body may choose to be neither P-member nor O-member of a given committee, in which case it will have neither the rights nor the obligations indicated above with regard to the work of that committee. Nevertheless, all National Bodies irrespective of their status within a technical committee or subcommittee have the right to vote on enquiry drafts (see <<_idTextAnchor173>>) and on final draft International Standards (see <<_idTextAnchor183>>).

National Bodies have the responsibility to organize their national input in an efficient and timely manner, taking account of all relevant interests at their national level.


[[_idTextAnchor048]]
==== {blank}

Membership of a subcommittee is open to any National Body, regardless of their membership status in the parent technical committee.

Members of a technical committee shall be given the opportunity to notify their intention to become a P- or O-member of a subcommittee at the time of its establishment.

Membership of a technical committee does not imply automatic membership of a subcommittee; National Bodies shall notify their intended status in each subcommittee.


[[_idTextAnchor049]]
==== {blank}

A National Body may, at any time, begin or end membership or change its membership status in any technical committee or subcommittee in IEC by informing the office of the CEO and the secretariat of the committee concerned, and in ISO by direct input via the Global Directory, subject to the requirements of <<_idTextAnchor050>> and <<_idTextAnchor051>>.


[[_idTextAnchor050]]
==== {blank}

A technical committee or subcommittee secretariat shall notify the Chief Executive Officer if a P-member of that technical committee or subcommittee

* has been persistently inactive and has failed to contribute to 2 successive technical committee/subcommittee meetings, either by direct participation or by correspondence and has failed to appoint any experts to the technical work, or

* In IEC:

Has failed to vote on questions formally submitted for voting within the technical committee or subcommittee (see <<_idTextAnchor047>>).

* In ISO:

has failed to vote on over 20 % (and at least 2) of the questions formally submitted for voting on the committee internal balloting (CIB) within the technical committee or subcommittee over one calendar year (see <<_idTextAnchor047>>).

Upon receipt of such a notification, the Chief Executive Officer shall remind the National Body of its obligation to take an active part in the work of the technical committee or subcommittee. In the absence of a satisfactory response to this reminder, and upon persistent continuation of the above articulated shortcomings in required P-member behaviour, the National Body shall without exception automatically have its status changed to that of O-member. A National Body having its status so changed may, after a period of 12 months, indicate to the Chief Executive Officer that it wishes to regain P-membership of the committee, in which case this shall be granted.

NOTE: This clause does not apply to the development of Guides.


[[_idTextAnchor051]]
==== {blank}

If a P-member of a technical committee or subc}ommittee fails to vote on an enquiry draft or final draft International Standard prepared by the respective committee, or on a systematic review ballot for a deliverable under the responsibility of the committee, the Chief Executive Officer shall remind the National Body of its obligation to vote. In the absence of a satisfactory response to this reminder, the National Body shall automatically have its status changed to that of O-member. A National Body having its status so changed may, after a period of 12 months, indicate to the Chief Executive Officer that it wishes to regain P-membership of the committee, in which case this shall be granted.

NOTE: This clause does not apply to the development of Guides.


[[_idTextAnchor053]]
=== Chairs of technical committees and subcommittees

[[_idTextAnchor054]]
==== Appointment

Chairs of technical committees shall be nominated by the secretariat of the technical committee and approved by the technical management board, for a maximum period of 6 years, or for such shorter period as may be appropriate. Extensions are allowed, up to a cumulative maximum of 9 years.

Chairs of subcommittees shall be nominated by the secretariat of the subcommittee and approved by the technical committee for a maximum period of 6 years, or for such shorter period as may be appropriate. Extensions are allowed, up to a cumulative maximum of 9 years. Approval criterion for both appointment and extension is a 2/3 majority vote of the P-members of the technical committee.

Secretariats of technical committees or subcommittees may submit nominations for new chairs up to one year before the end of the term of existing chairs. Chairs appointed one year before shall be designated as the "chair elect" of the committee in question. This is intended to provide the chair elect an opportunity to learn before taking over as chair of a committee.

Where two NSBs agree to share the leadership of an ISO committee, they may jointly identify a chair and jointly agree the way in which they will support that chair. In such cases, the NSB holding the committee secretariat is encouraged to nominate a chair from the other NSB.

For the purposes of transparency, the NSBs involved shall inform the committee members of any cooperative relationships.

The candidates for chairmanships shall have the competencies and attributes listed in Annex SQ _Selection criteria for people leading the technical work_ (see <<_idTextAnchor638>>).


[[_idTextAnchor055]]
==== Responsibilities

The chair of a technical committee is responsible for the overall management of that technical committee, including any subcommittees and working groups.

The chair of a technical committee or subcommittee shall

. act in a purely international capacity, divesting him- or herself of a national position; thus s/he cannot serve concurrently as the delegate of a National Body in his or her own committee;

. guide the secretary of that technical committee or subcommittee in carrying out his or her duty;

. conduct meetings with a view to reaching agreement on committee drafts (see <<_idTextAnchor161>>);

. ensure at meetings that all points of view expressed are adequately summed up so that they are understood by all present;

. ensure at meetings that all decisions are clearly formulated and made available in written form by the secretary for confirmation during the meeting;

. take appropriate decisions at the enquiry stage (see <<_idTextAnchor173>>);

. advise the technical management board on important matters relating to that technical committee via the technical committee secretariat. For this purpose s/he shall receive reports from the chairs of any subcommittees via the subcommittee secretariats;

. ensure that the policy and strategic decisions of the technical management board are implemented in the committee;

. ensure the establishment and ongoing maintenance of a strategic business plan covering the activities of the technical committee and all groups reporting to the technical committee, including all subcommittees;

. ensure the appropriate and consistent implementation and application of the committee's strategic business plan to the activities of the technical committee's or subcommittee's work programme;

. assist in the case of an appeal against a committee decision.

In case of unforeseen unavailability of the chair at a meeting, a session chair may be elected by the participants.

SC chairs shall attend meetings of the parent committee as required and may participate in the discussion, but do not have the right to vote. In exceptional circumstances, if a chair is prevented from attending, he or she shall delegate the secretary (or in ISO and IEC, another representative) to represent the subcommittee. In the case where no representative from the SC can attend, a written report shall be provided.


[[_idTextAnchor056]]
==== Twinned-chairs

Committees are encouraged to establish chair level twinning arrangements where one ISO member body acts as the lead partner and the other ISO member body as the twinned partner (with a limit of one Twinned-chair per committee). Twinned-chairs shall be a P-member (i.e. any P-member whether through a twinning arrangement or not) in the committee concerned. The same rules apply for the appointment and term of chairs and Twinned-chairs. The delineation of responsibilities shall be decided by mutual agreement and recorded in a twinning agreement between the two member bodies nominating the chair and the Twinned-chair, with the committee members and the office of the CEO being informed accordingly.

For more information on twinnings, see <<_idTextAnchor665>> for the Twinning Policy.


[[_idTextAnchor058]]
=== Secretariats of technical committees and subcommittees

[[_idTextAnchor059]]
==== Allocation

The secretariat of a technical committee shall be allocated to a National Body by the technical management board.

The secretariat of a subcommittee shall be allocated to a National Body by the parent technical committee. However, if two or more National Bodies offer to undertake the secretariat of the same subcommittee, the technical management board shall decide on the allocation of the subcommittee secretariat.

Two NSBs may cooperate on the work of an ISO committee secretariat, to support one another on strategic thinking and to share the resource burden of the work.  However, only one of these parties will be considered the official committee secretariat and such arrangements shall not be considered "co-secretariats".

For the purposes of transparency, the NSBs involved shall inform the committee members of any cooperative relationships.

For both technical committees and subcommittees, the secretariat shall be allocated to a National Body only if that National Body

. has indicated its intention to participate actively in the work of that technical committee or subcommittee, and

. has accepted that it will fulfil its responsibilities as secretariat and is in a position to ensure that adequate resources are available for secretariat work (see <<_idTextAnchor378>>).

Once the secretariat of a technical committee or subcommittee has been allocated to a National Body, the latter shall appoint a qualified individual as secretary (see <<_idTextAnchor377>> and <<_idTextAnchor379>>).

Secretaries shall have the competencies and attributes listed in Annex SQ Selection criteria for people leading the technical work (see <<_idTextAnchor644>>).

TC/SC secretariats, at intervals of 5 years, shall normally be subject to reconfirmation by the ISO Technical Management Board.

If, during a year when a particular TC/SC secretariat is due for reconfirmation, TC/SC productivity data show the committee to be experiencing difficulties, this will be drawn to the attention of the ISO Technical Management Board for decision as to whether a reconfirmation enquiry should be conducted. The allocation of those secretariats not notified for detailed examination will be reconfirmed automatically.

A reconfirmation enquiry may also be initiated at any time at the request of the Secretary-General or of a P-member of a committee. Such requests shall be accompanied by a written justification and shall be considered by the ISO Technical Management Board which will decide whether to conduct a reconfirmation enquiry.

The enquiry shall be conducted amongst the P-members of the committee to determine whether the P-members are satisfied that sufficient resources are available to the secretariat and that the performance of the secretariat is satisfactory. Any P-member responding negatively shall be invited to indicate whether it is willing itself to accept the secretariat of the committee.

The enquiry shall be conducted by the ISO Technical Management Board in the case of TC secretariats, and by TC secretariats in the case of SC secretariats. However, in cases where the same member body holds both the TC and SC secretariat, the enquiry shall be conducted by the ISO Technical Management Board.

If there are no negative responses, the secretariat allocation shall be reconfirmed. All negative responses concerning both TC and SC secretariats shall be referred to the ISO Technical Management Board for decision.


[[_idTextAnchor060]]
==== Responsibilities

The National Body to which the secretariat has been allocated shall ensure the provision of technical and administrative services to its respective technical committee or subcommittee.

The secretariat is responsible for monitoring, reporting, and ensuring active progress of the work, and shall use its utmost endeavour to bring this work to an early and satisfactory conclusion. These tasks shall be carried out as far as possible by correspondence.

The secretariat is responsible for ensuring that the ISO/IEC Directives and the decisions of the technical management board are followed.

A secretariat shall act in a purely international capacity, divesting itself of a national point of view.

The secretariat is responsible for the following to be executed in a timely manner:

. Working documents:
.. Preparation of committee drafts, arranging for their distribution and the treatment of the comments received;
.. Preparation of enquiry drafts and text for the circulation of the final draft International Standards or publication of International Standards;
.. Ensuring the equivalence of the English and French texts, if necessary with the assistance of other National Bodies that are able and willing to take responsibility for the language versions concerned. (See also <<_idTextAnchor066>> and the respective Supplements to the ISO/IEC Directives);

. Project management
.. Assisting in the establishment of priorities and target dates for each project;
.. Notifying the names, etc. of all working group and maintenance team convenors and project leaders to the office of the CEO;
.. Proposing proactively the publication of alternative deliverables or cancellation of projects that are running significantly overtime, and/or which appear to lack sufficient support;

. Meetings (see also <<_idTextAnchor242>>), including:
.. Establishment of the agenda and arranging for its distribution;
.. Arranging for the distribution of all documents on the agenda, including reports of working groups, and indicating all other documents which are necessary for discussion during the meeting (see <<_idTextAnchor386>>);
.. Regarding the decisions (also referred to as resolutions) taken in a meeting:
+
--
* ensuring that the decisions endorsing working groups recommendations contain the specific elements being endorsed;
* making the decisions available in writing for confirmation during the meeting (see <<_idTextAnchor386>>); and
* posting the decisions within 48 hours after the meeting in the committee's electronic folder.
--

.. Preparation of the minutes of meetings to be circulated within 4 weeks after the meeting;
.. Preparation of reports to the technical management board (TC secretariat), in the IEC within 4 weeks after the meeting, or to the parent committee (SC secretariat);
.. In case of unforeseen unavailability of the secretary at a meeting (if the Secretariat is unable to provide a replacement), an acting secretary may be appointed by the committee for the meeting.

. Decisions
+
--
The committee secretariat shall ensure that all decisions taken by the committee, whether at a plenary meeting or by correspondence, are documented and traceable through committee resolutions or numbered documents reporting the results of a committee decision;
--

. Advising
+
Providing advice to the chair, project leaders, and convenors on procedures associated with the progression of projects.

In all circumstances, each secretariat shall work in close liaison with the chair of its technical committee or subcommittee.

The secretariat of a technical committee shall maintain close contact with the office of the CEO and with the members of the technical committee regarding its activities, including those of its subcommittees and working groups.

The secretariat of a subcommittee shall maintain close contact with the secretariat of the parent technical committee and as necessary with the office of the CEO. It shall also maintain contact with the members of the subcommittee regarding its activities, including those of its working groups.

The secretariat of a technical committee or subcommittee shall update in conjunction with the office of the CEO the record of the status of the membership of the committee.

The office of the CEO shall also maintain a register of the membership of its working groups.

Member bodies are encouraged to establish twinning arrangements between a secretariat and a twinned secretariat with a limit of one twinned secretariat per committee. The lead partner will hold the secretariat and the twinned partner the twinned secretariat. Twinned secretariats shall be from member bodies holding P-membership in the committee concerned (either directly or via a twinning arrangement). The same rules apply for the allocation of secretariats and twinned secretariats, as well as secretaries and twinned secretaries. The delineation of responsibilities shall be decided by mutual agreement between the member bodies concerned, and recorded in the twinning agreement, with the committee members and the office of the CEO being informed accordingly.

For more information on twinnings, see <<_idTextAnchor665>> for the Twinning Policy.


[[_idTextAnchor061]]
==== Change of secretariat of a technical committee

If a National Body wishes to relinquish the secretariat of a technical committee, the National Body concerned shall immediately inform the Chief Executive Officer, giving a minimum of 12 months' notice. The technical management board decides on the transfer of the secretariat to another National Body.

If the secretariat of a technical committee persistently fails to fulfil its responsibilities as set out in these procedures, the Chief Executive Officer or a National Body may have the matter placed before the technical management board, which may review the allocation of the secretariat with a view to its possible transfer to another National Body.

Concerning the procedure to follow when the lead partner in a twinning arrangement for a technical committee secretariat wishes to relinquish the secretariat, see <<_idTextAnchor677>> Terminating a twinning arrangement of <<_idTextAnchor665>> on the Twinning Policy.


[[_idTextAnchor062]]
==== Change of secretariat of a subcommittee

If a National Body wishes to relinquish the secretariat of a subcommittee, the National Body concerned shall immediately inform the secretariat of the parent technical committee, giving a minimum of 12 months' notice.

If the secretariat of a subcommittee persistently fails to fulfil its responsibilities as set out in these procedures, the Chief Executive Officer or a National Body may have the matter placed before the parent technical committee, which may decide, by majority vote of the P-members, that the secretariat of the subcommittee should be re-allocated.

In either of the above cases an enquiry shall be made by the secretariat of the technical committee to obtain offers from other P-members of the subcommittee for undertaking the secretariat.

If two or more National Bodies offer to undertake the secretariat of the same subcommittee or if, because of the structure of the technical committee, the re-allocation of the secretariat is linked with the re-allocation of the technical committee secretariat, the technical management board decides on the re-allocation of the subcommittee secretariat. If only one offer is received, the parent technical committee itself proceeds with the appointment.

Concerning the procedure to follow when the lead partner in a twinning arrangement for a subcommittee secretariat wishes to relinquish the secretariat, see <<_idTextAnchor677>> Terminating a twinning arrangement of <<_idTextAnchor665>> on the Twinning Policy.


[[_idTextAnchor064]]
=== Project committees

Project committees are established by the technical management board to prepare individual standards not falling within the scope of an existing technical committee.

NOTE: Such standards carry one reference number but may be subdivided into parts.

Procedures for project committees are given in <<_idTextAnchor443>>.

Project committees wishing to be transformed into a technical committee shall follow the process for the establishment of a new technical committee (see <<_idTextAnchor024>>).


[[_idTextAnchor066]]
=== Editing committees

It is recommended that committees establish one or more editing committees for the purpose of updating and editing committee drafts, enquiry drafts and final draft International Standards and for ensuring their conformity to the ISO/IEC Directives, Part 2 (see also <<_idTextAnchor179>>).

Such committees should comprise at least

* one technical expert of English mother tongue and having an adequate knowledge of French;

* one technical expert of French mother tongue and having an adequate knowledge of English;

* the project leader (see <<_idTextAnchor131>>).

The project leader and/or secretary may take direct responsibility for one of the language versions concerned.

Editing committees shall meet when required by the respective technical committee or subcommittee secretariat for the purpose of updating and editing drafts which have been accepted by correspondence for further processing.

Editing committees shall be equipped with means of processing and providing texts electronically (see also <<_idTextAnchor179>>).


[[_idTextAnchor068]]
=== Working groups

[[_idTextAnchor069]]
==== {blank}

Technical committees or subcommittees may establish, by decision of the committee, working groups for specific tasks (see <<_idTextAnchor135>>, <<_idTextAnchor151>> and <<_idTextAnchor173>>). A working group operates by consensus, reports and gives recommendations, if any, to its parent committee through a convenor appointed by the parent committee.

Working group convenors shall be appointed by the committee for up to three-year terms ending at the next plenary session of the parent committee following the term. Such appointments shall be confirmed by the National Body (or liaison organization). The convenor may be reappointed for additional terms of up to three-years. There is no limit to the number of terms.

Responsibility for any changes of convenors rests with the committee and not with the National Body (or liaison organization).

The convenor may be supported by a secretariat, as needed.

The nomination of the working group secretary shall be confirmed by his/her National Body.

Committees are encouraged to establish arrangements between a convenor and a twinned convenor, with a limit of one twinned convenor per working group. The lead partner (convenor) and twinned partner (co-convenor) will be decided by mutual agreement. Convenors and twinned convenors shall be from the P-members in the committee concerned. The same rules apply for the appointment of convenors and twinned convenors.

Note that twinned convenors are only possible through twinning arrangements.

Co-convenors are only possible in Joint Working Groups (JWG) -- see <<_idTextAnchor074>>.

For more information on twinnings, see <<_idTextAnchor665>> for the Twinning Policy.

A working group comprises a restricted number of experts individually appointed by the P-members, A-liaisons of the parent committee and C-liaison organizations, brought together to deal with the specific task allocated to the working group. The experts act in a personal capacity and not as the official representative of the P-member or A-liaison organization (see <<_idTextAnchor096>>) by which they have been appointed with the exception of those appointed by C-liaison organizations (see <<_idTextAnchor096>>). However, it is recommended that they keep close contact with that P-member or organization in order to inform them about the progress of the work and of the various opinions in the working group at the earliest possible stage.

It is recommended that working groups be reasonably limited in size. The technical committee or subcommittee may therefore decide upon the maximum number of experts appointed by each P-member and liaison organizations.

Once the decision to set up a working group has been taken, P-members and A- and C-liaison organizations shall be officially informed in order to appoint expert(s).Working groups shall be numbered in sequence in the order in which they are established.

When a committee has decided to set up a working group, the convenor or acting convenor shall immediately be appointed and shall arrange for the first meeting of the working group to be held within 12 weeks. This information shall be communicated immediately after the committee's decision to the P-members of the committee and A- and C-liaison organizations, with an invitation to appoint experts within 6 weeks. Additional projects may be assigned, where appropriate, to existing working groups.


[[_idTextAnchor070]]
==== {blank}

The composition of the working group is defined in the ISO Global Directory (GD) or in the IEC Expert Management System (EMS) as appropriate. Experts not registered to a working group in the ISO GD or the IEC EMS respectively, shall not participate in its work. Convenors may invite a specific guest to participate in a single meeting and shall notify the guest's National Body of the invitation.

In case of missing stakeholder categories, the Convenor shall inform the committee secretariat, who shall launch another call for experts.


[[_idTextAnchor071]]
==== {blank}

Persistently inactive experts, meaning absence of contributions through attendance to working group meetings or by correspondence shall be removed, by the office of the CEO at the request of the technical committee or sub-committee secretary, from working groups after consultation with the P-member.

In case of lack of experts in the working group to meet the minimum number (as defined in <<_idTextAnchor147>>), the Convenor shall inform the committee secretariat, who shall launch another call for experts.

If the subsequent call for experts fails to recruit the minimum number of experts, the Convenor shall consult with the committee secretariat to decide if the project can or should continue. If the decision is to continue with fewer than the minimum number of experts, the committee secretariat shall request permission from the ISO Technical Management Board to proceed.


[[_idTextAnchor072]]
==== {blank}

On completion of its task(s) -- normally at the end of the enquiry stage (see <<_idTextAnchor173>>) of its last project -- the working group shall be disbanded by decision of the committee, the project leader remaining with consultant status until completion of the publication stage (see <<_idTextAnchor193>>).


[[_idTextAnchor073]]
==== {blank}

Distribution of the internal documents of a working group and of its reports shall be carried out in accordance with procedures described in the respective Supplements of the ISO/IEC Directives.


[[_idTextAnchor074]]
==== {blank}

In special cases a joint working group (JWG) may be established to undertake a specific task in which more than one ISO and/or IEC technical committee or subcommittee is interested. Committees who receive requests to establish JWG shall reply to such requests in a timely manner.

NOTE: For specific rules concerning JWGs between ISO committees and IEC committees, see <<_idTextAnchor306>> in addition to the following.

The decision to establish a joint working group shall be accompanied by mutual agreement between the committees on:

* the committee/organization having the administrative responsibility for the project;

* the convenor of the joint working group, who shall be nominated by a P-member from one of the committees, with the option to appoint a co-convenor from the other committee;

* the membership of the joint working group (membership may be open to all P-members and category A- and C-liaisons that wish to participate which may be limited to an equal number of representatives from each committee, if agreed).

The committee/organization with the administrative responsibility for the project shall:

* record the project in their programme of work;

* conduct the call for experts in all committees that are part of the JWG;

* be responsible for addressing comments (usually referred back to the JWG) and ensure that the comments and votes at all stages of the project are compiled and handled appropriately (see <<_idTextAnchor161>>, <<_idTextAnchor173>> and <<_idTextAnchor183>>) -- all comments are made available to the leadership of the committees;

* prepare drafts for the committee, enquiry and approval stages according to procedures given in <<_idTextAnchor161>>, <<_idTextAnchor173>> and <<_idTextAnchor183>>;

* send all relevant documents (minutes, Working drafts, drafts for the committee, enquiry and approval stages) to the secretariat of the other committee(s) for circulation in their respective committee and/or action;

* be responsible for maintenance of the publication.

Approval criteria are based on the Directives used by the committee with the administrative lead. If the lead committee is a JTC 1 committee, the Consolidated JTC 1 Supplement also applies.

For proposal stage (NP)

* For ISO/ISO JWGs, only one NP ballot is needed -- if a NP has already been launched or approved in one committee, it cannot be balloted again in another TC, but two (2) NP are launched for ISO/IEC JWG [one (1) in each organization].

* It is possible to establish a JWG at a later stage, in which case its administrative lead will be confirmed by the TCs concerned.

* Once the joint work is agreed, the committee with the administrative lead informs ISO/CS or IEC/CO respectively, of its lead and of the committees participating in the work.

* The other TCs launch a call for experts for participation in the JWG.

For preparatory stage (WD)

* The JWG functions like any other WG: consensus is required to advance to CD.

For committee stage (CD)

* The CD is circulated for review and comment by each committee.

* The final CD requires consensus by all committees, as defined in the ISO/IEC Directives, Part 1.

For DIS and FDIS ballots

* National Bodies are requested to consult all national mirror committees involved to define one position. A statement is included on the cover page to draw attention of NSBs.

* For an ISO/IEC JWG, two DIS/FDIS votes are launched, i.e. one in each organization.

The Foreword identifies all committees involved in the development of the deliverable.


[[_idTextAnchor076]]
=== Groups having advisory functions within a committee

[[_idTextAnchor077]]
==== {blank}

A group having advisory functions may be established by a technical committee or subcommittee to assist the chair and secretariat in tasks concerning coordination, planning and steering of the committee's work or other specific tasks of an advisory nature.


[[_idTextAnchor078]]
==== {blank}

A proposal to establish such a group shall include recommendations regarding its constitution and terms of reference, including criteria for membership, bearing in mind the requirement for sufficient representation of affected interests while at the same time limiting its size as far as possible in order to ensure its efficient operation. Members of advisory groups shall be committee officers, individuals nominated by National Bodies and/or, as relevant, by A-liaison organizations. The parent committee shall approve the final constitution and the terms of reference prior to the establishment of and nominations to the advisory group.

For chair's advisory groups, consideration shall be given to the provision of equitable participation.

In order to achieve greater involvement by National Bodies in developing countries in the governance of ISO committees, it is strongly recommended that special provisions be made to allocate places for representatives of developing countries in any advisory groups established by a committee. Those representatives shall be nominated by member bodies holding P-membership in the committee concerned (either directly or via a twinning arrangement).


[[_idTextAnchor079]]
==== {blank}

The tasks allocated to such a group may include the making of proposals relating to the drafting or harmonization of publications (in particular International Standards, Technical Specifications, Publicly Available Specifications and Technical Reports), but shall not include the preparation of such documents.


[[_idTextAnchor080]]
==== {blank}

The results of such a group shall be presented in the form of recommendations to the body that established the group. The recommendations may include proposals for the establishment of a working group (see <<_idTextAnchor068>>) or a joint working group (see <<_idTextAnchor074>>) for the preparation of publications.


[[_idTextAnchor081]]
==== {blank}

The internal documents of a group having advisory functions shall be distributed to its members only, with a copy to the secretariat of the committee concerned and to the office of the CEO.


[[_idTextAnchor082]]
==== {blank}

Such a group shall be disbanded once its specified tasks have been completed and agreed by the parent committee.


[[_idTextAnchor084]]
=== Ad hoc groups

Technical committees or subcommittees may establish ad hoc groups, the purpose of which is to study a precisely defined problem on which the group reports to its parent committee at the same meeting, or at the latest at the next meeting.

The membership of an ad hoc group shall be chosen from the delegates present at the meeting of the parent committee, supplemented, if necessary, by experts appointed by the committee. The parent committee shall also appoint a convenor.

An ad hoc group shall be automatically disbanded at the meeting to which it has presented its report.


[[_idTextAnchor086]]
=== Liaison between technical committees

[[_idTextAnchor087]]
==== {blank}

Within each organization, technical committees and/or subcommittees working in related fields shall establish and maintain liaison. Liaisons shall also be established, where appropriate, with technical committees responsible for basic aspects of standardization (e.g. terminology, graphical symbols). Liaison shall include the exchange of basic documents, including new work item proposals and working drafts.

Committees shall take an official decision on the establishment or removal of an internal liaison. Committees receiving requests for internal liaisons cannot refuse such requests and there is no need for the committee receiving the request to take an official decision confirming its acceptance.


[[_idTextAnchor088]]
==== {blank}

The maintenance of such liaison is the responsibility of the respective technical committee secretariats, which may delegate the task to the secretariats of the subcommittees.


[[_idTextAnchor089]]
==== {blank}

A technical committee or subcommittee may designate a Liaison Representative or Liaison Representatives, to follow the work of another technical committee with which a liaison has been established, or one or several of its subcommittees. The designation of such Liaison Representatives shall be notified to the secretariat of the committee concerned, which shall communicate all relevant documents to the Liaison Representative(s) and to the secretariat of that technical committee or subcommittee. The appointed Liaison Representative shall make progress reports to the secretariat by which s/he has been appointed.


[[_idTextAnchor090]]
==== {blank}

Such Liaison Representatives shall have the right to participate in the meetings of the technical committee or subcommittee whose work they have been designated to follow but shall not have the right to vote. They may contribute to the discussion in meetings, including the submission of written comments, on matters within the competence of their own technical committee and based on feedback that they have collected from their own committee. They may also attend meetings of working groups of the technical committee or subcommittee, but only to contribute the viewpoint of their own technical committee on matters within its competence, and not to otherwise participate in working group activities.


[[_idTextAnchor092]]
=== Liaison between ISO and IEC

[[_idTextAnchor093]]
==== {blank}

Arrangements for adequate liaison between ISO and IEC technical committees and subcommittees are essential. The channel of correspondence for the establishment of liaison between ISO and IEC technical committees and subcommittees is through the offices of the CEOs. As far as the study of new subjects by either organization is concerned, the CEOs seek agreement between the two organizations whenever a new or revised programme of work is contemplated in the one organization which may be of interest to the other, so that the work will go forward without overlap or duplication of effort. (See also <<_idTextAnchor306>>.)


[[_idTextAnchor094]]
==== {blank}

Liaison Representatives designated by ISO or IEC shall have the right to participate in the discussions of the other organization's technical committee or subcommittee whose work they have been designated to follow, and may submit written comments; they shall not have the right to vote.


[[_idTextAnchor096]]
=== Liaison with other organizations

[[_idTextAnchor097]]
==== General requirements applicable to all categories of liaisons

In order to be effective, liaison shall operate in both directions, with suitable reciprocal arrangements.

The desirability of liaison shall be taken into account at an early stage of the work.

The liaison organization shall accept the policy based on the ISO/IEC Directives concerning copyright (see <<_idTextAnchor217>>), whether owned by the liaison organization or by other parties. The statement on copyright policy will be provided to the liaison organization with an invitation to make an explicit statement as to its acceptability. The liaison organization is not entitled to charge a fee for documents submitted.

A liaison organization shall be willing to make a contribution to the technical work of ISO or IEC as appropriate. A liaison organization shall have a sufficient degree of representativity within its defined area of competence within a sector or subsector of the relevant technical or industrial field.

A liaison organization shall agree to ISO/IEC procedures, including IPR (see <<_idTextAnchor217>>).

Liaison organizations shall accept the requirements of <<_idTextAnchor219>> on patent rights.

Technical committees and subcommittees shall review all their liaison arrangements on a regular basis, at least every 2 years, or at every committee meeting.


[[_idTextAnchor098]]
==== Different categories of liaisons (Category A, B and C)

The categories of liaisons are:

* Category A: Organizations that make an effective contribution to the work of the technical committee or subcommittee for questions dealt with by this technical committee or subcommittee. Such organizations are given access to all relevant documentation and are invited to meetings. They may nominate experts to participate in a WG (see <<_idTextAnchor069>>).

* Category B: Organizations that have indicated a wish to be kept informed of the work of the technical committee or subcommittee. Such organizations are given access to reports on the work of a technical committee or subcommittee.

NOTE: Category B is reserved for inter-governmental organizations.

* Category C: Organizations that make a technical contribution to and participate actively in the work of a working group.

The procedure for the establishment of liaisons is:

* The organization wishing to create a liaison shall send an application liaison form to the office of the CEO with copies to the technical committee or subcommittee officers and IEC CO Technical Officer or ISO CS Technical Programme Manager.

* ISO application liaison form is available https://isotc.iso.org/livelink/livelink/Open/19409988[here]

* IEC application liaison form is available https://www.iec.ch/standardsdev/resources/forms_templates/[here]

NOTE: Invariably the organization will have been in contact with the technical committee or subcommittee officers prior to submitting its application and in these cases the technical committee or subcommittee officers should ensure that the organization is aware of their obligations as given in <<_idTextAnchor097>> i.e. copyright, agreeing to ISO/IEC procedures including IPR, and patent rights.

* The Office of the CEO will confirm that the eligibility criteria have been fulfilled and then consult with the National Body where the organization making the application has its headquarters;

* In case of objection from the National Body where the organization making the application has its headquarters, the matter will be referred to the technical management board for decision;

* If there is no objection from the National Body where the organization making the application has its headquarters, the application will be sent to the technical committee or subcommittee secretary with a request to circulate it for vote.


[[_idTextAnchor099]]
==== Acceptance (Category A, B and C liaisons)

Agreement to establish category A, B and C liaisons requires approval of the application by two-thirds of the P-members voting.

Committees are urged to seek out the participation of all parties at the beginning of the development of a work item. Where a request for category C liaison is submitted late in the development stage of a particular work item, the P-members will consider the value that can be added by the organization in question despite its late involvement in the working group.


[[_idTextAnchor100]]
==== Eligibility

[[_idTextAnchor101]]
===== At the technical committee/subcommittee level (Category A and B liaisons)

When an organization applies for a liaison with a technical committee/subcommittee, the office of the CEO will check with the member body in the country in which the organization is located. If the member body does not agree that the eligibility criteria have been met, the matter will be referred to the TMB to define the eligibility.

The office of the CEO will also ensure that the organization meets the following eligibility criteria:

* it is not-for-profit;

* is a legal entity -- the office of the CEO will request a copy of its statutes;

* it is membership-based and open to members worldwide or over a broad region;

* through its activities and membership demonstrates that it has the competence and expertise to contribute to the development of International Standards or the authority to promote their implementation; and

* has a process for stakeholder engagement and consensus decision-making to develop the input it provides (in ISO, see Guidance for ISO liaison organizations -- Engaging stakeholders and building consensus https://www.iso.org/iso/guidance_liaison-organizations.pdf[https://www.iso.org/iso/guidance_liaison-organizations.pdf]).


[[_idTextAnchor102]]
===== At the working group level (Category C liaisons)

When an organization applies for a liaison with a working group, the office of the CEO will check with the member body in the country in which the organization is located and will ensure that the organization meets the following eligibility criteria:

* it is not-for-profit;

* through its activities and membership demonstrates that it has the competence and expertise to contribute to the development of International Standards or the authority to promote their implementation; and

* has a process for stakeholder engagement and consensus decision-making to develop the input it provides (in ISO, see Guidance for ISO liaison organizations -- Engaging stakeholders and building consensus https://www.iso.org/iso/guidance_liaison-organizations.pdf[https://www.iso.org/iso/guidance_liaison-organizations.pdf]).

This can include for example manufacturer associations, commercial associations, industrial consortia, user groups and professional and scientific societies. Liaison organizations shall be multinational (in their objectives and standards development activities) with individual, company or country membership and may be permanent or transient in nature.


[[_idTextAnchor103]]
==== Rights and obligations

[[_idTextAnchor104]]
===== At the technical committee/subcommittee level (Category A and B liaisons)

Technical committees and subcommittees shall seek the full and, if possible, formal backing of the organizations having liaison status for each document in which the latter is interested.

Any comments from liaison organizations should be given the same treatment as comments from member bodies. It should not be assumed that refusal by a liaison organization to provide its full backing is a sustained opposition. Where such objections are considered sustained oppositions, committees are invited to refer to <<_idTextAnchor167>> for further guidance.


[[_idTextAnchor105]]
===== At the working group level (Category C liaisons)

Category C liaison organizations have the right to participate as full members in a working group, maintenance team or project team (see <<_idTextAnchor069>>) but not as project leaders or convenors.

Category C liaison experts act as the official representative of the organization by which they are appointed. They may only attend committee plenary meetings if expressly invited by the committee to attend. If they are invited by the committee to attend, they may only attend as observers.


[[_idTextAnchor106]]
==== Carrying over liaisons when a project committee is converted into a technical committee or a subcommittee

When a project committee is converted to a technical committee or a subcommittee, the new technical committee or subcommittee shall pass a resolution confirming which category A and B liaisons are carried over. Approval of the resolution requires a 2/3 majority of P-members voting.


[[_idTextAnchor107]]
.Liaison categories
[cols="4*",options="header"]
|===
^| Category ^| A ^| B ^| C

h| Purpose | To make an effective contribution to the work of the committee. | To be kept informed of the work of the committee. | To make a technical contribution to drafting standards in a Working Group.

h| Eligibility
a|
* Not for profit
* Legal entity
* Membership based (worldwide or over a broad region)
* Relevant competence and expertise
* Process for stakeholder engagement and consensus decision-making

(See <<_idTextAnchor101>> for full details)

a| *Intergovernmental Organizations only*

* Not for profit
* Legal entity
* Membership based (worldwide or over a broad region)
* Relevant competence and expertise
* Process for stakeholder engagement and consensus decision-making

(See <<_idTextAnchor101>> for full details)

a|
* Not for profit
* Relevant competence and expertise
* Process for stakeholder engagement and consensus decision-making

(See <<_idTextAnchor102>> for full details)

h| Level | TC/SC | TC/SC | Working Group
h| Participation | Participate in TC/SC meetings, access to documents, may appoint experts to WGs and these experts may serve as convenors or Project Leaders. | To be kept informed of the work only (access to documents). | Full participation as a member of the WG (but cannot be convenor or Project Leader).
h| Rights and obligations | No voting rights, but can comment (comments are given the same treatment as comments from member bodies).Can propose new work items (see <<_idTextAnchor144>>). | No voting rights, but can comment (comments are given the same treatment as comments from member bodies).Cannot propose new work items. | Experts can attend committee meetings if expressly invited by the committee, but only as observers.Cannot propose new work items.
|===