

[[_idTextAnchor109]]
== Development of International Standards

[[_idTextAnchor111]]
=== The project approach

[[_idTextAnchor112]]
==== General

The primary duty of a technical committee or subcommittee is the development and maintenance of International Standards. However, committees are also strongly encouraged to consider publication of intermediate deliverables as described in <<_idTextAnchor224>>.

International Standards shall be developed on the basis of a project approach as described below.


[[_idTextAnchor113]]
==== Strategic business plan

Annex SC describes the objectives of strategic business plans, and the procedure that applies to their development and approval.

Each technical committee shall prepare a strategic business plan for its own specific field of activity,

. taking into account the business environment in which it is developing its work programme;
. indicating those areas of the work programme which are expanding, those which have been completed, and those nearing completion or in steady progress, and those which have not progressed and should be cancelled (see also <<_idTextAnchor132>>);
. evaluating revision work needed (see also the respective Supplements to the ISO/IEC Directives);
. giving a prospective view on emerging needs.

The strategic business plan shall be formally agreed upon by the technical committee and be included in its report for review and approval by the technical management board on a regular basis.

NOTE: In ISO, the TMB approves the first strategic business plan only and committees are responsible for ensuring regular updates and revisions.


[[_idTextAnchor114]]
==== Project stages

[[_idTextAnchor115]] 
===== {blank}

<<_idTextAnchor116>> shows the sequence of project stages through which the technical work is developed, and gives the name of the document associated with each project stage. The development of Technical Specifications, Technical Reports and Publicly Available Specifications is described in <<_idTextAnchor224>>.


[[_idTextAnchor116]]
.Project stages and associated documents
[cols="3*]
|===
.2+^.^h| Project stage 2+^.^h| Associated document
^.^h| Name ^.^h| Abbreviation

h| Preliminary stage | Preliminary work item footnote:116a[These stages may be omitted, as described in <<_idTextAnchor396>>.] | PWI
h| Proposal stage | New work item proposal footnote:116a[] | NP
h| Preparatory stage | Working draft(s) footnote:116a[] | WD
h| Committee stage | Committee draft(s) footnote:116a[] | CD
h| Enquiry stage | Enquiry draft footnote:[Draft International Standard in ISO, committee draft for vote in IEC.] a| ISO/DIS +
 IEC/CDV
h| Approval stage | final draft International Standard footnote:[May be omitted (see <<_idTextAnchor177>>).] | FDIS
h| Publication stage | International Standard | ISO, IEC or ISO/IEC
|===


[[_idTextAnchor117]]
===== {blank}

<<_idTextAnchor397>> illustrates the steps leading to publication of an International Standard.


[[_idTextAnchor118]]
===== {blank}

The ISO and IEC Supplements to the ISO/IEC Directives give a matrix presentation of the project stages, with a numerical designation of associated sub-stages.

To facilitate the monitoring of project development, ISO has adopted a systematic approach to project management, based on subdivision of projects into stages and substages.

The project management system is associated with a detailed project tracking system that is a subset of the Harmonized Stage Code system _ISO Guide 69:1999 Harmonized Stage Code system (Edition 2) -- Principles and guidelines for use_. Annex SD gives a matrix presentation of this project tracking system, with the numerical designation of associated sub-stages. A project is registered in the ISO Central Secretariat database as having reached each particular step when the action or decision indicated at that point has been taken and ISO Central Secretariat has been duly informed.


[[_idTextAnchor119]]
==== Project description and acceptance

A project is any work intended to lead to the issue of a new, amended or revised International Standard. A project may subsequently be subdivided (see also <<_idTextAnchor124>>).

A project shall be undertaken only if a proposal has been accepted in accordance with the relevant procedures (see <<_idTextAnchor142>> for proposals for new work items, and the respective Supplements to the ISO/IEC Directives for review and maintenance of existing International Standards).


[[_idTextAnchor120]]
==== Programme of work

[[_idTextAnchor121]]
===== {blank}

The programme of work of a technical committee or subcommittee comprises all projects allocated to that technical committee or subcommittee, including maintenance of published standards.


[[_idTextAnchor122]]
===== {blank}

In establishing its programme of work, each technical committee or subcommittee shall consider sectoral planning requirements as well as requests for International Standards initiated by sources outside the technical committee, i.e. other technical committees, advisory groups of the technical management board, policy level committees and organizations outside ISO and IEC. (See also <<_idTextAnchor113>>.)


[[_idTextAnchor123]]
===== {blank}

Projects shall be within the agreed scope of the technical committee. Their selection shall be subject to close scrutiny in accordance with the policy objectives and resources of ISO and IEC. (See also <<_idTextAnchor326>>.)


[[_idTextAnchor124]]
===== {blank}

Each project in the programme of work shall be given a number (see IEC Supplements to the ISO/IEC Directives for document numbering at the IEC) and shall be retained in the programme of work under that number until the work on that project is completed or its cancellation has been agreed upon. The technical committee or subcommittee may subdivide a number if it is subsequently found necessary to subdivide the project itself. The subdivisions of the work shall lie fully within the scope of the original project; otherwise, a new work item proposal shall be made.


[[_idTextAnchor125]]
===== {blank}

The programme of work shall indicate, if appropriate, the subcommittee and/or working group to which each project is allocated.


[[_idTextAnchor126]]
===== {blank}

The agreed programme of work of a new technical committee shall be submitted to the technical management board for approval.


[[_idTextAnchor127]]
==== Target dates

The technical committee or subcommittee shall establish, for each project on its programme of work, target dates for the completion of each of the following steps:

* completion of the first working draft (in the event that only an outline of a working document has been provided by the proposer of the new work item proposal -- see <<_idTextAnchor142>>);
* circulation of the first committee draft;
* circulation of the enquiry draft;
* circulation of the final draft International Standard (in agreement with the office of the CEO);
* publication of the International Standard (in agreement with the office of the CEO).

NOTE: Committees may decide to skip the committee draft (CD) stage in accordance with Annex SS. The final draft International Standard (FDIS) shall be skipped if no technical changes are to be included in accordance with <<_idTextAnchor177>>.

These target dates shall correspond to the shortest possible development times to produce International Standards rapidly and shall be reported to the office of the CEO, which distributes the information to all National Bodies. For establishment of target dates, see the respective Supplements to the ISO/IEC Directives.

In establishing target dates, the relationships between projects shall be taken into account. Priority shall be given to those projects intended to lead to International Standards upon which other International Standards will depend for their implementation. The highest priority shall be given to those projects having a significant effect on international trade and recognized as such by the technical management board.

The technical management board may also instruct the secretariat of the technical committee or subcommittee concerned to submit the latest available draft to the office of the CEO for publication as a Technical Specification (see <<_idTextAnchor226>>).

All target dates shall be kept under continuous review and amended as necessary, and shall be clearly indicated in the programme of work. Revised target dates shall be notified to the technical management board. The technical management board will cancel all work items which have been on the work programme for more than 5 years and have not reached the approval stage (see <<_idTextAnchor183>>).


[[_idTextAnchor128]]
===== General

When a proposed new project is approved (whether for a new deliverable or for the revision of an existing deliverable), when submitting the results to the ISO Central Secretariat the committee secretariat shall also indicate the selected standards development track, as follows:

*SDT 18 standards development track -- 18 months to publication*

*SDT 24 standards development track -- 24 months to publication*

*SDT 36 standards development track -- 36 months to publication*

The following limit dates are automatically assigned to all new projects:

* DIS registered limit date (stage 40.00): 12 months before the end of the selected standards development track.
* Publication limit date (stage 60.60): Maximum timeframe of the selected standards development track.

NOTE: Projects using the 18-month development track shall be eligible for the 'Direct publication process' offered by ISO/CS if they successfully complete the DIS ballot within 13 months of the project's registration. This process reduces publication processing time by approximately one third.

Committee secretariats are reminded to perform risk assessments during project planning in order to identify potential problems in advance and set the target dates accordingly. The target dates shall be kept under continuous review by committee secretariats which shall ensure that they are reviewed and either confirmed or revised at each committee meeting. Such reviews shall also seek to confirm that projects are still market relevant and in cases in which they are found to be no longer required, or if the likely completion date is going to be too late, thus causing market players to adopt an alternative solution, the projects shall be cancelled or transformed into another deliverable (see <<_idTextAnchor129>>).

NOTE: Time spent on round-robin testing during the development of a standard shall not be counted in the overall development time. The standards development track is paused on request from the secretariat to ISO/CS during round-robin testing.


[[_idTextAnchor129]]
===== Automatic cancellation of projects (and their reinstatement)

If the limit date for DIS (stage 40.00) or publication (stage 60.60) is exceeded, the committee shall decide within 6 months on one of the following actions:

. for projects at the preparatory or committee stages: submission of a DIS -- if the technical content is acceptable and mature;
. for projects at the enquiry stage: submission of a second DIS or FDIS -- if the technical content is acceptable and mature;
. publication of a TS -- if the technical content is acceptable but unlikely sufficiently mature for a future International Standard;
. publication of a PAS -- if the technical content is acceptable but unlikely sufficiently mature for a future International Standard or a TS;
. submission of a request for extension to the ISO/TMB -- if no consensus can be reached but there is strong interest from stakeholders to continue -- a committee may be granted one extension of up to 9 months for the total project duration but the publication of intermediary deliverables (such as PAS and TS) is recommended;
. cancellation of the work item -- if the committee is unable to find a solution.

If, at the end of the six month period, none of the above actions has been taken, the project shall be automatically cancelled by the ISO Central Secretariat. Such projects may only be reinstated with the approval of the ISO Technical Management Board.


[[_idTextAnchor130]]
==== Project management

The secretariat of the technical committee or subcommittee is responsible for the management of all projects in the programme of work of that technical committee or subcommittee, including monitoring of their progress against the agreed target dates.

If target dates (see <<_idTextAnchor127>>) are not met and there is insufficient support for the work (that is, the acceptance requirements for new work given in <<_idTextAnchor147>> are no longer met), the committee responsible shall cancel the work item.


[[_idTextAnchor131]]
==== Project leader

For the development of each project, a project leader (the WG convenor, a designated expert or, if appropriate, the secretary) shall be appointed by the technical committee or subcommittee, taking into account the project leader nomination made by the proposer of the new work item proposal (see <<_idTextAnchor146>>). It shall be ascertained that the project leader will have access to appropriate resources for carrying out the development work. The project leader shall act in a purely international capacity, divesting him- or herself of a national point of view. The project leader should be prepared to act as consultant, when required, regarding technical matters arising at the proposal stage through to the publication stage (see <<_idTextAnchor161>> to <<_idTextAnchor193>>).

The secretariat shall communicate the name and address of the project leader, with identification of the project concerned, to the office of the CEO.


[[_idTextAnchor132]]
==== Progress control

Periodical progress reports to the technical committee shall be made by its subcommittees and working groups (see also ISO and IEC Supplements to the ISO/IEC Directives). Meetings between their secretariats will assist in controlling the progress.

The office of the CEO shall monitor the progress of all work and shall report periodically to the technical management board. For this purpose, the office of the CEO shall receive copies of documents as indicated in the ISO and IEC Supplements to the ISO/IEC Directives.

To enable ISO Central Secretariat to monitor the progress of all work and to report periodically to the ISO Technical Management Board, the committee secretariat shall ensure that the ISO Central Secretariat is notified each time a new document is distributed.


[[_idTextAnchor133]]
==== Responsibility for keeping records

The responsibility for keeping records concerning committee work and the background to the publication of International Standards and other ISO deliverables is divided between committee secretariats and the ISO Central Secretariat. The maintenance of such records is of particular importance in the context of changes of secretariat responsibility from one member body to another. It is also important that information on key decisions and important correspondence pertaining to the preparation of International Standards and other ISO deliverables should be readily retrievable in the event of any dispute arising out of the provenance of the technical content of the publications.

The secretariats of committees shall establish and maintain records of all official transactions concerning their committees, in particular reference copies of approved minutes of meetings and resolutions. Copies of working documents, results of ballots etc. shall be kept at least until such time as the publications to which they refer have been revised or have completed their next systematic review, but in any case for a minimum of five years after the publication of the related International Standards or other ISO deliverable.

The ISO Central Secretariat shall keep reference copies of all International Standards and other ISO deliverables, including withdrawn editions, and shall keep up-to-date records of member body votes in respect of these publications. Copies of draft International Standards (DIS) and of final draft International Standards (FDIS), including associated reports of voting, and final proofs shall be kept at least until such time as the publications to which they refer have been revised or have completed their next systematic review, but in any case for a minimum of five years after publication.


[[_idTextAnchor135]]
=== Preliminary stage

[[_idTextAnchor136]]
==== {blank}

Technical committees or subcommittees may introduce into their work programmes, by a simple majority vote of their P-members, preliminary work items (for example, corresponding to subjects dealing with emerging technologies), which are not yet sufficiently mature for processing to further stages and for which no target dates can be established.

Such items may include, for example, those listed in the strategic business plan, particularly as given under <<_idTextAnchor113>> d) giving a prospective view on emerging needs.


[[_idTextAnchor137]]
==== {blank}

All preliminary work items shall be registered into the programme of work.


[[_idTextAnchor138]]
==== {blank}

All preliminary work items shall be subject to regular review by the committee. The committee shall evaluate the market relevance and resources required for all such items.

All preliminary work items that have not progressed to the proposal stage in the IEC by the expiration date given by the TC/SC and in ISO within 3 years will be automatically cancelled.


[[_idTextAnchor139]]
==== {blank}

This stage can be used for the elaboration of a new work item proposal (see <<_idTextAnchor142>>) and the development of an initial draft.


[[_idTextAnchor140]]
==== {blank}

Before progressing to the preparatory stage, all such items shall be subject to approval in accordance with the procedures described in <<_idTextAnchor142>>.


[[_idTextAnchor142]]
=== Proposal stage

In the case of proposals to prepare management system deliverables, see Annex SL.


[[_idTextAnchor143]]
==== {blank}

A new work item proposal (NP) is a proposal for:

* a new standard;
* a new part of an existing standard;
* a Technical Specification (see <<_idTextAnchor226>>) or a Publicly Available Specification (see <<_idTextAnchor231>>).

The NP stage (<<_idTextAnchor142>>) is not required for:

* the revision or amendment of an existing International Standard,
* the revision of an existing TS or a PAS (if within its 6-year lifespan),
* the conversion of a TS or PAS to an IS.

However, the committee shall pass a resolution containing the following elements: 1) target dates, 2) confirmation that the scope will not be expanded, and 3) the convenor or project leader. The committee shall also launch a call for experts (Form 4 is not required).

For the conversion of a TS or a PAS to an IS, a two-thirds majority resolution is required.

If the revision or the amendment results in an expanded scope, <<_idTextAnchor142>> applies (NP ballot shall be initiated and Form 4 is required).


[[_idTextAnchor144]]
==== {blank}

A new work item proposal within the scope of an existing technical committee or subcommittee may be made in the respective organization by

* a National Body;
* the secretariat of that technical committee or subcommittee;
* another technical committee or subcommittee;
* an organization in category A liaison;
* the technical management board or one of its advisory groups;
* the Chief Executive Officer.


[[_idTextAnchor145]]
==== {blank}

Where both an ISO and an IEC technical committee are concerned, the Chief Executive Officers shall arrange for the necessary coordination. (See also <<_idTextAnchor306>>.)


[[_idTextAnchor146]]
==== {blank}

Each new work item proposal shall be presented using the appropriate form, and shall be fully justified and properly documented (see <<_idTextAnchor326>>).

The proposers of the new work item proposal shall

* make every effort to provide a first working draft for discussion, or shall at least provide an outline of such a working draft;

* nominate a project leader;

* discuss the proposal with the committee leadership prior to submitting the appropriate form, in order to decide on an appropriate development track (based on market needs) and draft a project plan including key milestones and the proposed date of the first meeting.

The form shall be submitted to the office of the CEO or to the secretariat of the relevant committee for proposals within the scope of an existing committee.

The office of the CEO or the relevant committee chair and secretariat shall ensure that the proposal is properly developed in accordance with ISO and IEC requirements (see <<_idTextAnchor326>>) and provides sufficient information to support informed decision making by National Bodies.

The office of the CEO or the relevant committee chair and secretariat shall also assess the relationship of the proposal to existing work, and may consult interested parties, including the technical management board or committees conducting related existing work. If necessary, an ad hoc group may be established to examine the proposal. Any review of proposals should not exceed 2 weeks.

In all cases, the office of the CEO or the relevant committee chair and secretariat may also add comments and recommendations to the proposal form.

See <<_idTextAnchor443>> for new work item proposals for project committees.

Copies of the completed form shall be circulated to the members of the technical committee or subcommittee for P-member ballot and to the O-members and liaison members for information.

The proposed date of availability of the publication shall be indicated on the form.

A decision upon a new work item proposal shall be taken by correspondence.

Votes shall be returned within 12 weeks.

The committee may decide on a case-by-case basis by way of a resolution to shorten the voting period for new work item proposals to 8 weeks.

When completing the ballot form, National Bodies shall provide a statement justifying their decision for negative votes ("justification statement"). If no such statement is provided, the negative vote of a National Body will not be registered and considered.


[[_idTextAnchor147]]
==== {blank}

Acceptance requires

. approval of the work item by a 2/3 majority of the P-members of the technical committees or subcommittees voting -- abstentions are excluded when the votes are counted; and

. a commitment to participate actively in the development of the project, i.e. to make an effective contribution at the preparatory stage, by nominating technical experts and by commenting on working drafts, by at least 4 P-members in committees with 16 or fewer P-members, and at least 5 P-members in committees with 17 or more P-members; only P-members having also approved the inclusion of the work item in the programme of work [see a)] will be taken into account when making this tally. If experts are not nominated on the form accompanying an approval vote, then the National Body's commitment to active participation will not be registered and considered when determining if the approval criteria have been met on this ballot.

If in the context of an NP, a member body does not provide a clear justification statement for why it voted "no", the committee secretariat should go back to the member body and give it two (2) weeks to provide an explanation.

If the member body does not provide a response within that 2-week period, the vote will not be counted in the result.

Secretariats shall not make value judgments about the justification and shall ask the member body in case of doubt.

If member bodies do not name an expert in the Form, they have two (2) weeks following the result of the vote to name their expert. If this delay is not respected, the member body's participation will not be counted, thereby affecting the approval requirement for b) above.

Individual committees may increase this minimum requirement of nominated experts.

In cases, where it can be documented that the industry and/or technical knowledge exists only with a very small number of P-members, then the committee may request permission from the technical management board to proceed with fewer than 4 or 5 nominated technical experts.


[[_idTextAnchor148]]
==== {blank}

Once a new work item proposal is accepted, it shall be registered in the programme of work of the relevant technical committee or subcommittee as a new project with the appropriate priority. The agreed target dates (see <<_idTextAnchor127>>) shall be indicated on the appropriate form.

The voting results will be reported to the ISO Central Secretariat (using Form 6) or the IEC Central Office (using Form RVN) within 4 weeks after the close of the ballot.


[[_idTextAnchor149]]
==== {blank}

The inclusion of the project in the programme of work concludes the proposal stage.


[[_idTextAnchor151]]
=== Preparatory stage

[[_idTextAnchor152]]
==== {blank}

The preparatory stage covers the preparation of a working draft (WD) conforming to the ISO/IEC Directives, Part 2.


[[_idTextAnchor153]]
==== {blank}

When a new project is accepted the project leader shall work with the experts nominated by the P-members during the approval [see <<_idTextAnchor147>> a)].


[[_idTextAnchor154]]
==== {blank}

The secretariat may propose to the technical committee or subcommittee, either at a meeting or by correspondence, to create a working group the convenor of which will normally be the project leader.

Such a working group shall be set up by the technical committee or subcommittee, which shall define the task(s) and set the target date(s) for submission of draft(s) to the technical committee or subcommittee (see also <<_idTextAnchor068>>). The working group convenor shall ensure that the work undertaken remains within the scope of the balloted work item.


[[_idTextAnchor155]]
==== {blank}

In responding to the proposal to set up a working group those P-members having agreed to participate actively [see <<_idTextAnchor147>> a)] shall each confirm their technical expert(s). Other P-members or A- or C- liaison organizations may also nominate expert(s).


[[_idTextAnchor156]]
==== {blank}

The project leader is responsible for the development of the project and will normally convene and chair any meetings of the working group. S/he may invite a member of the working group to act as its secretary.


[[_idTextAnchor157]]
==== {blank}

Every possible effort shall be made to prepare both a French and an English version of the text in order to avoid delays in the later stages of the development of the project.

If a trilingual (English -- French -- Russian) standard is to be prepared, this provision should include the Russian version.


[[_idTextAnchor158]]
==== {blank}

For time limits relating to this stage, see <<_idTextAnchor127>>.


[[_idTextAnchor159]]
==== {blank}

The preparatory stage ends when a working draft is available for circulation to the members of the technical committee or subcommittee as a first committee draft (CD) and is registered by the office of the CEO. The committee may also decide to publish the final working draft as a PAS (see <<_idTextAnchor231>>) to respond particular market needs.

If the committee has opted to skip the CD (see <<_idTextAnchor161>>), the preparatory stage ends when the enquiry draft (DIS) is available for circulation (see <<_idTextAnchor173>>).


[[_idTextAnchor161]]
=== Committee stage

[[_idTextAnchor162]]
==== {blank}

The committee stage is the principal stage at which comments from National Bodies are taken into consideration, with a view to reaching consensus on the technical content. National Bodies shall therefore carefully study the texts of committee drafts and submit all pertinent comments at this stage.

Committees may decide to skip the CD stage in accordance with Annex SS.

Any graphical symbol shall be submitted to the relevant ISO committee responsible for the registration of graphical symbols (see Annex SH).


[[_idTextAnchor163]]
==== {blank}

As soon as it is available, a committee draft shall be circulated to all P-members and O-members of the technical committee or subcommittee for consideration, with a clear indication of the latest date for submission of replies.

A period of 8, 12 or 16 weeks as agreed by the technical committee or subcommittee shall be available for National Bodies to comment.

The default for CD circulation is 8 weeks.

Comments shall be sent for preparation of the compilation of comments, in accordance with the instructions given.

National Bodies shall fully brief their delegates on the national position before meetings.


[[_idTextAnchor164]]
==== {blank}

No more than 4 weeks after the closing date for submission of replies, the secretariat shall prepare the compilation of comments and arrange for its circulation to all P-members and O-members of the technical committee or subcommittee. When preparing this compilation, the secretariat shall indicate its proposal, made in consultation with the chair of the technical committee or subcommittee and, if necessary, the project leader, for proceeding with the project, either

. to discuss the committee draft and comments at the next meeting, or
. [[item_164-b]]to circulate a revised committee draft for consideration, or
. [[item_164-c]]to register the committee draft for the enquiry stage (see <<_idTextAnchor173>>).

In the case of <<item_164-b>> and <<item_164-c>>, the secretariat shall indicate in the compilation of comments the action taken on each of the comments received. This shall be made available to all P-members, if necessary by the circulation of a revised compilation of comments, no later than in parallel with the submission of a revised CD for consideration by the committee (case <<item_164-b>>) or simultaneously with the submission of the finalized version of the draft to the office of the CEO for registration for the enquiry stage (case <<item_164-c>>).

Committees are required to respond to all comments received.

If, within 8 weeks from the date of dispatch, 2 or more P-members disagree with proposal <<item_164-b>> or <<item_164-c>> of the secretariat, the committee draft shall be discussed at a meeting (see <<_idTextAnchor254>>).


[[_idTextAnchor165]]
==== {blank}

If a committee draft is considered at a meeting but agreement on it is not reached on that occasion, a further committee draft incorporating decisions taken at the meeting shall be distributed within 12 weeks for consideration. A period of 8, 12 or 16 weeks as agreed by the technical committee or subcommittee shall be available to National Bodies to comment on the draft and on any subsequent versions.


[[_idTextAnchor166]]
==== {blank}

Consideration of successive drafts shall continue until consensus of the P-members of the technical committee or subcommittee has been obtained or a decision to abandon or defer the project has been made.


[[_idTextAnchor167]]
==== {blank}

The decision to circulate an enquiry draft (see <<_idTextAnchor174>>) shall be taken on the basis of the consensus principle.

It is the responsibility of the chair of the technical committee or subcommittee, in consultation with the secretary of his/her committee and, if necessary, the project leader, to judge whether there is sufficient support bearing in mind the definition of consensus given in ISO/IEC Guide 2:2004.

"consensus: General agreement, characterized by the absence of sustained opposition to substantial issues by any important part of the concerned interests and by a process that involves seeking to take into account the views of all parties concerned and to reconcile any conflicting arguments.

NOTE     Consensus need not imply unanimity."

The following applies to the definition of consensus:

In the process of reaching consensus, many different points of views will be expressed and addressed as the document evolves. However, "sustained oppositions" are views expressed at minuted meetings of committee, working group (WG) or other groups (e.g. task forces, advisory groups, etc.) and which are maintained by an important part of the concerned interest and which are incompatible with the committee consensus. The notion of "concerned interest(s)" will vary depending on the dynamics of the committee and shall therefore be determined by the committee leadership on a case by case basis. The concept of sustained opposition is not applicable in the context of member body votes on CD, DIS or FDIS since these are subject to the applicable voting rules.

Those expressing sustained oppositions have a right to be heard and the following approach is recommended when a sustained opposition is declared:

* The leadership shall first assess whether the opposition can be considered a "sustained opposition", i.e. whether it has been sustained by an important part of the concerned interest. If this is not the case, the leadership will register the opposition (i.e. in the minutes, records, etc.) and continue to lead the work on the document.

* If the leadership determines that there is a sustained opposition, it is required to try and resolve it in good faith. However, a sustained opposition is not akin to a right to veto. The obligation to address the sustained oppositions does not imply an obligation to successfully resolve them.

The responsibility for assessing whether or not consensus has been reached rests entirely with the leadership. This includes assessing whether there is sustained opposition or whether any sustained opposition can be resolved without compromising the existing level of consensus on the rest of the document. In such cases, the leadership will register the opposition and continue the work.

Those parties with sustained oppositions may avail themselves of appeals mechanisms as detailed in <<_idTextAnchor268>>.

In case of doubt concerning consensus, approval by a two-thirds majority of the P-members of the technical committee or subcommittee voting may be deemed to be sufficient for the committee draft to be accepted for registration as an enquiry draft; however every attempt shall be made to resolve negative votes.

Abstentions are excluded when the votes are counted, as well as negative votes not accompanied by technical reasons.

The secretariat of the technical committee or subcommittee responsible for the committee draft shall ensure that the enquiry draft fully embodies decisions taken either at meetings or by correspondence.


[[_idTextAnchor168]]
==== {blank}

When consensus has been reached in a technical committee or subcommittee, its secretariat shall submit the finalized version of the draft in electronic form suitable for distribution to the national members for enquiry (<<_idTextAnchor174>>), to the office of the CEO (with a copy to the technical committee secretariat in the case of a subcommittee) within a maximum of 16 weeks.

The secretariat shall submit the proposed draft International Standard (DIS) to the ISO Central Secretariat in electronic format together with a completed explanatory report (ISO form 8A) and the compilation of comments and actions taken in response to comments on the final CD.


[[_idTextAnchor169]]
==== {blank}

For time limits relating to this stage, see <<_idTextAnchor127>>.


[[_idTextAnchor170]]
==== {blank}

The committee stage ends when all technical issues have been resolved and a committee draft is accepted for circulation as an enquiry draft and is registered by the office of the CEO. Texts that do not conform to the ISO/IEC Directives, Part 2 shall be returned to the secretariat with a request for correction before they are registered.


[[_idTextAnchor171]]
==== {blank}

If the technical issues cannot all be resolved within the appropriate time limits, technical committees and subcommittees may wish to consider publishing an intermediate deliverable in the form of a Technical Specification (see <<_idTextAnchor226>>) pending agreement on an International Standard.


[[_idTextAnchor173]]
=== Enquiry stage

[[_idTextAnchor174]]
==== {blank}

At the enquiry stage, the enquiry draft (DIS in ISO, CDV in IEC) shall be circulated by the office of the CEO to all National Bodies for a 12-week vote.

For policy on the use of languages, see <<_idTextAnchor381>>.

National Bodies shall be advised of the date by which completed ballots are to be received by the office of the CEO.

At the end of the voting period, the Chief Executive Officer shall send within 4 weeks to the chair and secretariat of the technical committee or subcommittee the results of the voting together with any comments received, for further speedy action.


[[_idTextAnchor175]]
==== {blank}

Votes submitted by National Bodies shall be explicit: positive, negative, or abstention.

A positive vote may be accompanied by editorial or technical comments, on the understanding that the secretary, in consultation with the chair of the technical committee or subcommittee and project leader, will decide how to deal with them.

If a National Body finds an enquiry draft unacceptable, it shall vote negatively and state the technical reasons. It may indicate that the acceptance of specified technical modifications will change its negative vote to one of approval, but it shall not cast an affirmative vote which is conditional on the acceptance of modifications.

In the case where a member body has voted negatively without submitting a justification, the vote will not be counted.

In the case where a Member Body has voted negatively and has submitted comments that are not clearly of a technical nature, the committee secretary shall contact the ISO/CS Technical Programme Manager within 2 weeks of the ballot closure.


[[_idTextAnchor176]]
==== {blank}

An enquiry draft is approved if

. a two-thirds majority of the votes cast by the P-members of the technical committee or subcommittee are in favour, and

. not more than one-quarter of the total number of votes cast are negative.

Abstentions are excluded when the votes are counted, as well as negative votes not accompanied by technical reasons.

Comments received after the normal voting period are submitted to the technical committee or subcommittee secretariat for consideration at the time of the next review of the International Standard.


[[_idTextAnchor177]]
==== {blank}

On receipt of the results of the voting and any comments, the chair of the technical committee or subcommittee, in cooperation with its secretariat and the project leader, and in consultation with the office of the CEO, shall take one of the following courses of action:

. when the approval criteria of <<_idTextAnchor176>> are met and no technical changes are to be included, to proceed directly to publication (see <<_idTextAnchor193>>);
. when the approval criteria of <<_idTextAnchor176>> are met, but technical changes are to be included, to register the enquiry draft, as modified, as a final draft international standard;
. when the approval criteria of <<_idTextAnchor176>> are not met:
.. to circulate a revised enquiry draft for voting (see <<_idTextAnchor174>>), or
+
NOTE: A revised enquiry draft will be circulated for a voting period of 8 weeks, which may be extended up to 12 weeks at the request of one or more P-members of the committee concerned.

.. to circulate a revised committee draft for comments, or
.. to discuss the enquiry draft and comments at the next meeting.


[[_idTextAnchor178]]
==== {blank}

Not later than 12 weeks after the end of the voting period, a full report shall be prepared by the secretariat of the technical committee or subcommittee and circulated by the office of the CEO to the National Bodies. The report shall

. show the result of the voting;
. state the decision of the chair of the technical committee or subcommittee;
. reproduce the text of the comments received; and
. include the observations of the secretariat of the technical committee or subcommittee on each of the comments submitted.

Every attempt shall be made to resolve negative votes.

If, within 8 weeks from the date of dispatch, two or more P-members disagree with decision <<_idTextAnchor177>> c)1) or <<_idTextAnchor177>> c)2) of the chair, the draft shall be discussed at a meeting (see <<_idTextAnchor254>>).

Committees are required to respond to all comments received.


[[_idTextAnchor179]]
==== {blank}

When the chair has taken the decision to proceed to the approval stage (see <<_idTextAnchor183>>) or publication stage (see <<_idTextAnchor193>>), the secretariat of the technical committee or subcommittee shall prepare, within a maximum of 16 weeks after the end of the voting period and with the assistance of its editing committee, a final text and send it to the office of the CEO for preparation and circulation of the final draft International Standard.

The secretariat shall provide the office of the CEO with the text in a revisable electronic format and also in a format which permits validation of the revisable form.

Texts that do not conform to the ISO/IEC Directives, Part 2 shall be returned to the secretariat with a request for correction before they are registered.

The revised text shall be submitted to ISO Central Secretariat in electronic format together with the decision of the chair taken as a result of the voting, using ISO Form 13, and including a detailed indication of the decisions taken for each comment as <<_idTextAnchor306>> to the ISO Form 13.


[[_idTextAnchor180]]
==== {blank}

For time limits relating to this stage, see <<_idTextAnchor127>>.


[[_idTextAnchor181]]
==== {blank}

The enquiry stage ends with the registration, by the office of the CEO, of the text for circulation as a final draft International Standard or publication as an International Standard, in the case of <<_idTextAnchor177>> a) and b).


[[_idTextAnchor183]]
=== Approval stage

[[_idTextAnchor184]]
==== {blank}

At the approval stage, the final draft International Standard (FDIS) shall be distributed by the office of the CEO within 12 weeks to all National Bodies for a 8-week vote (6 weeks in IEC).

National Bodies shall be advised of the date by which ballots are to be received by the office of the CEO.


[[_idTextAnchor185]]
==== {blank}

Votes submitted by National Bodies shall be explicit: positive, negative, or abstention.

A National Body may submit comments on any FDIS vote.

If a National Body finds a final draft International Standard unacceptable, it shall vote negatively and state the technical reasons. It shall not cast an affirmative vote that is conditional on the acceptance of modifications.

In the case where a member body has voted negatively without submitting a justification, the vote will not be counted.

In the case where a Member Body has voted negatively and has submitted comments that are not clearly of a technical nature, the committee secretary shall contact the ISO/CS Technical Programme Manager within 2 weeks of the ballot closure.


[[_idTextAnchor186]]
==== {blank}

A final draft International Standard having been circulated for voting is approved if

. a two-thirds majority of the votes cast by the P-members of the technical committee or subcommittee are in favour, and

. not more than one-quarter of the total number of votes cast are negative.

Abstentions are excluded when the votes are counted, as well as negative votes not accompanied by technical reasons.


[[_idTextAnchor187]]
==== {blank}

The secretariat of the technical committee or subcommittee has the responsibility of bringing any errors that may have been introduced in the preparation of the draft to the attention of the office of the CEO by the end of the voting period; further editorial or technical amendments are not acceptable at this stage.


[[_idTextAnchor188]]
==== {blank}

All comments received will be retained for the next review and will be recorded on the voting form as "noted for future consideration". However, the Secretary along with the office of the CEO may seek to resolve obvious editorial errors. Technical changes to an approved FDIS are not allowed.

Within 2 weeks after the end of the voting period, the office of the CEO shall circulate to all National Bodies a report showing the result of voting and indicating either the formal approval by National Bodies to issue the International Standard or formal rejection of the final draft International Standard.


[[_idTextAnchor189]]
==== {blank}

If the final draft International Standard has been approved in accordance with the conditions of <<_idTextAnchor186>>, it shall proceed to the publication stage (see <<_idTextAnchor193>>).


[[_idTextAnchor190]]
==== {blank}

If the final draft International Standard is not approved in accordance with the conditions in <<_idTextAnchor186>>, the document shall be referred back to the technical committee or subcommittee concerned for reconsideration in the light of the technical reasons submitted in support of the negative votes.

The committee may decide to:

* resubmit a modified draft as a committee draft, enquiry draft or, in ISO and JTC 1, final draft International Standard;
* publish a Technical Specification (see <<_idTextAnchor226>>);
* publish a Publicly Available Specification (see <<_idTextAnchor231>>);
* cancel the project.


[[_idTextAnchor191]]
==== {blank}

The approval stage ends with the circulation of the voting report (see <<_idTextAnchor188>>) stating that the FDIS has been approved for publication as an International Standard, with the publication of a Technical Specification (see 3.1.1.2), or with the document being referred back to the committee.


[[_idTextAnchor193]]
=== Publication stage

[[_idTextAnchor194]]
==== {blank}

Within 6 weeks, the office of the CEO shall correct any errors indicated and validated by the secretariat of the technical committee or subcommittee, and publish and distribute the International Standard.

Before publication the document is sent to the secretary and project leader for final review.


[[_idTextAnchor195]]
==== {blank}

The publication stage ends with the publication of the International Standard.


[[_idTextAnchor197]]
=== Maintenance of deliverables

The procedures for the maintenance of deliverables are given in the respective Supplements to the ISO/IEC Directives.


[[_idTextAnchor198]]
==== Introduction

Every International Standard and other deliverable published by ISO or jointly with IEC shall be subject to systematic review in order to determine whether it should be confirmed, revised, amended (for International Standard), converted to another form of deliverable, or withdrawn, according to <<_idTextAnchor199>>.

A committee may at any time between systematic reviews pass a resolution initiating a revision of a deliverable.

See <<_idTextAnchor143>> for the process for initiating a revision of an existing deliverable (or amendment of an existing International Standard).

For minor changes to International Standards, e.g. updating and editorial changes, that do not impact the technical content, a shortened procedure called "minor revision" may be applied. This is comprised only of the proposal for a minor revision by the committee (through a resolution and completion of ISO form 8B), approval and publication stages (see  <<_idTextAnchor183>> and <<_idTextAnchor193>>). Subsequent to the resolution of the responsible technical committee and consultation of the responsible ISO Technical Programme Manager, a final draft of the revised deliverable shall be circulated for an 8 week FDIS vote, and 12 weeks in the case of Vienna Agreement documents. The Foreword of the next edition of the deliverable shall indicate that it is a minor revision and list the updates and editorial changes made.


[[_idTextAnchor199]] 
.Timing of systematic reviews
[cols="4*",options="header"]
|===
| Deliverable a| Max. elapsed time +
 before systematic +
 review
a| Max. number of +
 times deliverable +
 may be confirmed
| Max. life

| International Standard | 5 years | Not limited | Not limited

| Technical Specification (see <<_idTextAnchor229>>) | 3 years | Once recommended | 6 years recommended
| Publicly Available Specification (see <<_idTextAnchor235>>) | 3 years | Once a| 6 years +
 (If not converted after this period, the deliverable is proposed for withdrawal)
| Technical Report (see <<_idTextAnchor240>>) | Not specified | Not specified | Not limited
|===

A systematic review will typically be initiated in the following circumstances:

* (all deliverables) on the initiative and as a responsibility of the secretariat of the responsible committee, typically as the result of the elapse of the specified period since publication or the last confirmation of the document, or

* (for International Standards and Technical Specifications) a default action by ISO Central Secretariat if a systematic review of the International Standard or Technical Specification concerned has not been initiated by the secretariat of the responsible committee, or

* (all deliverables) at the request of one or more National Body, or

* (all deliverables) at the request of the CEO.

The timing of a systematic review is normally based either on the year of publication or, where a document has already been confirmed, on the year in which it was last confirmed. However, it is not necessary to wait for the maximum period to elapse before a document is reviewed.


[[_idTextAnchor200]]
==== Review

The review period is 20 weeks.

NOTE: Systematic reviews are administered electronically by the ISO Central Secretariat and all ISO member bodies are invited to respond to such reviews. P-members of a given committee have an obligation to vote on all systematic review ballots for deliverables under the responsibility of that committee. The purpose of the reviews has been extended to include obtaining information when member bodies have needed to make modifications in order to make ISO standards suitable for national adoption. Such modifications need to be considered by committees in order to determine whether they need to be taken into account to improve the global relevance of a standard. The final decision, to revise, confirm or withdraw a standard, remains with the P-members of the responsible committee.

After the closing of the vote, the secretariat's proposal reflecting the voting results shall be circulated to the members of the technical committee or subcommittee using Form 21. No more than 6 months after the closing of the vote, the committee shall take a final decision as to whether to revise, confirm or withdraw the standard, following which the secretariat shall submit the committee's decision to the ISO Central Secretariat.


[[_idTextAnchor201]]
==== Interpretation of ballot results

[[_idTextAnchor202]]
===== General

Typically, a decision as to the appropriate action to take following a systematic review shall be based on a simple majority of P-members voting for a specific action. However, in some cases a more detailed analysis of the results may indicate that another interpretation may be more appropriate.

NOTE: It is not feasible to provide concrete rules for all cases when interpreting the ballot results due to the variety of possible responses, degrees of implementation, and the relative importance of comments, etc.

Where voting results are not definitive and/or a decision is based on interpretation of responses the secretariat shall invite approval of a proposed course of action within a specified time delay, for example within two months.

In proposing future action, due account shall be taken of the maximum possible number of confirmations and specified maximum life of the deliverable concerned (see <<_idTextAnchor199>>).


[[_idTextAnchor203]]
===== Interpretation of ballot results for International Standards

====== Option 1: Confirmation (retention without technical change)

Where it has been verified that a document is used, that it should continue to be made available, and that no technical changes are needed, a deliverable may be confirmed. The criteria is as follows:

* the standard has been adopted with or without change or is used in at least five countries (when this criteria is not met, the standard should be withdrawn); and

* a simple majority of the P-members of the committee voting propose confirmation.

====== Option 2: Amendment or revision (Retention, with change/s)

Where it has been verified that an International Standard is used, that it should continue to be made available, but that technical changes are needed, it may be proposed for amendment or revision. The criteria are as follows:

* the International Standard has been adopted with or without change or is used in at least five countries (when this criterion is not met, the standard should be withdrawn); and

* a simple majority of the P-members of the committee voting considers there is a need for amendment or revision.

In that case, an item may be registered as an approved work item (stage 10.99).

A call for experts shall be launched. However, there is no minimum number of active P-members required.

Where an amendment or revision is not immediately started following approval by the committee, it is recommended that the project is first registered as a preliminary work item and that the International Standard is registered as confirmed. When it is eventually proposed for registration at stage 10.99, reference shall be made to the results of the preceding systematic review and the committee shall pass a resolution (see <<_idTextAnchor143>> for the process for initiating a revision or amendment of an existing International Standard).

Where it is decided that the International Standard needs to be revised or amended, it becomes a new project and shall be added to the programme of work of the technical committee or subcommittee. The steps for revision or amendment are the same as those for preparation of a new International Standard (see ISO/IEC Directives, Part 1, <<_idTextAnchor142>> to <<_idTextAnchor193>>), and include the establishment of target dates for the completion of the relevant stages.

====== Option 3: Withdrawal

When the standard has not been adopted with or without change or is not used in at least five countries, the standard should be withdrawn (see Options 1 and 2 above).

In the case of the proposed withdrawal of an International Standard, the National Bodies shall be informed by the CEO of the decision of the technical committee or subcommittee, with an invitation to inform the office of the CEO within 8 weeks if they object to that decision.

Any objection received shall be referred to the ISO Technical Management Board for consideration and decision.


[[_idTextAnchor204]]
===== Conversion to an International Standard (Technical Specifications and Publicly Available Specifications only)

In addition to the three basic options of confirmation, revision, or withdrawal, in the cases of the systematic review of Technical Specifications and Publicly Available Specifications a fourth option is their conversion to an International Standard.

To initiate conversion to an International Standard, a text, up-dated as appropriate, is submitted to the normal development procedures as specified for an International Standard (see <<_idTextAnchor143>>).

The conversion procedure will typically start with a DIS vote. Where changes considered to be required are judged as being so significant as to require a full review in the committee prior to DIS ballot, a revised version of the document shall be submitted for review and ballot as a CD.


[[_idTextAnchor205]]
==== Reinstatement of withdrawn standards

If, following withdrawal of an International Standard, a committee determines that it is still needed, it may propose that the standard be reinstated. The standard shall be issued either as a draft International Standard or as a final draft International Standard, as decided by the committee, for voting by the member bodies. The usual approval criteria shall apply. If approved, the standard shall be published as a new edition with a new date of publication. The foreword shall explain that the standard results from the reinstatement of the previous edition.


[[_idTextAnchor207]]
=== Corrections and amendments

[[_idTextAnchor208]]
==== General

A published International Standard may subsequently be modified by the publication of

* a technical corrigendum (in IEC only);
* a corrected version;
* an amendment; or
* a revision (as part of the maintenance procedure in <<_idTextAnchor197>>).

NOTE: In case of revision a new edition of the International Standard will be issued.


[[_idTextAnchor209]]
==== Corrections

A correction is only issued to correct an error or ambiguity, inadvertently introduced either in drafting or in publishing and which could lead to incorrect or unsafe application of the publication.

Corrections are not issued to update information that has become outdated since publication.

Suspected errors shall be brought to the attention of the secretariat of the technical committee or subcommittee concerned. After confirmation by the secretariat and chair, if necessary in consultation with the project leader and P-members of the technical committee or subcommittee, the secretariat shall submit to the office of the CEO a proposal for correction, with an explanation of the need to do so.

The Chief Executive Officer shall decide, in consultation with the secretariat of the technical committee or subcommittee, and bearing in mind both the financial consequences to the organization and the interests of users of the publication, whether to publish a technical corrigendum (in IEC only) and/or a corrected version of the existing edition of the publication (see also <<_idTextAnchor211>>). The secretariat of the committee will then inform the members of the committee of the outcome.

The corrections are mentioned in the Foreword of the corrected version.

In general, a correction will not be issued for a publication that is older than 3 years.


[[_idTextAnchor210]]
==== Amendments

An amendment alters and/or adds to previously agreed technical provisions in an existing International Standard. An amendment is considered as a partial revision: the rest of the International Standard is not open for comments.

An amendment is normally published as a separate document, the edition of the International Standard affected remaining in use.

The procedure for developing and publishing an amendment shall be as described in <<_idTextAnchor142>> (ISO and JTC 1), or the review and maintenance procedures (see IEC Supplement) and <<_idTextAnchor151>>, <<_idTextAnchor161>>, <<_idTextAnchor173>> (draft amendment, DAM), <<_idTextAnchor183>> (final draft amendment, FDAM), and <<_idTextAnchor193>>.

At the approval stage (<<_idTextAnchor183>>), the Chief Executive Officer shall decide, in consultation with the secretariat of the technical committee or subcommittee, and bearing in mind both the financial consequences to the organization and the interests of users of the International Standard, whether to publish an amendment or a new edition of the International Standard, incorporating the amendment. (See also <<_idTextAnchor211>>.)

NOTE: Where it is foreseen that there will be frequent additions to the provisions of an International Standard, the possibility should be borne in mind at the outset of developing these additions as a series of parts (see ISO/IEC Directives, Part 2).


[[_idTextAnchor211]]
==== Avoidance of proliferation of modifications

No more than 2 separate documents in the form of technical corrigenda (in IEC only) or amendments shall be published modifying a current International Standard. The development of a third such document shall result in publication of a new edition of the International Standard.


[[_idTextAnchor213]]
=== Maintenance agencies

When a technical committee or subcommittee has developed a standard that will require frequent modification, it may decide that a maintenance agency is required. Rules concerning the designation of maintenance agencies are given in <<_idTextAnchor407>>.


[[_idTextAnchor215]]
=== Registration authorities

When a technical committee or subcommittee has developed a standard that includes registration provisions, a registration authority is required. Rules concerning the designation of registration authorities are given in <<_idTextAnchor415>>.

In ISO, see also Annex SN, Registration Authority Policy.


[[_idTextAnchor217]]
=== Copyright

The copyright for all drafts and International Standards and other publications belongs to ISO, IEC or ISO and IEC, respectively as represented by the office of the CEO.

The content of, for example, an International Standard may originate from a number of sources, including existing national standards, articles published in scientific or trade journals, original research and development work, descriptions of commercialized products, etc. These sources may be subject to one or more rights.

In ISO and IEC, there is an understanding that original material contributed to become a part of an ISO, IEC or ISO/IEC publication can be copied and distributed within the ISO and/or IEC systems (as relevant) as part of the consensus building process, this being without prejudice to the rights of the original copyright owner to exploit the original text elsewhere. Where material is already subject to copyright, the right should be granted to ISO and/or IEC to reproduce and circulate the material. This is frequently done without recourse to a written agreement, or at most to a simple written statement of acceptance. Where contributors wish a formal signed agreement concerning copyright of any submissions they make to ISO and/or IEC, such requests shall be addressed to ISO Central Secretariat or the IEC Central Office, respectively.

Attention is drawn to the fact that the respective members of ISO and IEC have the right to adopt and re-publish any respective ISO and/or IEC standard as their national standard. Similar forms of endorsement do or may exist (for example, with regional standardization organizations).


[[_idTextAnchor219]]
=== Reference to patented items (see also <<_idTextAnchor422>>)

[[_idTextAnchor220]]
==== {blank}

If, in exceptional situations, technical reasons justify such a step, there is no objection in principle to preparing an International Standard in terms which include the use of items covered by patent rights -- defined as patents, utility models and other statutory rights based on inventions, including any published applications for any of the foregoing -- even if the terms of the standard are such that there are no alternative means of compliance. The rules given below shall be applied.


[[_idTextAnchor221]]
==== {blank}

If technical reasons justify the preparation of a document in terms which include the use of items covered by patent rights, the following procedures shall be complied with:

. The proposer of a proposal for a document shall draw the attention of the committee to any patent rights of which the proposer is aware and considers to cover any item of the proposal. Any party involved in the preparation of a document shall draw the attention of the committee to any patent rights of which it becomes aware during any stage in the development of the document.

. If the proposal is accepted on technical grounds, the proposer shall ask any holder of such identified patent rights for a statement that the holder would be willing to negotiate worldwide licences under his/her rights with applicants throughout the world on reasonable and non-discriminatory terms and conditions. Such negotiations are left to the parties concerned and are performed outside ISO and/or IEC. A record of the right holder's statement shall be placed in the registry of the ISO Central Secretariat or IEC Central Office as appropriate. If the right holder does not provide such a statement, the committee concerned shall not proceed with inclusion of an item covered by a patent right in the document without authorization from ISO Council or IEC Council Board as appropriate.

. A document shall not be published until the statements of the holders of all identified patent rights have been received, unless the council board concerned gives authorization.


[[_idTextAnchor222]]
==== {blank}

Should it be revealed after publication of a document that licences under patent rights, which appear to cover items included in the document, cannot be obtained under reasonable and non-discriminatory terms and conditions, the document shall be referred back to the relevant committee for further consideration.