
[[_idTextAnchor224]]
== Development of other deliverables

[[_idTextAnchor226]]
=== Technical Specifications

Technical Specifications may be prepared and published under the following circumstances and conditions.


[[_idTextAnchor227]]
==== {blank}

When the subject in question is still under development or where for any other reason there is the future but not immediate possibility of an agreement to publish an International Standard, the technical committee or subcommittee may decide, by following the procedure set out in <<_idTextAnchor142>>, that the publication of a Technical Specification would be appropriate. The procedure for preparation of such a Technical Specification shall be as set out in <<_idTextAnchor151>> and <<_idTextAnchor161>>. The decision to publish the resulting document as a Technical Specification shall require a two-thirds majority vote of the P-members voting of the technical committee or subcommittee. A Technical Specification is a normative document.

In ISO, when the required support cannot be obtained for a final draft International Standard to pass the approval stage (see <<_idTextAnchor183>>), or in case of doubt concerning consensus, the technical committee or subcommittee may decide, by a two-thirds majority vote of P-members voting, that the document should be published in the form of a Technical Specification.


[[_idTextAnchor228]]
==== {blank}

When the P-members of a technical committee or subcommittee have agreed upon the publication of a Technical Specification, the draft specification shall be submitted electronically by the secretariat of the technical committee or subcommittee to the office of the CEO within 16 weeks for publication. Competing technical specifications offering different technical solutions are possible provided that they do not conflict with existing International Standards.


[[_idTextAnchor229]]
==== {blank}

Technical Specifications shall be subject to review by the technical committee or subcommittee not later than 3 years after their publication. The aim of such review shall be to re-examine the situation which resulted in the publication of a Technical Specification and if possible to achieve the agreement necessary for the publication of an International Standard to replace the Technical Specification. In IEC, the date for this review is based on the stability date which shall be agreed in advance of the publication of the Technical Specification (review date).


[[_idTextAnchor231]]
=== Publicly Available Specifications (PAS)

The procedures set out in <<_idTextAnchor142>> apply to the development of a PAS.


[[_idTextAnchor232]]
==== {blank}

A PAS may be an intermediate specification, published prior to the development of a full International Standard, or, in IEC may be a "dual logo" publication published in collaboration with an external organization. It is a document not fulfilling the requirements for a standard. A PAS is a normative document.

Normally, the decision to develop a PAS should be agreed at the outset, i.e. simultaneously with the approval of the new work item proposal.


[[_idTextAnchor233]]
==== {blank}

A proposal for submission of a PAS may be made by the Secretariat, an A-liaison or by any P-member of the committee. In IEC, a C-liaison may also submit a PAS (see <<_idTextAnchor096>>).


[[_idTextAnchor234]]
==== {blank}

The PAS is published after verification of the presentation and checking that there is no conflict with existing International Standards by the committee concerned and following simple majority approval of the P-members voting of the committee concerned. Competing PAS offering different technical solutions are possible provided that they do not conflict with existing International Standards.


[[_idTextAnchor235]]
==== {blank}

A PAS shall remain valid for an initial maximum period of 3 years in ISO and 2 years in IEC. The validity may be extended for a single period up to a maximum of 3 years in ISO and 2 years in IEC, at the end of which it shall be transformed with or without change into another type of normative document, or shall be withdrawn.


[[_idTextAnchor237]]
=== Technical Reports

[[_idTextAnchor238]]
==== {blank}

When a technical committee or subcommittee has collected data of a different kind from that which is normally published as an International Standard (this may include, for example, data obtained from a survey carried out among the National Bodies, data on work in other international organizations or data on the "state of the art" in relation to standards of National Bodies on a particular subject), the technical committee or subcommittee may decide, by a simple majority vote of P-members voting, to request the Chief Executive Officer to publish such data in the form of a Technical Report. The document shall be entirely informative in nature and shall not contain matter implying that it is normative. It shall clearly explain its relationship to normative aspects of the subject which are, or will be, dealt with in International Standards related to the subject. The Chief Executive Officer, if necessary in consultation with the technical management board, shall decide whether to publish the document as a Technical Report.


[[_idTextAnchor239]]
==== {blank}

When the P-members of a technical committee or subcommittee have agreed upon the publication of a Technical Report, the draft report shall be submitted electronically by the secretariat of the technical committee or subcommittee to the Chief Executive Officer within 16 weeks for publication.


[[_idTextAnchor240]]
==== {blank}

It is recommended that Technical Reports are regularly reviewed by the committee responsible, to ensure that they remain valid. Withdrawal of a Technical Report is decided by the technical committee or subcommittee responsible.

Technical Reports are not subject to systematic revision.
