

[[_idTextAnchor242]]
== Meetings

[[_idTextAnchor244]]
=== General

National Bodies are reminded that they are not permitted to charge delegates/experts any sort of participation fee, nor require accommodations at specific hotels or hotel rates for any meetings of technical committees, subcommittees, working groups, maintenance and project teams. The basic meeting facilities shall be funded entirely by resources from a National Body and/or voluntary sponsors. For more information in IEC, see Meeting Guide (https://www.iec.ch/members_experts/refdocs/iec/IEC_Meeting_Guide_2012.pdf[https://www.iec.ch/members_experts/refdocs/iec/IEC_Meeting_Guide_2012.pdf]) and for ISO, see Annex SF for further details.


[[_idTextAnchor245]]
==== {blank}

Technical committees and subcommittees shall use current electronic means to carry out their work (for example, e-mail, groupware and teleconferencing) wherever possible. A meeting of a technical committee or subcommittee should be convened only when it is necessary to discuss committee drafts (CD) or other matters of substance which cannot be settled by other means.


[[_idTextAnchor246]]
==== {blank}

The technical committee secretariat should look ahead with a view to drawing up, in consultation with the office of the CEO, a planned minimum 2-year programme of meetings of the technical committee and its subcommittees and, if possible, its working groups, taking account of the programme of work.


[[_idTextAnchor247]]
==== {blank}

In planning meetings, account should be taken of the possible advantage of grouping meetings of technical committees and subcommittees dealing with related subjects, in order to improve communication and to limit the burden of attendance at meetings by delegates who participate in several technical committees or subcommittees.


[[_idTextAnchor248]]
==== {blank}

In planning meetings, account should also be taken of the advantages for the speedy preparation of drafts of holding a meeting of the editing committee immediately after the meeting of the technical committee or subcommittee and at the same place.


[[_idTextAnchor250]]
=== Procedure for calling a meeting

For information relating to hosting meetings, refer to Annex SF.


[[_idTextAnchor251]]
==== Technical committee and subcommittee meetings

[[_idTextAnchor252]]
===== {blank}

The date and place of a meeting shall be subject to an agreement between the chair and the secretariat of the technical committee or subcommittee concerned, the Chief Executive Officer and the National Body acting as host. In the case of a subcommittee meeting, the subcommittee secretariat shall first consult with the secretariat of the parent technical committee in order to ensure coordination of meetings (see also <<_idTextAnchor247>>).


[[_idTextAnchor253]]
===== {blank}

A National Body wishing to act as host for a particular meeting shall contact the Chief Executive Officer and the technical committee or subcommittee secretariat concerned.

The National Body shall first ascertain that there are no restrictions imposed by its country to the entry of representatives of any P-member of the technical committee or subcommittee for the purpose of attending the meeting.

In accrediting delegates to attend meetings, national standards bodies from P- and O-member countries shall register them in the ISO Meetings application.

The hosting national standards body can access the list of delegates through the ISO Meetings application so that it can make appropriate arrangements for the meeting. It is the responsibility of the national standards bodies in countries with participants who need invitation letters to send the names of these participants directly to the hosting national standards body.

The hosting organizations are advised to verify and provide information on access means to meeting facilities. As per <<_idTextAnchor254>>, a document describing logistics for the meeting shall be circulated. As well as location and transport information, it should provide details of the accessibility of meeting facilities.

During the planning process, there should be a request for notification of specific accessibility requirements. The hosting body should make its best efforts to satisfy these requirements.


[[_idTextAnchor254]]
===== {blank}

The secretariat shall ensure that arrangements are made for the agenda and logistical information to be circulated by the office of the CEO (in the IEC) or by the secretariat with a copy to the office of the CEO (in ISO) at the latest 16 weeks before the date of the meeting.

NOTE: All new work item proposals must be approved by correspondence (committee internal ballot -- CIB) see <<_idTextAnchor146>>.

Only those committee drafts for which the compilation of comments will be available at least 6 weeks before the meeting shall be included on the agenda and be eligible for discussion at the meeting.

Any other working documents, including compilations of comments on drafts to be discussed at the meeting, shall be distributed not less than 6 weeks in advance of the meeting.

The agenda shall clearly state the starting and estimated finishing times.

In the event of meetings over running the estimated finishing time, the Chair shall ensure that the P-members are willing to take voting decisions. However if P-members leave, they may request the Chair not to take any further voting decisions.

Any decisions made after the estimated finishing time of the meeting and after any P-members have left shall be confirmed by correspondence after the meeting.

NOTE: Attendees should take the estimated meeting time into consideration when booking their travel.

See Annex SK for the issuance of notices, agendas and documents before committee and working group meetings.


[[_idTextAnchor255]]
==== Working group meetings

[[_idTextAnchor256]]
===== {blank}

Working groups shall use current electronic means to carry out their work (for example, e-mail, groupware and teleconferencing) wherever possible. For a fully remote meeting, the advance notice shall be made available a minimum of 4 weeks in advance of the meeting.

When a physical meeting needs to be held, notification by the convenor of the meetings of a working group shall be sent to its members and to the secretariat of the parent committee, at least 6 weeks in advance of the meeting.

The Working Group leadership should ensure that everything reasonable is done to enable experts to actively participate.

Arrangements for meetings shall be made between the convenor and the member of the working group in whose country the meeting is to be held. The latter member shall be responsible for all practical working arrangements.


[[_idTextAnchor257]]
===== {blank}

If a working group meeting is to be held in conjunction with a meeting of the parent committee, the convenor shall coordinate arrangements with the secretariat of the parent committee. In particular it shall be ensured that the working group members receive all general information for the meeting, which is sent to delegates to the meeting of the parent committee.


[[_idTextAnchor258]]
===== {blank}

Either the WG (or PT/MT/AC in IEC) leader or the Secretary of the relevant committee shall notify National Body Secretariats of any WG (or PT/MT/AC in IEC) meeting held in their country.


[[_idTextAnchor260]]
=== Languages at meetings

While the official languages are English, French and Russian, meetings are conducted in English by default.

The National Body for the Russian Federation provides all interpretation and translation into or from the Russian language.

The chair and secretariat are responsible for dealing with the question of language at a meeting in a manner acceptable to the participants following the general rules of ISO or IEC, as appropriate. (See also <<_idTextAnchor381>>.)


[[_idTextAnchor262]]
=== Cancellation of meetings

Every possible effort shall be made to avoid cancellation or postponement of a meeting once it has been convened. Nevertheless, if the agenda and basic documents are not available within the time required by <<_idTextAnchor254>>, then the Chief Executive Officer has the right to cancel the meeting.


[[_idTextAnchor264]]
=== Distribution of documents

For requirements relating to document distribution, refer to Annex SB. A copy of the agenda and calling notice for a committee meeting shall be made available to the ISO Central Secretariat for information.


[[_idTextAnchor266]]
=== Remote participation at committee meetings

Remote participation at committee meetings is supported in ISO to enable the goals of increasing stakeholder engagement and better coordination of the committee work. Remote participation is allowed for all ISO meetings and ISO committees, provided that:

* The committee secretary checks with the host prior to meeting and follows the 'Guidelines on remote participation at committee meetings'.

* The host agrees and can provide the necessary technology and support.

* The same registration and accreditation rules apply to remote and physical participants.

* The 'https://isotc.iso.org/livelink/livelink/fetch/-15620806/15620808/15623592/17856067/Guidelines_for_remote_participation_in_committee_meeetings_September_2016.pdf?nodeid=17857546&vernum=-2[Guidelines on remote participation at committee meetings'] are provided to all participants in advance of the meeting.
