== Foreword

The *ISO/IEC Directives* are published in two parts:

* Part 1: Procedures for the technical work
* Part 2: Principles and rules for the structure and drafting of ISO and IEC documents

Furthermore, the International Organization for Standardization (ISO), the International Electrotechnical Commission (IEC) and ISO/IEC Joint Technical Committee (JTC) 1 have published independent supplements to Part 1, which include procedures that are not common.

This part sets out the procedures to be followed within ISO and the IEC in carrying out their technical work: primarily the development and maintenance of International Standards through the activities of technical committees and their subsidiary bodies.

ISO, IEC and ISO/IEC JTC 1 provide additional guidance and tools to all those concerned with the preparation of technical documents on their respective websites ( https://www.iso.org/iso/standards_development/processes_and_procedures/iso_iec_directives_and_iso_supplement.htm; https://www.iec.ch/members_experts/refdocs/ and http://www.jtc1.org/).

This sixteenth edition incorporates changes agreed by the respective technical management boards since publication of the fourteenth edition in 2018. Procedures which are not common to all the ISO/IEC Directives are published separately in the ISO Supplement (also referred to as the Consolidated ISO Supplement), the IEC Supplement or the ISO/IEC JTC 1 Supplement, respectively. The Supplements are to be used in conjunction with this document.

The following clauses have been modified with respect to the previous edition: Foreword, <<scls-1-9-2>>, <<scls-1-12-1>>, <<scls-1-12-2>>, <<scls-1-15-1>>, <<scls-1-17>>, <<scls-2-8-1>>, <<scls-2-14-2>>, <<scls-4-2-2-1>>, <<annexA>>, <<annexB>>, <<annexF>>, Annex L, and Annex M. The track changes version of this sixteenth edition should be consulted for the details of the changes made.

These procedures have been established by ISO and IEC in recognition of the need for International Standards to be cost-effective and timely, as well as widely recognized and generally applied. In order to attain these objectives, the procedures are based on the following concepts.

. *Current technology and project management*
+
--
Within the framework of these procedures, the work may be accelerated and the task of experts and secretariats facilitated both by current technology (e.g. IT tools) and project management methods.
--
. *Consensus*
+
--
Consensus, which requires the resolution of substantial objections, is an essential procedural principle and a necessary condition for the preparation of International Standards that will be accepted and widely used. Although it is necessary for the technical work to progress speedily, sufficient time is required before the approval stage for the discussion, negotiation and resolution of significant technical disagreements.

For further details on the principle of "consensus", see <<scls-2-5-6>>.
--
. *Discipline*
+
--
National Bodies need to ensure discipline with respect to deadlines and timetables in order to avoid long and uncertain periods of "dead time". Similarly, to avoid re-discussion, National Bodies have the responsibility of ensuring that their technical standpoint is established taking account of all interests concerned at national level, and that this standpoint is made clear at an early stage of the work rather than, for example, at the final (approval) stage. Moreover, National Bodies need to recognize that substantial comments tabled at meetings are counter-productive, since no opportunity is available for other delegations to carry out the necessary consultations at home, without which rapid achievement of consensus will be difficult.
--
. *Cost-effectiveness*
+
--
These procedures take account of the total cost of the operation. The concept of "total cost" includes direct expenditure by National Bodies, expenditure by the offices in Geneva (funded mainly by the dues of National Bodies), travel costs and the value of the time spent by experts in working groups and committees, at both national and international level.
--

*Terminology used in this document*

NOTE: Wherever appropriate in this document, for the sake of brevity the following terminology has been adopted to represent similar or identical concepts within ISO and IEC.

[%unnumbered]
|===
h| Term h| ISO h| IEC

| National Body | Member Body (MB) | National Committee (NC)
| technical management board (TMB) | Technical Management Board (ISO/TMB) | Standardization Management Board (SMB)
| Chief Executive Officer (CEO) | Secretary-General | General Secretary
| office of the CEO | Central Secretariat (CS) | Central Office (CO)
| council board | Council | Council Board (CB)
| advisory group | Technical Advisory Group (TAG) | Advisory Committee
| secretary (of a committee or subcommittee) | Committee manager | Secretary
3+| For other concepts, ISO/IEC Guide 2 applies.
|===

[NOTE,keep-separate=true]
====
In addition the following abbreviations are used in this document.
====

JTAB:: Joint Technical Advisory Board
JCG:: Joint Coordination Group
JPC:: Joint Project Committee
JTC:: Joint Technical Committee
JWG:: joint working group
TC:: technical committee
SC:: Subcommittee
PC:: project committee
WG:: working group
PWI:: preliminary work item
NP:: new work item proposal
WD:: working draft
CD:: committee draft
DIS:: draft International Standard (ISO)
CDV:: committee draft for vote (IEC)
FDIS:: final draft International Standard
PAS:: Publicly Available Specification
TS:: Technical Specification
TR:: Technical Report
