[[cls-5]]
== Appeals

[[scls-5-1]]
=== General

[[scls-5-1-1]]
==== National Bodies have the right of appeal

. to the parent technical committee on a decision of a subcommittee;
. to the technical management board on a decision of a technical committee;
. to the council board on a decision of the technical management board,

within 12 weeks in ISO and 8 weeks in IEC of the decision in question.

The decision of the council board on any case of appeal is final.

[[scls-5-1-2]]
==== {blank}

A P-member of a technical committee or subcommittee may appeal against any action, or inaction, on the part of the technical committee or subcommittee, when the P-member considers that such action or inaction is

. not in accordance with
** the Statutes and Rules of Procedure;
** the ISO/IEC Directives; or

. not in the best interests of international trade and commerce, or such public factors as safety, health or environment.

[[scls-5-1-3]]
==== {blank}

Matters under appeal may be either technical or administrative in nature.

Appeals on decisions concerning new work item proposals, committee drafts, enquiry drafts and final draft International Standards are only eligible for consideration if

* questions of principle are involved, or
* the contents of a draft may be detrimental to the reputation of ISO or IEC.

[[scls-5-1-4]]
==== {blank}

All appeals shall be fully documented to support the P-member's concern.

[[scls-5-2]]
=== Appeal against a subcommittee decision

[[scls-5-2-1]]
==== {blank}

The documented appeal shall be submitted by the P-member to the secretariat of the parent technical committee, with a copy to the Chief Executive Officer.

[[scls-5-2-2]]
==== {blank}

Upon receipt, the secretariat of the parent technical committee shall advise all its P-members of the appeal and take immediate action, by correspondence or at a meeting, to consider and decide on the appeal, consulting the Chief Executive Officer in the process.

[[scls-5-2-3]]
==== {blank}

If the technical committee supports its subcommittee, then the P-member which initiated the appeal may either

* accept the technical committee decision, or
* appeal against it.

[[scls-5-3]]
=== Appeal against a technical committee decision

[[scls-5-3-1]]
==== {blank}

Appeals against a technical committee decision may be of 2 kinds:

* an appeal arising out of <<scls-5-2-3>> above, or
* an appeal against an original decision of a technical committee.

[[scls-5-3-2]]
==== {blank}

The documented appeal shall, in all cases, be submitted to the Chief Executive Officer, with a copy to the chair and secretariat of the technical committee.

[[scls-5-3-3]]
==== {blank}

The Chief Executive Officer shall, following whatever consultations s/he deems appropriate, refer the appeal together with his/her comments to the technical management board within 4 weeks after receipt of the appeal.

[[scls-5-3-4]]
==== {blank}

The technical management board shall decide whether an appeal shall be further processed or not. If the decision is in favour of proceeding, the chair of the technical management board shall form a conciliation panel.

The conciliation panel shall hear the appeal within 12 weeks and attempt to resolve the difference of opinion as soon as practicable. The conciliation panel shall give a final report within 12 weeks. If the conciliation panel is unsuccessful in resolving the difference of opinion, this shall be reported to the Chief Executive Officer, together with recommendations on how the matter should be settled.

[[scls-5-3-5]]
==== {blank}

The Chief Executive Officer, on receipt of the report of the conciliation panel, shall inform the technical management board, which will make its decision.

[[scls-5-4]]
=== Appeal against a technical management board decision

An appeal against a decision of the technical management board shall be submitted to the Chief Executive Officer with full documentation on all stages of the case.

The Chief Executive Officer shall refer the appeal together with his/her comments to the members of the council board within 4 weeks after receipt of the appeal.

The council board shall make its decision within 12 weeks.

[[scls-5-5]]
=== Progress of work during an appeal process

When an appeal is against a decision respecting work in progress, the work shall be continued, up to and including the approval stage (see <<scls-2-7>>).
