[[annexH]]
[appendix,obligation=normative]
== Registration authorities

[[scls-H-1]]
=== {blank}

A technical committee or subcommittee developing an International Standard that will require a registration authority shall inform the Chief Executive Officer at an early stage, in order to permit any necessary negotiations and to allow the technical management board to take a decision in advance of the publication of the International Standard.

[[scls-H-2]]
=== {blank}

The technical management board designates registration authorities in connection with International Standards on the proposal of the technical committee concerned.

[[scls-H-3]]
=== {blank}

Registration authorities should be qualified and internationally acceptable bodies; if there is no such organization available, such tasks may be conferred upon the office of the CEO by decision of the technical management board.

[[scls-H-4]]
=== {blank}

Registration authorities should be required to indicate clearly in their operations that they have been designated by ISO or IEC (for example, by including appropriate wording in the letterhead of the designated body).

[[scls-H-5]]
=== {blank}

Registration functions undertaken by the registration authority under the provisions of the relevant International Standard shall require no financial contribution from ISO or IEC or their members. This would not preclude, however, the charging for services provided by the registration authority if duly authorized by the council board.
