[[annexA]]
[appendix,obligation=normative]
== Guides

[[scls-A-1]]
=== Introduction

In addition to International Standards, Technical Specifications, Publicly Available Specifications and Technical Reports prepared by technical committees, ISO and IEC publish Guides on matters related to international standardization. Guides shall be drafted in accordance with the ISO/IEC Directives, Part 2.

Guides shall not be prepared by technical committees and subcommittees. They may be prepared by an ISO Policy Development Committee, an IEC Advisory Committee or Strategic Group, an ISO group reporting to the ISO technical management board, or an ISO/IEC Joint Coordination Group. These bodies are referred to below as the "Committee or Group responsible for the project".

The procedure for preparation and publication of a Guide is as described below.

[[scls-A-2]]
=== Proposal stage

The ISO and/or IEC technical management board will approve proposals for new Guides or revisions of Guides and decide on the secretariat and composition of the Committee or Group responsible for the project.

Once a project is approved by the ISO and/or IEC technical management board, the secretariat of the Committee or Group responsible for the project shall ensure that the appropriate interests in ISO and IEC are informed.

[[scls-A-3]]
=== Preparatory stage

The Committee or Group responsible for the project shall ensure that the appropriate interests in ISO and IEC have the opportunity to be represented during the preparation of the working draft.

[[scls-A-4]]
=== Committee stage

Once a working draft is available for circulation as a committee draft, the secretariat of the Committee or Group responsible for the project shall send it to the parent committee or ISO and/or IEC technical management board for vote, comments and to approve its advancement to the Enquiry stage.

[[scls-A-5]]
=== Enquiry stage

[[scls-A-5-1]]
==== {blank}

The office of the CEOs shall circulate both the English and French texts of the revised draft Guide to all National Bodies for an 8-week translation and preparation period prior to 12-week vote.

[[scls-A-5-2]]
==== {blank}

The draft Guide is approved for publication as a Guide if not more than one-quarter of the votes cast are negative, abstentions being excluded when the votes are counted.

In the case of ISO/IEC Guides, the draft shall be submitted for approval to the National Bodies of both ISO and IEC. The National Bodies of both organizations need to approve the document if it is to be published as an ISO/IEC Guide.

If this condition is satisfied for only one of the organizations, ISO or IEC, the Guide may be published under the name of the approving organization only, unless the Committee or Group responsible for the project decides to apply the procedure set out in <<scls-A-5-3>>.

[[scls-A-5-3]]
==== {blank}

If a draft Guide is not approved, or if it is approved with comments the acceptance of which would improve consensus, the chair of the Committee or Group responsible for the project may decide to submit an amended draft for a 8-week vote. The conditions for acceptance of the amended draft are the same as in <<scls-A-5-2>>.

[[scls-A-6]]
=== Publication stage

The publication stage shall be the responsibility of the office of the CEO of the organization to which the Committee or Group responsible for the project belongs.

In the case of a Joint ISO/IEC Group, the responsibility shall be decided by agreement between the Chief Executive Officers.

[[scls-A-7]]
=== Withdrawal of a Guide

The Committee or Group responsible for the Guide shall be responsible for deciding if the Guide shall be withdrawn. The formal withdrawal shall be ratified by the technical management board (TMB) in accordance with its normal procedures.
