[heading=Introduction]
== Introduction

Le présent document a été élaboré en vue de répondre à une demande, à l'échelle
mondiale, de spécifications minimales pour le riz commercialisé sur un plan
international, du fait que la plupart des lots commerciaux qui n'ont pas été nettoyés
par tamisage ou aspiration contiennent une certaine quantité de grains d'autres
céréales, de graines étrangères, d'enveloppes, de pailles, de pierres, de sable, etc.
Les matériaux végétaux peuvent avoir des propriétés physiques et biologiques qui
diffèrent de celles du constituant principal et peuvent, par conséquent, affecter le
comportement au stockage.

De plus, il convient de noter que le riz vit en permanence avec une microflore
considérable; la plupart de ces microorganismes sont cosmopolites et en majorité sans
danger, mais certains produisent des sousproduits toxiques. La microflore présente sur
le riz fraîchement récolté comprend de nombreux genres de bactéries, moisissures et
levures. Lorsque le riz mûrit et que sa teneur en eau diminue, le nombre de
microorganismes, principalement de bactéries, diminue. Lorsque le riz est récolté, il
est envahi par les microorganismes de stockage et la microflore du terrain disparaît.
Si la fraction massique d'humidité (précédemment appelée «teneur en eau») est
inférieure à 18 %, la microflore ne se multiplie pas, ce qu'elle fait rapidement
au-dessus de 18 %. Par conséquent, au moment de la moisson, la composition qualitative
et quantitative de la microflore dépend plus de facteurs écologiques que de la variété
de riz considérée. La microflore s'enrichit de microorganismes pendant le transport et
les opérations de stockage. Les microorganismes présents sur le riz à la récolte
tendent à mourir pendant le stockage et sont remplacés par des microorganismes adaptés
aux conditions de stockage.

Les pertes dues au stockage sont estimées en moyenne à 5 %, ce chiffre pouvant
atteindre et même dépasser 30 %, en particulier dans les régions aux climats favorables
au développement rapide des agents de de détérioration, comme les climats tropicaux.
L'importance de ces chiffres montre bien l'intérêt de promouvoir dans le monde
l'amélioration des techniques de conservation dans le monde.
