[heading=Terms and definitions]
== Termes et définitions

=== paddy
[alt]#riz paddy#

riz muni de sa balle après battage

[.source]
<<ISO7301,clause=3.1>>

=== riz décortiqué
[deprecated]#riz cargo#

term:[riz paddy] dont seule la balle a été éliminée

[.source]
<<ISO7301,clause=3.2>>, Le terme "riz cargo" est représenté comme rejeté. La Note 1 à
l'article a été supprimée.

=== riz usiné

riz obtenu après une opération de mouture mécanique qui consiste à débarrasser le
term:[riz décortiqué] de tout ou partie de son péricarpe et du germe

[.source]
<<ISO7301,clause=3.3>>

=== riz étuvé
[alt]#riz prétraité#

riz dont l'amidon a été entièrement gélatinisé par trempage dans l'eau du
term:[riz paddy] ou du term:[riz décortiqué] suivi d'un traitement à la chaleur, puis
d'une opération de séchage

=== riz gluant

variété spéciale de riz, dont les grains ont un aspect blanc et opaque

NOTE: L'amidon du riz gluant est presque entièrement constitué d'amylopectine. Les
grains ont tendance à se prendre en masse après cuisson.

=== matière étrangère
[alt]#ME#
[domain]#riz#

élément organique et non organique autre que les grains de riz, entiers ou brisés

[example]
Graines étrangères, coques, fibre, sable, poussière.

=== HDK
[alt]#grain échauffé#

grain ou partie de grain, dont la coloration naturelle a changé sous l'effet de la
chaleur

NOTE: Cette catégorie comprend les grains ou parties de grains présentant une
coloration jaune due à une altération. Les grains de term:[riz étuvé] dans un lot de
riz non étuvé sont également compris dans cette catégorie.

=== grain endommagé

grain ou partie de grain présentant distinctement une détérioration provoquée par
l'humidité, les déprédateurs, les maladies ou d'autres causes, mais qui n'est pas un
term:[HDK]

=== grain immature
[alt]#grain non mûr#

grain ou partie de grain, non mûre ou sous-développée, ou les deux

=== rendement en riz décortiqué

quantité de term:[riz décortiqué] obtenue à partir de riz paddy

[.source]
<<ISO6646,clause=3.1>>

=== teneur en azote

quantité d'azote déterminée après l'application du mode opératoire décrit dans
l'<<ISO20483>>

NOTE: Elle est exprimée en fraction massique de produit sec, en pourcentage.

[.source]
<<ISO20483,clause=3.1>>, Dans la définition, «dans l'ISO 20483» a été ajouté

=== protéines brutes

quantité de protéines brutes obtenue à partir de la teneur en azote telle que
déterminée en appliquant la méthode décrite dans l'ISO 20483, calculée en multipliant
cette teneur par un facteur approprié selon le type de céréale ou de légumineuse

NOTE: Elle est exprimée en fraction massique de produit sec, en pourcentage.

[.source]
<<ISO20483,clause=3.2>>, Dans la définition, «décrite dans l'ISO 20483» a été ajouté

=== gélatinisation

processus hydrothermique correspondant au phénomène de gonflement irréversible et de
solubilisation des grains d'amidon et conférant au grain de riz un état gélatinisé
typique des empois d'amidon

NOTE: Voir <<figureC-1>>.

[.source]
<<ISO14864,clause=3.1>>, Note 1 à l'article ajoutée

=== état gélatinisé

état atteint à la suite de la term:[gélatinisation], lorsque le grain de riz est
entièrement transparent et totalement exempt de granules blanchâtres et opaques après
avoir été écrasé entre deux lamelles de verre

[.source]
<<ISO14864,clause=3.2>>

=== temps de gélatinisation

stem:[t_90]

temps nécessaire pour faire passer 90 % des grains de leur état naturel à
l'term:[état gélatinisé])

[.source]
<<ISO14864,clause=3.3>>, terme admis, stem:[t_"90"], ajouté à l'entrée du terme
