
[[_idTextAnchor293]]
[appendix]
== Guides

[[_idTextAnchor294]]
=== Introduction

In addition to International Standards, Technical Specifications, Publicly Available Specifications and Technical Reports prepared by technical committees, ISO and IEC publish Guides on matters related to international standardization. Guides shall be drafted in accordance with the ISO/IEC Directives, Part 2.

Guides shall not be prepared by technical committees and subcommittees. They may be prepared by an ISO Policy Development Committee, an IEC Advisory Committee or Strategic Group, an ISO group reporting to the ISO technical management board, or an ISO/IEC Joint Coordination Group. These bodies are referred to below as the "Committee or Group responsible for the project".

The procedure for preparation and publication of a Guide is as described below.


[[_idTextAnchor295]]
=== Proposal stage

The ISO and/or IEC technical management board will approve proposals for new Guides or revisions of Guides and decide on the secretariat and composition of the Committee or Group responsible for the project.

Once a project is approved by the ISO and/or IEC technical management board, the secretariat of the Committee or Group responsible for the project shall ensure that the appropriate interests in ISO and IEC are informed.


[[_idTextAnchor296]]
=== Preparatory stage

The Committee or Group responsible for the project shall ensure that the appropriate interests in ISO and IEC have the opportunity to be represented during the preparation of the working draft.


[[_idTextAnchor297]]
=== Committee stage

Once a working draft is available for circulation as a committee draft, the secretariat of the Committee or Group responsible for the project shall send it to the parent committee or ISO and/or IEC technical management board for vote, comments and to approve its advancement to the Enquiry stage.


[[_idTextAnchor298]]
=== Enquiry stage


[[_idTextAnchor299]]
==== {blank}

The office of the CEOs shall circulate both the English and French texts of the revised draft Guide to all National Bodies for an 8-week translation and preparation period prior to 12-week vote.


[[_idTextAnchor300]]
==== {blank}

The draft Guide is approved for publication as a Guide if not more than one-quarter of the votes cast are negative, abstentions being excluded when the votes are counted.

In the case of ISO/IEC Guides, the draft shall be submitted for approval to the National Bodies of both ISO and IEC. The National Bodies of both organizations need to approve the document if it is to be published as an ISO/IEC Guide.

If this condition is satisfied for only one of the organizations, ISO or IEC, the Guide may be published under the name of the approving organization only, unless the Committee or Group responsible for the project decides to apply the procedure set out in <<_idTextAnchor301>>.


[[_idTextAnchor301]]
==== {blank}

If a draft Guide is not approved, or if it is approved with comments the acceptance of which would improve consensus, the chair of the Committee or Group responsible for the project may decide to submit an amended draft for a 8-week vote. The conditions for acceptance of the amended draft are the same as in <<_idTextAnchor300>>.


[[_idTextAnchor302]]
=== Publication stage

The publication stage shall be the responsibility of the office of the CEO of the organization to which the Committee or Group responsible for the project belongs.

In the case of a Joint ISO/IEC Group, the responsibility shall be decided by agreement between the Chief Executive Officers.


[[_idTextAnchor303]]
=== Withdrawal of a Guide

The Committee or Group responsible for the Guide shall be responsible for deciding if the Guide shall be withdrawn. The formal withdrawal shall be ratified by the technical management board (TMB) in accordance with its normal procedures.


[[_idTextAnchor304]]
=== Procedure for transforming a guide into an ISO International Standard

==== Submission of a proposal for transformation of a Guide into an International Standard

Any member body, organization in liaison or group reporting to the TMB ("Authorized bodies"), or the ISO CEO, can propose that an approved Guide be transformed into an ISO International Standard. All proposals shall be accompanied by justification for the transformation into an International Standard.


==== Circulation of the proposal

The offices of the CEO's circulate the proposal to all member bodies for approval.


==== Member body ballot

===== {blank}

The ballot will ask the question: Do you approve the transformation of Guide XX into an ISO International Standard?


===== {blank}

Members will have the option of responding yes or no and the reasons for their negative vote should be provided.


===== {blank}

Because the Guide in question has been developed and approved according to the consensus building procedures of ISO and/or IEC, technical or editorial comments will not be considered. Consideration of such comments will be held over to the next revision of the International Standard if the transformation of the Guide is approved.


===== {blank}

The voting period and voting rules are the same as for the normal DIS vote.


==== Approval criteria

===== {blank}

If more than one quarter of all votes received is negative, the transformation into an International Standard is not approved and the approval process ends.


===== {blank}

If the transformation of a Guide into a standard is approved, the International Standard will be published, and the original Guide withdrawn.


==== Maintenance of the International Standard resulting from a transformed guide

The ISO technical management board will decide on a case-by-case basis how to handle the maintenance of transformed Guide. Preference will be given to assigning the maintenance responsibility to an appropriate TC, but, in the absence of an appropriate TC, the TMB will decide where to assign maintenance responsibility, including through the establishment of a new TC or PC.
