

[[_idTextAnchor306]]
[appendix]
== ISO/IEC procedures for liaison and work allocation

[[_idTextAnchor307]]
=== Introduction

By the ISO/IEC Agreement of 1976 footnote:[ISO Council resolutions 49/1976 and 50/1976 and IEC Administrative Circular No. 13/1977.], ISO and IEC together form a system for international standardization as a whole. For this system to operate efficiently, the following procedures are agreed for coordination and allocation of work between the technical committees and subcommittees of both organizations.


[[_idTextAnchor308]]
=== General considerations

The allocation of work between ISO and IEC is based on the agreed principle that all questions relating to international standardization in the electrical and electronic engineering fields are reserved to IEC, the other fields being reserved to ISO and that allocation of responsibility for matters of international standardization where the relative contribution of electrical and non-electrical technologies is not immediately evident will be settled by mutual agreement between the organizations.

Questions of coordination and work allocation may arise when establishing a new ISO or IEC technical committee, or as a result of the activities of an existing technical committee.

The following levels of coordination and work allocation agreement are available. Matters should be raised at the next higher level only after all attempts to resolve them at the lower levels have failed.

. Formal liaisons between ISO and IEC committees for normal inter-committee cooperation.
. Organizational consultations, including technical experts and representatives of the Chief Executive Officers, for cases where technical coordination may have an effect on the future activities of the organizations in a larger sense than the point under consideration.
. Decisions on work allocation
+
--
* by the technical management boards or, if necessary,
* the ISO/IEC Joint Technical Advisory Board (JTAB).
--

Questions affecting both ISO and IEC, on which it has not proved possible to obtain a common decision by the ISO Technical Management Board and the IEC Standardization Management Board, are referred to the ISO/IEC Joint Technical Advisory Board (JTAB) for decision (see <<_idTextAnchor017>>).


[[_idTextAnchor309]]
=== Establishing new technical committees

Whenever a proposal to establish a new technical committee is made to the National Bodies of ISO or of IEC respectively, the proposal shall also be submitted to the other organization requesting comment and/or agreement. As a result of these consultations, two cases may arise:

. [[item_309-a]]the opinion is unanimous that the work should be carried out in one of the organizations;
. [[item_309-b]]opinions are divided.

In case <<item_309-a>>, formal action may then be taken to establish the new technical committee according to the unanimous opinion.

In case <<item_309-b>>, a meeting of experts in the field concerned shall be arranged with representatives of the Chief Executive Officers with a view to reaching a satisfactory agreement for allocation of the work (i.e., organizational level). If agreement is reached at this level, formal action may be taken by the appropriate organization to implement the agreement.

In the case of disagreement after these consultations, the matter may be referred by either organization to the ISO/IEC Joint Technical Advisory Board (JTAB).


[[_idTextAnchor310]]
=== Coordinating and allocating work between ISO and IEC technical committees

[[_idTextAnchor311]]
==== Formal liaison at TC level

Most coordination needs arising between individual ISO and IEC committees are successfully dealt with through formal technical liaison arrangements. These arrangements, when requested by either organization, shall be honoured by the other organization. Requests for formal liaison arrangements are controlled by the offices of the CEOs. The requesting organization shall specify the type of liaison required, such as:

. full or selective exchange of committee documents;
. regular or selective attendance of liaison representatives at meetings;
. participation in a standing coordination (or steering) committee for selected ISO and IEC technical committees;
. setting up of a Joint Working Group (JWG).


[[_idTextAnchor312]]
==== Details of agreement

[[_idTextAnchor313]]
===== {blank}

Continual efforts shall be made to minimize the overlap areas between IEC and ISO by entrusting areas of work to one of the two organizations.

For areas of work so entrusted, IEC and ISO shall agree through the JTAB on how the views and interests of the other organization are to be fully taken into account.


[[_idTextAnchor314]]
===== Five working modes of cooperation have been established, as follows:

====== Mode 1 -- Informative relation

One organization is fully entrusted with a specific work area and keeps the other fully informed of all progress.


====== Mode 2 -- Contributive relation

One organization should take the lead of the work and the other should make written contributions where considered appropriate during the progress of this work. This relation also includes the exchange of full information.


====== Mode 3 -- Subcontracting relation

One organization is fully entrusted with the realization of the work on an identified item, but due to specialization of the other, a part of the work is subcontracted and that part is prepared under the responsibility of the second organization. Necessary arrangements shall be made to guarantee the correct integration of the resulting subcontracted work into the main part of the programme. The enquiry and approval stages are handled by the organization being the main contractor for the standardization task.


====== Mode 4 -- Collaborative relation

One organization takes the lead in the activities, but the work sessions and meetings receive liaison representatives from the other. Such liaison representatives should have the right to intervene in the debate but have no right to vote. The full flow of information is oriented through this liaison.


====== Mode 5 -- Integrated liaison

Joint Working Groups and Joint Technical Committees ensure integrated meetings for handling together the realization of standards under a principle of total equality of participation.

Joint Working Groups between technical committees of the two organizations shall operate in accordance with <<_idTextAnchor074>>.


[[_idTextAnchor315]]
===== {blank}

The allocation of work between IEC and ISO for potentially overlapping areas will be set out as required in schedules or programmes which, when agreed by the relevant parties, will form addenda to this agreement.

A consequence of this agreement is that the parties agree to cross-refer to the relevant standards of the other in the respective competent fields of interest.

When the standard being referred to is updated, it is the responsibility of the body making the reference to take care of the updating of the reference where appropriate.


[[_idTextAnchor316]]
===== {blank}

For work for which one organization has assumed responsibility and for which there will be subcontracting of work to the other, the fullest account shall be taken of the interests participating in the subcontracted work in defining the objectives of that work.


[[_idTextAnchor317]]
===== {blank}

The necessary procedures for enquiry and approval shall be realized by the organization entrusted with a particular standardization task, except as otherwise agreed by the two technical management boards.


[[_idTextAnchor318]]
===== {blank}

For standards developed under the Mode 5 -- Integrated liaison, the committee, enquiry and approval stages shall be carried out in parallel in both ISO and IEC in accordance with the rules of the organization with the administrative lead. The committee/organization with the administrative responsibility for the project shall submit drafts for the committee, enquiry and approval stages to the other organization two weeks prior to the circulation date.


[[_idTextAnchor319]]
===== {blank}

When the enquiry draft has not fulfilled the approval criteria (see <<_idTextAnchor176>>) in one of the organizations, then:

* the officers of the committees involved in the joint working group may select one of options given in <<_idTextAnchor177>> c) or

* in exceptional circumstances, if agreed between the officers of the ISO and IEC committees involved in the joint working group and the offices of the CEO, the project may proceed as a single logo standard of the organization in which the enquiry draft was approved. The joint working group is automatically disbanded.


[[_idTextAnchor320]]
===== {blank}

If the final draft International Standard is not approved in accordance of the conditions in <<_idTextAnchor186>> then:

* the committees involved in the joint working group may select one of the options given in <<_idTextAnchor190>>, noting that in IEC the circulation of a second final draft International Standard is not allowed and will require a derogation of the TMB or

* in exceptional circumstances, if agreed between the officers of the ISO and IEC committees involved in the joint working group and the offices of the CEO, the standard may be published as a single logo standard of the organization in which the final draft International Standard was approved. The joint working group is automatically disbanded.


[[_idTextAnchor321]]
===== {blank}

Standards developed under the Mode 5 -- Integrated liaison via a joint working group between ISO and IEC are published by the organization of the committee having administrative responsibility. That organization assigns the reference number of the standard and owns the copyright of the standard. The standard carries the logo of both organizations and may be sold by both organizations. The foreword of the International Standard will identify all the committees responsible for the development. For those standards where the committee with the administrative responsibility is in the IEC, then the foreword will also give the ISO voting results. ISO-lead documents are assigned numbers from 1 to 59999. IEC-lead documents are assigned numbers from 60000 to 79999. In the case of multi-part standards, some parts being under ISO responsibility and some being under IEC responsibility, a number in the 80000 series is assigned (e.g. ISO 80000-1, IEC 80000-6).


[[_idTextAnchor322]]
===== {blank}

0The maintenance procedures to be used for standards developed under the Mode 5 -- Integrated liaison will be those currently applied in the organization which has the committee with the administrative responsibility.


[[_idTextAnchor323]]
===== {blank}

1If there is a reason, during the development of the project, to change from one mode of operation to another, a recommendation shall be made by both technical committees concerned and submitted to the two technical management boards for information.


[[_idTextAnchor324]]
==== Cooperation of secretariats

The secretariats of the technical committees/subcommittees from the two organizations concerned shall cooperate on the implementation of this agreement. There shall be a complete information flow on on-going work and availability on demand to each other of working documents, in accordance with normal procedures.
