


[[_idTextAnchor326]]
[appendix]
== Justification of proposals for the establishment of standards

[[_idTextAnchor327]]
=== General


[[_idTextAnchor328]]
==== {blank}

Because of the large financial resources and manpower involved and the necessity to allocate these according to the needs, it is important that any standardization activity begin by identifying the needs, determining the aims of the standard(s) to be prepared and the interests that may be affected. This will, moreover, help to ensure that the standards produced will cover appropriately the aspects required and be market relevant for the affected sectors. Any new activity shall therefore be reasonably justified before it is begun.


[[_idTextAnchor329]]
==== {blank}

It is understood that, whatever conclusions may be drawn on the basis of the annex, a prerequisite of any new work to be commenced would be a clear indication of the readiness of a sufficient number of relevant interested parties to allocate necessary manpower, funds and to take an active part in the work.


[[_idTextAnchor330]]
==== {blank}

This annex sets out rules for proposing and justifying new work, so that proposals will offer to others the clearest possible idea of the purposes and extent of the work, in order to ensure that standardization resources are really allocated by the parties concerned and are used to the best effect.


[[_idTextAnchor331]]
==== {blank}

This annex does not contain rules of procedure for implementing and monitoring the guidelines contained in it, nor does it deal with the administrative mechanism which should be established to this effect.


[[_idTextAnchor332]]
==== {blank}

This annex is addressed primarily to the proposer of any kind of new work to be started but may serve as a tool for those who will analyse such a proposal or comment on it, as well as for the body responsible for taking a decision on the proposal.


[[_idTextAnchor333]]
=== Terms and definitions

==== proposal for new work

proposal for a new field of technical activity or for a new work item
  

==== proposal for a new field of technical activity

proposal for the preparation of (a) standard(s) in a field that is not covered by an existing committee (such as a technical committee, subcommittee or project committee) of the organization to which the proposal is made


==== proposal for a new work item

proposal for the preparation of a standard or a series of related standards in the field covered by an existing committee (such as a technical committee) of the organization to which the proposal is made


[[_idTextAnchor334]]
=== General principles

[[_idTextAnchor335]]
==== {blank}

Any proposal for new work shall lie within the scope of the organization to which it is submitted.

NOTE: For example, the objects of ISO are laid down in its Statutes and of IEC in <<_idTextAnchor109>> of its Statutes.


[[_idTextAnchor336]]
==== {blank}

The documentation justifying new work in ISO and IEC shall make a substantial case for the market relevance of the proposal.


[[_idTextAnchor337]]
==== {blank}

The documentation justifying new work in ISO and IEC shall provide solid information as a foundation for informed ISO or IEC National Body voting.


[[_idTextAnchor338]]
==== {blank}

Within the ISO and IEC systems, the onus is considered to be placed on the proposer to provide the proper documentation to support principles <<_idTextAnchor336>> and <<_idTextAnchor337>> stated above.


[[_idTextAnchor339]]
=== Elements to be clarified when proposing a new field of technical activity or a new work item

[[_idTextAnchor340]]
==== C.4.1Proposals for new fields of technical activity and new work items shall include the following fields of information (<<_idTextAnchor341>> to <<_idTextAnchor371>>).

[[_idTextAnchor341]]
==== C.4.2Title

The title shall indicate clearly yet concisely the new field of technical activity or the new work item which the proposal is intended to cover.

EXAMPLE 1(proposal for a new technical activity) "Machine tools".

EXAMPLE 2(proposal for a new work item) "Electrotechnical products -- Basic environmental testing procedures".


[[_idTextAnchor342]]
==== Scope

[[_idTextAnchor343]]
===== For new fields of technical activity

The scope shall precisely define the limits of the field of activity. Scopes shall not repeat general aims and principles governing the work of the organization but shall indicate the specific area concerned.

[example]
"Standardization of all machine tools for the working of metal, wood and plastics, operating by removal of material or by pressure".


[[_idTextAnchor344]]
===== For new work items

The scope shall give a clear indication of the coverage of the proposed new work item and, if necessary for clarity, exclusions shall be stated.

====
This standard lists a series of environmental test procedures, and their severities, designed to assess the ability of electrotechnical products to perform under expected conditions of service.

Although primarily intended for such applications, this standard may be used in other fields where desired.

Other environmental tests, specific to the individual types of specimen, may be included in the relevant specifications.
====


====
Standardization in the field of fisheries and aquaculture, including, but not limited to, terminology, technical specifications for equipment and for their operation, characterization of aquaculture sites and maintenance of appropriate physical, chemical and biological conditions, environmental monitoring, data reporting, traceability and waste disposal.

Excluded:

* methods of analysis of food products (covered by ISO/TC 34);
* personal protective clothing (covered by ISO/TC 94);
* environmental monitoring (covered by ISO/TC 207).
====


[[_idTextAnchor345]]
==== Proposed initial programme of work (for proposals for new fields of technical activity only)

[[_idTextAnchor346]]
===== {blank}

The proposed programme of work shall correspond to and clearly reflect the aims of the standardization activities and shall, therefore, show the relationship between the subjects proposed.


[[_idTextAnchor347]]
===== {blank}

Each item on the programme of work shall be defined by both the subject and aspect(s) to be standardized (for products, for example, the items would be the types of products, characteristics, other requirements, data to be supplied, test methods, etc.).


[[_idTextAnchor348]]
===== {blank}

Supplementary justification may be combined with particular items in the programme of work.


[[_idTextAnchor349]]
===== {blank}

The proposed programme of work shall also suggest priorities and target dates for new work items (when a series of standards is proposed, priorities shall be suggested).


[[_idTextAnchor350]]
==== Indication(s) of the preferred type or types of deliverable(s) to be produced

In the case of proposals for new fields of technical activity, this may be provided under <<_idTextAnchor345>>.


[[_idTextAnchor351]]
==== A listing of relevant existing documents at the international, regional and national levels

Any known relevant documents (such as standards and regulations) shall be listed, regardless of their source and should be accompanied by an indication of their significance.


[[_idTextAnchor352]]
==== Relation to and impact on existing work

[[_idTextAnchor353]]
===== {blank}

A statement shall be provided regarding any relation or impact the proposed work may have on existing work, especially existing ISO and IEC deliverables. The proposer should explain how the work differs from apparently similar work, or explain how duplication and conflict will be minimized.


[[_idTextAnchor354]]
===== {blank}

If seemingly similar or related work is already in the scope of other committees of the organization or in other organizations, the proposed scope shall distinguish between the proposed work and the other work.


[[_idTextAnchor355]]
===== {blank}

The proposer shall indicate whether his or her proposal could be dealt with by widening the scope of an existing committee or by establishing a new committee.


[[_idTextAnchor356]]
==== Relevant country participation

[[_idTextAnchor357]]
===== {blank}

For proposals for new fields of technical activity, a listing of relevant countries should be provided where the subject of the proposal is important to their national commercial interests.


[[_idTextAnchor358]]
===== {blank}

For proposals for new work item within existing committees, a listing of relevant countries should be provided which are not already P-members of the committee, but for whom the subject of the proposal is important to their national commercial interests.


[[_idTextAnchor359]]
==== Cooperation and liaison

[[_idTextAnchor360]]
===== {blank}

A list of relevant external international organizations or internal parties (other than ISO and/or IEC committees) to be engaged as liaisons in the development of the deliverable(s) shall be provided.


[[_idTextAnchor361]]
===== {blank}

In order to avoid conflict with, or duplication of efforts of, other bodies, it is important to indicate all points of possible conflict or overlap.


[[_idTextAnchor362]]
===== {blank}

The result of any communication with other interested bodies shall also be included.


[[_idTextAnchor363]]
==== Affected stakeholders

A simple and concise statement shall be provided identifying and describing relevant affected stakeholder categories (including small and medium sized enterprises) and how they will each benefit from or be impacted by the proposed deliverable(s).


[[_idTextAnchor364]]
==== Base document (for proposals for new work items only)

[[_idTextAnchor365]]
===== {blank}

When the proposer considers that an existing well-established document may be acceptable as a standard (with or without amendments) this shall be indicated with appropriate justification and a copy attached to the proposal.


[[_idTextAnchor366]]
===== {blank}

All proposals for new work items shall include an attached existing document to serve as an initial basis for the ISO or IEC deliverable or a proposed outline or table of contents.


[[_idTextAnchor367]]
===== {blank}

If an existing document is attached that is copyrighted or includes copyrighted content, the proposer shall ensure that appropriate permissions have been granted in writing for ISO or IEC to use that copyrighted content.


[[_idTextAnchor368]]
==== Leadership commitment

[[_idTextAnchor369]]
===== {blank}

In the case of a proposal for a new field of technical activity, the proposer shall indicate whether his/her organization is prepared to undertake the secretariat work required.


[[_idTextAnchor370]]
===== {blank}

In the case of a proposal for new work item, the proposer shall also nominate a project leader.


[[_idTextAnchor371]]
==== Purpose and justification

[[_idTextAnchor372]]
===== {blank}

The purpose and justification of the standard to be prepared shall be made clear and the need for standardization of each aspect (such as characteristics) to be included in the standard shall be justified.


[[_idTextAnchor373]]
===== {blank}

If a series of new work items is proposed the purpose and the justification of which is common, a common proposal may be drafted including all elements to be clarified and enumerating the titles and scopes of each individual item.


[[_idTextAnchor374]]
===== {blank}

Please note that the items listed in the bullet points below represent a menu of suggestions or ideas for possible documentation to support the purpose and justification of proposals. Proposers should consider these suggestions, but they are not limited to them, nor are they required to comply strictly with them. What is most important is that proposers develop and provide purpose and justification information that is most relevant to their proposals and that makes a substantial business case for the market relevance and need of their proposals. Thorough, well-developed and robust purpose and justification documentation will lead to more informed consideration of proposals and ultimately their possible success in the ISO and IEC systems.

* A simple and concise statement describing the business, technological, societal or environmental issue that the proposal seeks to address, preferably linked to the Strategic Business Plan of the concerned ISO or IEC committee.

* Documentation on relevant global metrics that demonstrate the extent or magnitude of the economic, technological, societal or environmental issue, or the new market. This may include an estimate of the potential sales of the resulting standard(s) as an indicator of potential usage and global relevance.

* Technological benefit -- a simple and concise statement describing the technological impact of the proposal to support coherence in systems and emerging technologies, convergence of merging technologies, interoperability, resolution of competing technologies, future innovation, etc.

* Economic benefit -- a simple and concise statement describing the potential of the proposal to remove barriers to trade, improve international market access, support public procurement, improve business efficiency for a broad range of enterprises including small and medium sized ones, and/or result in a flexible, cost-effective means of complying with international and regional rules/conventions, etc. A simple cost/benefit analysis relating the cost of producing the deliverable(s) to the expected economic benefit to businesses worldwide may also be helpful.

* Societal benefit(s) -- a simple and concise statement describing any societal benefits expected from the proposed deliverable(s).

* Environmental benefit(s) -- a simple and concise statement describing any environmental or wider sustainability benefits expected from the proposed deliverable(s).

* A simple and concise statement clearly describing the intended use(s) of the proposed deliverable(s), for example, whether the deliverable is intended as requirements to support conformity assessment or only as guidance or recommended best practices; whether the deliverable is a management system standard; whether the deliverable is intended for use or reference in technical regulation; whether the deliverable is intended to be used to support legal cases in relation to international treaties and agreements.

* A simple and concise statement of metrics for the committee to track in order to assess the impact of the published standard over time to achieve the benefits to stakeholders documented under <<_idTextAnchor363>> above.

* A statement assessing the prospect of the resulting deliverable(s) being compliant with, for the IEC, the IEC Global Relevance Policy: https://www.iec.ch/members_experts/refdocs/ac_cl/AC_200817e_AC.pdf[https://www.iec.ch/members_experts/refdocs/ac_cl/AC_200817e_AC.pdf] and for ISO, with ISO's Global Relevance Policy https://www.iso.org/iso/home/standards_development/governance_of_technical_work.htm[https://www.iso.org/iso/home/standards_development/governance_of_technical_work.htm] and the ISO/TMB recommendations (see NOTE below) regarding sustainable development and sustainability, where relevant.

NOTE: For ISO, the ISO/TMB confirmed the following recommendations: 1) When a committee (in any sector) develops a standard dealing with sustainability/sustainable development the standard must remain within the context of the committee's scope of work; 2) The committee should also notify the TMB with the title and scope as early as possible; 3) The committee undertaking such work should clarify its intentions in the Introduction of the specific standard(s); 4) The most widely used definition of sustainable development is the one from the UN Brundtland committee on sustainable development: development that meets the needs of the present without compromising the ability of future generations to meet their own needs.

* A statement assessing the proposal's compliance with the Principles for developing ISO and IEC Standards related to or supporting public policy initiatives (for ISO see Annex SO in the Consolidated ISO Supplement and for IEC and ISO see http://www.iso.org/sites/policy/[Using and referencing ISO and IEC standards to support public policy]: http://www.iso.org/sites/policy/[http://www.iso.org/sites/policy/]) and the possible relation of the resulting deliverable(s) to public policy, including a statement regarding the potential for easier market access due to conformity with appropriate legislation.
