
[[_idTextAnchor376]]
[appendix]
== Resources of secretariats and qualifications of secretaries

[[_idTextAnchor377]]
=== Terms and definitions

==== secretariat

National Body to which has been assigned, by mutual agreement, the responsibility for providing technical and administrative services to a technical committee or subcommittee

==== secretary

individual appointed by the secretariat to manage the technical and administrative services provided


[[_idTextAnchor378]]
=== Resources of a secretariat

A National Body to which a secretariat has been assigned shall recognize that, no matter what arrangements it makes in its country to provide the required services, it is the National Body itself that is ultimately responsible for the proper functioning of the secretariat. National Bodies undertaking secretariat functions shall become party to the ISO Service Agreement or IEC Basic Agreement, as appropriate.

The secretariat shall therefore have adequate administrative and financial means or backing to ensure:

. facilities for word-processing in English and/or French, for providing texts electronically, and for any necessary reproduction of documents;
. preparation of adequate technical illustrations;
. identification and use, with translation where necessary, of documents received in the official languages;
. updating and continuous supervision of the structure of the committee and its subsidiary bodies, if any;
. reception and prompt dispatch of correspondence and documents;
. adequate communication facilities by telephone, telefax and electronic mail;
. access to the Internet;
. arrangements and facilities for translation, interpretation and services during meetings, in collaboration with the host National Body, as required;
. attendance of the secretary at any meetings requiring his/her presence, including technical committee and/or subcommittee meetings, editing committee meetings, working group meetings, and consultations with the chair when necessary;
. access by the secretary to basic International Standards (see the ISO/IEC Directives, Part 2 on "Referencing Documents and sources for drafting") and to International Standards, national standards and/or related documents in the field under consideration;
. access by the secretary, when necessary, to experts capable of advising on technical issues in the field of the committee.

Whilst the Chief Executive Officer endeavours to send his/her representative to the first meeting of a technical committee, to meetings of technical committees with new secretariats, and to any technical committee or subcommittee meeting where such presence is desirable for solving problems, the office of the CEO cannot undertake to carry out the work for a secretariat, on a permanent or temporary basis.


[[_idTextAnchor379]]
=== Requirements of a secretary

The individual appointed as secretary shall

. have sufficient knowledge of English and/or French;
. be familiar with the Statutes and rules of procedure, as appropriate, and with the ISO/IEC Directives (see the respective Supplements to the ISO/IEC Directives);
. be in a position to advise the committee and any subsidiary bodies on any point of procedure or drafting, after consultation with the office of the CEO if necessary;
. be aware of any council board or technical management board decision regarding the activities of the technical committees in general and of the committee for which s/he is responsible in particular;
. be a good organizer and have training in and ability for technical and administrative work, in order to organize and conduct the work of the committee and to promote active participation on the part of committee members and subsidiary bodies, if any;
. be familiar with the documentation supplied by the offices of CEO, in particular the use of electronic tools and services.

It is recommended that newly appointed secretaries of technical committees should make an early visit to the office of the CEO in Geneva in order to discuss procedures and working methods with the staff concerned.