

[[_idTextAnchor381]]
[appendix]
== General policy on the use of languages

[[_idTextAnchor382]]
=== Expressing and communicating ideas in an international environment

At the international level, it is common practice to publish deliverables in at least two languages. There are a number of reasons why it is advantageous to use two languages, for example:

* greater clarity and accuracy of meaning can be achieved by expressing a given concept in two languages which have different grammar and syntax;

* if consensus is reached on the basis of a text drafted in only one language, difficulties may arise when it comes to putting that text into another language. Some questions may have to be rediscussed, and this can cause delay if the text originally agreed upon has to be altered. Subsequent drafting into a second language of a text already approved in the first language often brings to light difficulties of expression that could have been avoided if both versions had been prepared at the same time and then amended together;

* to ensure that international meetings will be as productive as possible, it is important for the agreements reached to be utterly devoid of ambiguity, and there has to be no risk that these agreements can be called back into question because of misunderstandings of a linguistic nature;

* the use of two languages chosen from two linguistic groups widens the number of prospective delegates who might be appointed to attend the meetings;

* it becomes easier to express a concept properly in other languages if there are already two perfectly harmonized versions.


[[_idTextAnchor383]]
=== The use of languages in the technical work

The official languages are English, French and Russian.

The work of the technical committees and the correspondence are in English by default.

For the purposes of the above, the National Body for the Russian Federation provides all interpretation and translation into and from the Russian language.

In IEC, a definitive language of development for each deliverable shall be designated in the Foreword. Specific exceptions apply to the IEV and/or database standards.


[[_idTextAnchor384]]
=== International Standards

International Standards are published by the ISO and IEC in English and in French (and sometimes in multilingual editions also including Russian and other languages, especially in cases of terminology). These versions of a given International Standard are equivalent, and each is regarded as being an original-language version.

It is advantageous for the technical content of a standard to be expressed in both English and French from the outset of the drafting procedure, so that these two versions will be studied, amended and adopted at the same time and their linguistic equivalence will be ensured at all times. (See also the ISO/IEC Directives, Part 2, clause on "Language versions").

This may be done

* by the secretariat or, under the latter's responsibility, with outside assistance, or
* by the editing committee of the responsible technical committee or subcommittee, or
* by National Bodies whose national language is English or French and under an agreement concluded between those National Bodies and the secretariat concerned.

When it is decided to publish a multilingual International Standard (a vocabulary, for example), the National Body for the Russian Federation takes charge of the Russian portion of the text; similarly, when it is decided to publish an International Standard containing terms or material in languages other than the official languages, the National Bodies whose national languages are involved are responsible for selecting the terms or for drafting the portions of text which are to be in those languages.


[[_idTextAnchor385]]
=== Other publications developed by technical committees

Other publications may be issued in one official language only.


[[_idTextAnchor386]]
=== Documents for technical committee and subcommittee meetings

[[_idTextAnchor387]]
==== {blank}

Drafts and documents referred to the agenda

The documents prepared and circulated prior to a meeting are the following.

. *Draft agendas*
+
--
Draft agendas are prepared and distributed in the language(s) of the meeting (English by default) by the responsible secretariats.
--

. *Committee drafts referred to in the agenda*
+
--
It is desirable that versions of the committee drafts referred to in the agenda will be available for the meeting in the language(s) of the meeting (English by default).

Enquiry drafts shall be available in English and French. The ISO Council or IEC Standardization Management Board guidelines shall be applied where one of the language versions is not available in due time.

Other documents (sundry proposals, comments, etc.) relating to agenda items may be prepared in only one language (English or French).
--


[[_idTextAnchor388]]
==== {blank}

Documents prepared and circulated during a meeting

The documents prepared and circulated during a meeting are the following.

. *Resolutions adopted during the meeting*
+
--
An ad hoc drafting committee, formed at the beginning of each meeting and comprising the secretary and, whenever possible, one or more delegates of English and/or French mother tongue, edits each of the proposed resolutions.
--

. *Brief minutes, if any, prepared after each session*
+
--
If such minutes are prepared, they shall be drafted in English or French and preferably in both with, if necessary, the assistance of the ad hoc drafting committee.
--


[[_idTextAnchor389]]
==== Documents prepared and circulated after a meeting

After each technical committee or subcommittee meeting, the secretariat concerned shall draft a report of the meeting, which may be in only one language (English or French) and which includes, as annex, the full text of the resolutions adopted, preferably in both English and French.


[[_idTextAnchor390]]
=== Documents prepared in languages other than English or French

National Bodies whose national language is neither English nor French may translate any documents circulated by secretariats into their own national language in order to facilitate the study of those documents by the experts of their country or to assist the delegates they have appointed to attend the meetings of the technical committees and subcommittees.

If one language is common to two or more National Bodies, one of them may at any time take the initiative of translating technical documents into that language and of providing copies to other National Bodies in the same linguistic group.

The terms of the above two paragraphs may be applied by the secretariats for their own needs.


[[_idTextAnchor391]]
=== Technical meetings

[[_idTextAnchor392]]
==== Purpose

The purpose of technical meetings is to achieve as full agreement as possible on the various agenda items and every effort shall be made to ensure that all delegates understand one another.


[[_idTextAnchor393]]
==== Interpretation of debates into English and French

Although the basic documents may be available in both English and French, it has to be determined according to the case whether interpretation of statements expressed in one language should be given in the other language

* by a volunteer delegate,
* by a staff member from the secretariat or host National Body, or
* by an adequately qualified interpreter.

Care should also be taken that delegates who have neither English nor French as mother tongue can follow the meeting to a sufficient extent.

It is impractical to specify rules concerning the necessity of interpreting the debates at technical meetings. It is essential, of course that all delegates should be able to follow the discussions, but it may not be altogether essential to have a word-for-word interpretation of each statement made.

In view of the foregoing, and except in special cases where interpretation may not be necessary, the following practice is considered appropriate:

. for meetings where procedural decisions are expected to be taken, brief interpretation may be provided by a member of the secretariat or a volunteer delegate;
. at working group meetings, the members should, whenever possible, arrange between themselves for any necessary interpretation on the initiative and under the authority of the convenor of the working group.

To enable the secretariat responsible for a meeting to make any necessary arrangements for interpretation, the secretariat should be informed, at the same time as it is notified of attendance at the meeting, of the languages in which the delegates are able to express themselves and of any aid which delegates might be able to provide in the matter of interpretation.

In those cases where a meeting is conducted mainly in one language, the following practice should be adopted as far as is practicable in order to assist delegates having the other language:

. the decision taken on one subject should be announced in both languages before passing to the next subject;
. whenever a change to an existing text is approved in one language, time should be allowed for delegates to consider the effect of this change on the other language version;
. a summary of what has been said should be provided in the other language if a delegate so requests.


[[_idTextAnchor394]]
==== Interpretation into English and French of statements made in other languages

When at a meeting of a technical committee or a subcommittee a participant wishes, in view of exceptional circumstances, to speak in any language other than English or French, the chair of the session shall be entitled to authorize this, for the session in question, provided that a means of interpretation has been secured.

In order to give all experts an equal opportunity to express their views at meetings of technical committees and subcommittees, a very flexible application of this provision is recommended.
