
[[_idTextAnchor407]]
[appendix]
== Maintenance agencies

[[_idTextAnchor408]]
=== {blank}

A technical committee or subcommittee developing an International Standard that will require a maintenance agency shall inform the Chief Executive Officer at an early stage in order that an ISO/TMB or IEC Council Board decision may be taken in advance of the publication of the International Standard.


[[_idTextAnchor409]]
=== {blank}

The ISO/TMB or IEC Council Board designates maintenance agencies in connection with International Standards, including appointment of their members, on the proposal of the technical committee concerned.


[[_idTextAnchor410]]
=== {blank}

The secretariat of a maintenance agency should be attributed wherever possible to the secretariat of the technical committee or subcommittee that has prepared the International Standard.


[[_idTextAnchor411]]
=== {blank}

The Chief Executive Officer shall be responsible for contacts with external organizations associated with the work of a maintenance agency.


[[_idTextAnchor412]]
=== {blank}

The rules of procedure of maintenance agencies shall be subject to ISO/TMB or IEC Council Board approval and any requested delegation of authority in connection with the updating of the International Standard or the issuing of amendments shall be specifically authorized by the ISO/TMB or IEC Council Board.


[[_idTextAnchor413]]
=== {blank}

Any charges for services provided by a maintenance agency shall be authorized by the council board.
