

[[_idTextAnchor435]]
[appendix]
== Formulating scopes of technical committees and subcommittees

[[_idTextAnchor436]]
=== Introduction

The scope of a technical committee or subcommittee is a statement precisely defining the limits of the work of that committee. As such it has a number of functions:

* it assists those with queries and proposals relating to a field of work to locate the appropriate committee;
* it prevents overlapping the work programmes of two or more ISO and/or IEC committees;
* it can also help guard against moving outside the field of activities authorized by the parent committee.


[[_idTextAnchor437]]
=== Formulation of scopes

Basic rules for the formulation of scopes of technical committees and subcommittees are given in <<_idTextAnchor034>>.

The order of the elements of a scope shall be:

* basic scope;
* in the ISO, horizontal functions, where applicable;
* in the IEC, horizontal and/or group safety functions where applicable;
* exclusions (if any);
* notes (if any).


[[_idTextAnchor438]]
=== Basic scope

Scopes of technical committees shall not refer to the general aims of international standardization or repeat the principles that govern the work of all technical committees.

In exceptional cases, explanatory material may be included if considered important to the understanding of the scope of the committee. Such material shall be in the form of "Notes".


[[_idTextAnchor439]]
=== Exclusions

Should it be necessary to specify that certain topics are outside the scope of the technical committee, these shall be listed and be introduced by the words "Excluded …"

Exclusions shall be clearly specified.

Where the exclusions are within the scope of one or more other existing ISO or IEC technical committees, these committees shall also be identified.

[example]
"Excluded: Those … covered by ISO/TC …".

====
"Excluded: Standardization for specific items in the field of … (ISO/TC …), … (IEC/TC …), etc.".

It is _not_ necessary to mention self-evident exclusions.
====

[example]
"Excluded: Products covered by other ISO or IEC technical committees".

[example]
"Excluded: ... Specifications for electrical equipment and apparatus, which fall within the scope of IEC committees".


[[_idTextAnchor440]]
=== Scopes of committees related to products

Scopes of committees related to products shall clearly _indicate the field, application area or market sector_ which they intend to cover, in order to easily ascertain whether a particular product is, or is not, within that field, application area or market sector.

[example]
"Standardization of … and … used in …".

[example]
"Standardization of materials, components and equipment for construction and operation of … and … as well as equipment used in the servicing and maintenance of …".

The limits of the scope can be defined by _indicating the purpose_ of the products, or by characterizing the products.

The scope _should not enumerate the types_ of product covered by the committee since to do so might suggest that other types can be, or are, standardized by other committees. However, if this is the intention, then it is preferable to list those items which are excluded from the scope.

The _enumeration of aspects_ such as terminology, technical requirements, methods of sampling, test methods, designation, marking, packaging, dimensions, etc. suggests a restriction in the scope to those particular aspects, and that other aspects may be standardized by other committees. The aspects of the products to be standardized should therefore not be included in the scope unless it is intended that the scope is limited to those particular aspects.

If the scope makes no mention of any aspect, this means that the subject _in its entirety_ is covered by the committee.

NOTE: The coverage does not necessarily mean the need for preparing a standard. It only means that standards on any aspect, if needed, will be prepared by that committee and no other.

An example of unnecessary enumeration of aspects is as follows:

[example]
"Standardization of classification, terminology, sampling, physical, chemical or other test methods, specifications, etc.".

Mention of priorities, whether referring to type of product or aspect, shall not appear in the scope since these will be indicated in the programme of work.


[[_idTextAnchor441]]
=== Scopes of committees not related to products

If the scope of a committee is intended to be limited to certain aspects which are unrelated, or only indirectly related to products, the scope shall only indicate the aspect to be covered (e.g. safety colours and signs, non-destructive testing, water quality).

The term terminology as a possible aspect of standardization should not be mentioned unless this aspect is the only task to be dealt with by the committee. If this is not the case, the mention of terminology is superfluous since this aspect is a logical part of any standardization activity.
