

[[_idTextAnchor443]]
[appendix]
== Project committees

[[_idTextAnchor444]]
=== Proposal stage

A new work item proposal not falling within the scope of an existing technical committee shall be presented using the appropriate form and fully justified (see <<_idTextAnchor146>>) by one of the bodies authorized to make new work item proposals (see <<_idTextAnchor144>>).

The office of the CEO may decide to return the proposal to the proposer for further development before circulation for voting. In this case, the proposer shall make the changes suggested or provide justification for not making the changes. If the proposer does not make the changes and requests that its proposal be circulated for voting as originally presented, the technical management board will decide on appropriate action. This could include blocking the proposal until the changes are made or accepting that it be balloted as received.

In all cases, the office of the CEO may also include comments and recommendations to the proposal form.

For details relating to justification of the proposal, see <<_idTextAnchor326>>.

In the case of a proposal to establish a project committee to prepare management system standards, see Annex SL.

It shall be submitted to the secretariat of the technical management board which shall arrange for it to be submitted to all National Bodies for voting.

Proposers are also encouraged to indicate the date of the first meeting of the project committee (see <<_idTextAnchor446>>).

If the proposal was not submitted by a National Body, the submission to the National Bodies shall include a call for offers to assume the secretariat of a project committee.

Votes shall be returned within 12 weeks.

Acceptance requires:

* approval by a 2/3 majority of the National Bodies voting;
* a commitment to participate actively by at least five National Bodies that approved the new work item proposal and nominated technical experts.


[[_idTextAnchor445]]
=== Establishment of a project committee

The technical management board shall review the results of voting on the new work item proposal and if the approval criteria are met, shall establish a project committee (the reference number shall be the next available number in the technical committee/project committee sequence).

The secretariat of the project committee shall be allocated to the National Body that submitted the proposal, or the technical management board shall decide on the allocation amongst the offers received if the proposal did not originate from a National Body.

National Bodies that approved the new work item proposal and nominated (a) technical expert(s) shall be registered as P-members of the project committee. National Bodies that approved the new work item proposal but did not make a commitment to participate actively shall be registered as O-members. National Bodies that voted negatively, but nevertheless indicated that they would participate actively if the new work item was approved, shall be registered as P-members. National Bodies voting negatively without indicating a wish to participate shall be registered as O-members.

The office of the CEO shall announce to the National Bodies the establishment of the project committee and its membership.

National Bodies will be invited to confirm/change their membership status by informing the office of the CEO.

The secretariat will contact any potential liaison organizations identified in the new work item proposal or in National Body comments thereon and will invite them to indicate whether they have an interest in the work and, if so, which category of liaison they would be interested in. Requests for liaison will be processed according to the existing procedures.


[[_idTextAnchor446]]
=== First meeting of a project committee

The procedure for calling a project committee meeting shall be carried out in accordance with <<_idTextAnchor242>>, with the exception that a six weeks' notice period may be used if the date of the first meeting was communicated at the time of submission of the proposal.

The chair of the project committee shall be the project leader nominated in the new work item proposal or shall be nominated by the secretariat if no project leader was nominated in the new work item proposal.

The first meeting shall confirm the scope of the new work item. In case revision is necessary (for purposes of clarification but not extension of the scope), the revised scope shall be submitted to the technical management board for approval. It shall also confirm the project plan and in ISO the development track and decide on any substructures needed to carry out the work.

If it is determined that the project needs to be subdivided to produce two or more publications, this is possible provided that the subdivisions of the work lie fully within the scope of the original new work item proposal. If not, a new work item will need to be prepared for consideration by the technical management board.

NOTE: Project committees are exempted from the requirement to establish a strategic business plan.


[[_idTextAnchor447]]
=== Preparatory stage

The preparatory stage shall be carried out in accordance with <<_idTextAnchor151>>.


[[_idTextAnchor448]]
=== Committee, enquiry, approval and publication stages

The committee, enquiry, approval and publication stages shall be carried out in accordance with <<_idTextAnchor161>> to  <<_idTextAnchor193>>.


[[_idTextAnchor449]]
=== Disbanding of a project committee

Once the standard(s) is/are published, the project committee shall be disbanded.


[[_idTextAnchor450]]
=== Maintenance of standard(s) prepared by a project committee

The National Body which held the secretariat shall assume responsibility for the maintenance of the standard(s) according to the procedures given in <<_idTextAnchor197>> unless the project committee has been transformed into a technical committee (see <<_idTextAnchor064>>) in which case the technical committee shall be given the responsibility for the maintenance of the standard.
