
[[terms]]
== Terms and definitions

=== accelerant

term:[fuel] or oxidizer, often an ignitable liquid, solid or gas (LGP/NP) intentionally used to initiate a fire or increase the rate of growth or spread of fire


=== area of origin of the fire

general localized area within the location where the fire started

NOTE: See also, location of the fire (3.58) and point of origin of the fire (3.64).


=== fuel
domain:[fire statistics]

material that maintains combustion under specified environmental conditions

NOTE: This definition differs from that given in <<iso13943,clause 3.189>>.


=== location of the fire

general area where the origin of the fire started

NOTE: See also, term:[area of origin of the fire], and term:[point of origin of the fire].


=== point of origin of the fire

exact physical location within the area of origin where the fire starts

NOTE: See also, term:[area of origin of the fire], and term:[location of the fire].


=== self-immolation
alt:[suicide fire]

act of killing oneself by the use of fire, often by pouring term:[accelerant] over the body and igniting it



// Illustration-purpose terms (these are not included in ISO/TS 17755-2:2020(en) original standard)

=== husked rice
deprecated:[cargo rice]

paddy from which the husk only has been removed

[.source]
<<ISO7301,clause 3.2>>, The term "cargo rice" is shown as deprecated, and Note 1 to entry is not included here

=== gelatinization time
stem:[t_90]

time necessary for 90 % of the kernels to pass from their natural state to the gel state

[.source]
<<ISO14864,clause 3.1>>